// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
	TRelationship extends
		| prismic.CustomTypeModelFetchCustomTypeLevel1
		| prismic.CustomTypeModelFetchCustomTypeLevel2
		| prismic.CustomTypeModelFetchGroupLevel1
		| prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<
		string,
		prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone
	>,
	TLang extends string,
> = {
	// Content relationship fields
	[TSubRelationship in Extract<
		TRelationship["fields"][number],
		prismic.CustomTypeModelFetchContentRelationshipLevel1
	> as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
		TSubRelationship["customtypes"],
		TLang
	>;
} & {
	// Group
	[TGroup in Extract<
		TRelationship["fields"][number],
		prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
	> as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
		? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
		: never;
} & {
	// Other fields
	[TFieldKey in Extract<TRelationship["fields"][number], string>]: TFieldKey extends keyof TData
		? TData[TFieldKey]
		: never;
};

type ContentRelationshipFieldWithData<
	TCustomType extends
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string,
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]: prismic.ContentRelationshipField<
		ID,
		TLang,
		PickContentRelationshipFieldData<
			Extract<TCustomType[number], { id: ID }>,
			Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
			TLang
		>
	>;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Flight Search → ptc type*
 */
export interface FlightSearchPageDocumentDataPtcTypeItem {
	/**
	 * type field in *Flight Search → ptc type*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: flight_search_page.ptc_type[].type
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	type: prismic.KeyTextField;

	/**
	 * name field in *Flight Search → ptc type*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: flight_search_page.ptc_type[].name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
}

/**
 * Content for Flight Search documents
 */
interface FlightSearchPageDocumentData {
	/**
	 * Page Title field in *Flight Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Flight search
	 * - **API ID Path**: flight_search_page.page_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	page_title: prismic.KeyTextField;

	/**
	 * Page Description field in *Flight Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Search flights by route, travel date, passengers, and cabin class.
	 * - **API ID Path**: flight_search_page.page_description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	page_description: prismic.KeyTextField;

	/**
	 * Label From field in *Flight Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: From
	 * - **API ID Path**: flight_search_page.label_from
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label_from: prismic.KeyTextField;

	/**
	 * Label To field in *Flight Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: To
	 * - **API ID Path**: flight_search_page.label_to
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label_to: prismic.KeyTextField;

	/**
	 * Label Departure Date field in *Flight Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Departure date
	 * - **API ID Path**: flight_search_page.label_departure_date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label_departure_date: prismic.KeyTextField;

	/**
	 * Label Return Date field in *Flight Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Return date
	 * - **API ID Path**: flight_search_page.label_return_date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label_return_date: prismic.KeyTextField;

	/**
	 * Label Passengers field in *Flight Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Passengers
	 * - **API ID Path**: flight_search_page.label_passengers
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label_passengers: prismic.KeyTextField;

	/**
	 * Label Cabin Class field in *Flight Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Cabin class
	 * - **API ID Path**: flight_search_page.label_cabin_class
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label_cabin_class: prismic.KeyTextField;

	/**
	 * Label Promo Code field in *Flight Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Promo code
	 * - **API ID Path**: flight_search_page.label_promo_code
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label_promo_code: prismic.KeyTextField;

	/**
	 * Placeholder From field in *Flight Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Tokyo (HND)
	 * - **API ID Path**: flight_search_page.placeholder_from
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	placeholder_from: prismic.KeyTextField;

	/**
	 * Placeholder To field in *Flight Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Singapore (SIN)
	 * - **API ID Path**: flight_search_page.placeholder_to
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	placeholder_to: prismic.KeyTextField;

	/**
	 * Placeholder Departure Date field in *Flight Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Select departure date
	 * - **API ID Path**: flight_search_page.placeholder_departure_date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	placeholder_departure_date: prismic.KeyTextField;

	/**
	 * Placeholder Return Date field in *Flight Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Select return date
	 * - **API ID Path**: flight_search_page.placeholder_return_date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	placeholder_return_date: prismic.KeyTextField;

	/**
	 * Placeholder Passengers field in *Flight Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 1 adult
	 * - **API ID Path**: flight_search_page.placeholder_passengers
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	placeholder_passengers: prismic.KeyTextField;

	/**
	 * Placeholder Cabin Class field in *Flight Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Economy
	 * - **API ID Path**: flight_search_page.placeholder_cabin_class
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	placeholder_cabin_class: prismic.KeyTextField;

	/**
	 * Placeholder Promo Code field in *Flight Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter code
	 * - **API ID Path**: flight_search_page.placeholder_promo_code
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	placeholder_promo_code: prismic.KeyTextField;

	/**
	 * Action Search Flights field in *Flight Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Search flights
	 * - **API ID Path**: flight_search_page.action_search_flights
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	action_search_flights: prismic.KeyTextField /**
	 * Name Error field in *Flight Search*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: flight_search_page.name_error
	 * - **Tab**: Error
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */;
	name_error: prismic.KeyTextField /**
	 * ptc type field in *Flight Search*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: flight_search_page.ptc_type[]
	 * - **Tab**: PTC
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */;
	ptc_type: prismic.GroupField<Simplify<FlightSearchPageDocumentDataPtcTypeItem>>;
}

/**
 * Flight Search document from Prismic
 *
 * - **API ID**: `flight_search_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FlightSearchPageDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<FlightSearchPageDocumentData>,
		"flight_search_page",
		Lang
	>;

/**
 * Content for IBE documents
 */
interface IbeDocumentData {
	/**
	 * Common field in *IBE*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ibe.common
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	common: prismic.ContentRelationshipField<"common">;

	/**
	 * Flight Search Page field in *IBE*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ibe.flight_search_page
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	flight_search_page: prismic.ContentRelationshipField<"flight_search_page">;

	/**
	 * Flight Select Page field in *IBE*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ibe.flight_select_page
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	flight_select_page: prismic.ContentRelationshipField<"flight_select_page">;

	/**
	 * Passenger Page field in *IBE*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ibe.passenger_page
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	passenger_page: prismic.ContentRelationshipField<"passenger_page">;

	/**
	 * Messages JSON (Optional Full Override) field in *IBE*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Optional: full JSON for all sections, same shape as apps/ibe-app/messages/en.json
	 * - **API ID Path**: ibe.messages_json
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	messages_json: prismic.KeyTextField;
}

/**
 * IBE document from Prismic
 *
 * - **API ID**: `ibe`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IbeDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<IbeDocumentData>,
	"ibe",
	Lang
>;

export type AllDocumentTypes = FlightSearchPageDocument | IbeDocument;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * Content field in *RichText → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: rich_text.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default rich text
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
	"default",
	Simplify<RichTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: Reusable rich text section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<"rich_text", RichTextSliceVariation>;

declare module "@prismicio/client" {
	type CreateClient = (
		repositoryNameOrEndpoint: string,
		options?: prismic.ClientConfig,
	) => prismic.Client<AllDocumentTypes>;

	type CreateWriteClient = (
		repositoryNameOrEndpoint: string,
		options: prismic.WriteClientConfig,
	) => prismic.WriteClient<AllDocumentTypes>;

	type CreateMigration = () => prismic.Migration<AllDocumentTypes>;

	namespace Content {
		export type {
			AllDocumentTypes,
			FlightSearchPageDocument,
			FlightSearchPageDocumentData,
			FlightSearchPageDocumentDataPtcTypeItem,
			IbeDocument,
			IbeDocumentData,
			RichTextSlice,
			RichTextSliceDefault,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
		};
	}
}
