// Defines the available product section categories shown in the extras page.

import type { Category } from "@/types/extras/extras.type";

export const EXTRAS_CATEGORIES: Category[] = [
	{ id: "all", name: "All", icon: "lists" },
	{ id: "special-offers", name: "Special Offers", icon: "sell" },
	{ id: "amenities", name: "Amenities", icon: "domino_mask" },
	{ id: "food-souvenirs", name: "Food and Souvenirs", icon: "hand_meal" },
	{ id: "snacks-souvenirs", name: "Snacks and Souvenirs", icon: "cookie" },
	{ id: "clothes-cosmetics", name: "Clothes and Cosmetics", icon: "laundry" },
	{ id: "others", name: "Others", icon: "list_alt_check" },
];

// Maps each booking stage to its corresponding i18n translation key for the extras page title.
// Used to render the correct heading depending on whether the user is selecting extras for outbound, inbound, or multi-segment flights.
export const EXTRAS_PAGE_TITLE_BY_STAGE = {
	outbound: "page_title_outbound",
	inbound: "page_title_inbound",
	segment1: "page_title_segment1",
	segment2: "page_title_segment2",
} as const;

// Allowlist of SSR (Special Service Request) codes for amenity products that are permitted to appear in the extras page.
// Sourced from the admin portal configuration — only products whose SSR code is in this set will be displayed.
export const ALLOWED_AMENITY_SSR_CODES = new Set([
	"AMEA",
	"AMEB",
	"BCBL",
	"BCBM",
	"BCBS",
	"BCLL",
	"BCLM",
	"BCLS",
	"BDBL",
	"BDBM",
	"BDBS",
	"BEBL",
	"BEBM",
	"BEBS",
	"CMAA",
	"CMAB",
	"CMAC",
	"CMAD",
	"CMAE",
	"CMAF",
	"CMAG",
	"CMAH",
	"CMAI",
	"CMAJ",
	"CMAK",
	"CMAL",
	"CMAM",
	"CMAN",
	"CMAO",
	"CMAP",
	"CMAQ",
	"CMAR",
	"CMAS",
	"CMAT",
	"CMAU",
	"CMAV",
	"CMAW",
	"CMAX",
	"CMAY",
	"CMAZ",
	"CMBA",
	"CMBB",
	"CMBC",
	"CMBD",
	"CMBE",
	"CMBF",
	"CMBG",
	"SVDA",
	"SVDB",
	"SVDC",
	"SVDD",
	"SVDE",
	"SVDF",
	"SVDG",
	"SVDH",
	"SVDI",
	"SVDJ",
	"SVDL",
	"SVDM",
	"SVDN",
	"SVDO",
	"SVDP",
	"SVDQ",
	"SVEA",
	"SVEB",
	"SVEC",
	"SVED",
	"SVEE",
	"SVEF",
	"SVEG",
	"SVEH",
	"SVEI",
	"SVEJ",
	"SVEK",
	"SVEL",
	"SVEM",
	"SVEN",
	"SVEO",
	"SVEP",
	"SVEQ",
	"SVES",
	"SVET",
	"SVEU",
	"SVEV",
	"SVEW",
	"SVEX",
	"SVEY",
	"SVEZ",
	"SVHA",
	"SVHB",
	"SVHC",
	"SVHD",
	"SVHE",
	"SVHF",
	"SVHG",
	"SVHH",
	"SVHI",
	"SVHJ",
	"SVHK",
	"SVHL",
	"SVHM",
	"SVHN",
	"SVHO",
	"SVHP",
	"SVHQ",
]);
