// @ts-nocheck - next/cache types are generated by Next.js build process
import { unstable_cache } from "next/cache";

import { getSharedEnvValue } from "../prismic/config";
import { createPrismicClient } from "../prismic/create-client";

/**
 * AssetService: Enterprise-grade CMS asset layer
 *
 * Purpose:
 * - Fetch and cache media assets (images, icons, files, PDFs, videos) from Prismic
 * - Return complete Prismic document data without contract mapping
 * - Support locale-specific assets
 * - Enable scalable addition of new asset fields without code changes
 *
 * Design Principles:
 * 1. Contract-free: Returns raw document.data, allowing Prismic schema flexibility
 * 2. Locale-aware: Resolves locales consistently with application routing
 * 3. Cache-first: Uses unstable_cache for 24-hour memoization
 * 4. Webhook-ready: Supports revalidateTag() for immediate cache invalidation
 * 5. Production-hardened: Comprehensive logging, error handling, and fallbacks
 * 6. Framework-agnostic: Lives in packages/cms, reusable across apps (ibe-app, top-app)
 *
 * Architecture:
 * - fetchCachedPrismicAssets(): Wrapper for stable cache key and TTL management
 * - createAssetService(): Factory function returning locale-aware asset resolution
 * - Asset documents fetched from Prismic with optional locale support
 * - Tags enable webhook-triggered cache invalidation per app/locale
 */

type PrismicAssetDocument = {
	id: string;
	type: string;
	lang: string;
	data: Record<string, unknown>;
};

export type CreateAssetServiceOptions = {
	applicationName: string;
	defaultLocale: string;
	locales: readonly string[];
	globalAssetsDocumentType: string;
	prismicLocaleMap: Record<string, string>;
};

export type AssetService = {
	getAssets(locale: string): Promise<Record<string, unknown>>;
	resolveLocale(locale: string | undefined): string;
};

/**
 * Cached wrapper for Prismic asset fetching.
 *
 * Implementation: Next.js unstable_cache (NOT React Cache Components or "use cache")
 *
 * Cache Strategy:
 * - Key composition: `prismic-assets:${applicationName}:${locale}`
 * - Ensures complete isolation by application and locale
 * - Reduces network calls to Prismic API
 *
 * Cache Mechanism:
 * - Uses `unstable_cache()` from "next/cache" for server-side memoization
 * - Cache lifetime: 24 hours (86400 seconds, via revalidate option)
 * - Rationale: Assets (media URLs) are stable and change infrequently
 * - Webhook-triggered invalidation via revalidateTag() provides immediate freshness
 *
 * Error Handling:
 * - Failures are NOT cached (errors throw immediately)
 * - Fallback to empty object {} if asset fetch fails
 * - Graceful degradation: missing assets logged but don't break the page
 */
export async function fetchCachedPrismicAssets(
	applicationName: string,
	locale: string,
	fetcherFn: () => Promise<Record<string, unknown>>,
): Promise<Record<string, unknown>> {
	// Create a stable cache key based on app name and locale
	const cacheKey = `prismic-assets:${applicationName}:${locale}`;

	// Use unstable_cache to memoize across requests
	// Lifetime: 24 hours = 86400 seconds
	const cachedFetcher = unstable_cache(
		async () => {
			logInfo("cache: executing uncached prismic asset fetch", {
				applicationName,
				locale,
			});

			const result = await fetcherFn();

			logInfo("cache stored", {
				applicationName,
				locale,
				cacheLifeSeconds: 86400,
				cacheKey,
				assetFieldCount: Object.keys(result).length,
			});

			return result;
		},
		[cacheKey],
		{ revalidate: 86400, tags: [`prismic-assets:${applicationName}:${locale}`] },
	);

	return cachedFetcher();
}

/**
 * Creates an app-specific asset service without coupling CMS runtime code to an app.
 *
 * Returns an object with methods:
 * - getAssets(locale): Fetch assets from Prismic (with cache) or return empty object
 * - resolveLocale(locale): Normalize locale to app's supported locales
 *
 * @example
 * const assetService = createAssetService({
 *   applicationName: "ibe-app",
 *   defaultLocale: "en",
 *   locales: ["en", "ja"],
 *   globalAssetsDocumentType: "global_assets",
 *   prismicLocaleMap: { en: "en-us", ja: "ja-jp" },
 * });
 *
 * const assets = await assetService.getAssets("en");
 * // Returns: { zipair_logo: {...}, hero_banner: {...}, ... }
 */
export function createAssetService(options: CreateAssetServiceOptions) {
	const _debugEnabled = isAssetFlowDebugEnabled();

	const resolveLocale = (locale: string | undefined) => {
		const resolvedLocale = options.locales.includes(locale ?? "")
			? (locale as string)
			: options.defaultLocale;

		return resolvedLocale;
	};

	async function getAssets(locale: string): Promise<Record<string, unknown>> {
		const resolvedLocale = resolveLocale(locale);
		const source = getServerAssetSource();

		if (source === "prismic") {
			return loadFromPrismic(resolvedLocale);
		}

		logDebug("asset source set to local, returning empty object", {
			locale: resolvedLocale,
		});

		return {};
	}

	async function loadFromPrismic(locale: string): Promise<Record<string, unknown>> {
		// Wrap fetch with unstable_cache to memoize across requests
		return fetchCachedPrismicAssets(options.applicationName, locale, async () => {
			return fetchAssets(locale);
		});
	}

	async function fetchAssets(locale: string): Promise<Record<string, unknown>> {
		const lang = options.prismicLocaleMap[locale] ?? locale;
		const client = createPrismicClient();

		logDebug("fetching prismic assets", { locale, lang });

		// Fetch the global assets document (singleton) for this locale
		const globalAssetsDocument = await fetchGlobalAssetsDocument(
			client,
			options.globalAssetsDocumentType,
			lang,
		);

		if (!globalAssetsDocument) {
			logWarn("global assets document not found", {
				locale,
				documentType: options.globalAssetsDocumentType,
			});
			return {};
		}

		logDebug("loaded global assets document", {
			locale,
			documentType: options.globalAssetsDocumentType,
			assetFieldCount: Object.keys(globalAssetsDocument.data).length,
		});

		// Return raw document data without contract mapping
		// This allows Prismic schema to evolve without code changes
		return globalAssetsDocument.data as Record<string, unknown>;
	}

	async function fetchGlobalAssetsDocument(
		client: ReturnType<typeof createPrismicClient>,
		documentType: string,
		lang: string,
	): Promise<PrismicAssetDocument | null> {
		try {
			return (await client.getSingle(documentType as never, {
				lang,
			})) as PrismicAssetDocument;
		} catch (error) {
			logDebug("prismic global assets document locale lookup failed, retrying without lang", {
				documentType,
				lang,
				error: error instanceof Error ? error.message : String(error),
			});

			try {
				return (await client.getSingle(documentType as never)) as PrismicAssetDocument;
			} catch {
				const errorMessage = `Unable to load Prismic global assets document "${documentType}" for locale "${lang}"`;
				logError(errorMessage, {
					locale: lang,
					documentType,
				});
				// Return null to enable graceful degradation
				return null;
			}
		}
	}

	return {
		getAssets,
		resolveLocale,
	};
}

/**
 * Resolves the configured server-side asset source (prismic or local).
 * Supports ASSET_SOURCE environment variable for explicit control.
 *
 * Default: "local" (no-op)
 * Production: "prismic" to fetch from Prismic CMS
 */
export function getServerAssetSource(): "local" | "prismic" {
	const source = getSharedEnvValue("ASSET_SOURCE");

	return source === "prismic" ? "prismic" : "local";
}

function isAssetFlowDebugEnabled() {
	return (
		getSharedEnvValue("IBE_DEBUG_ASSET_FLOW") === "true" ||
		getSharedEnvValue("TOP_DEBUG_ASSET_FLOW") === "true"
	);
}

/**
 * Logs at INFO level: cache operations and status updates.
 * Always logged in production.
 */
function logInfo(message: string, details?: Record<string, unknown>) {
	// biome-ignore lint: production logging
	console.info(`[asset-service] ${message}`, details ?? {});
}

/**
 * Logs at WARN level: content/configuration issues.
 * Always logged in production.
 */
function logWarn(message: string, details?: Record<string, unknown>) {
	// biome-ignore lint: production logging
	console.warn(`[asset-service] ${message}`, details ?? {});
}

/**
 * Logs at ERROR level: failures and exceptions.
 * Always logged in production.
 */
function logError(message: string, details?: Record<string, unknown>) {
	// biome-ignore lint: production logging
	console.error(`[asset-service] ${message}`, details ?? {});
}

/**
 * Logs at DEBUG level: detailed flow and state information.
 * Only logged when IBE_DEBUG_ASSET_FLOW or TOP_DEBUG_ASSET_FLOW is enabled.
 */
function logDebug(message: string, details?: Record<string, unknown>) {
	if (!isAssetFlowDebugEnabled()) {
		return;
	}

	// biome-ignore lint: debug logging
	console.debug(`[asset-service] ${message}`, details ?? {});
}
