/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type NEXUZR004OffersAncillaryRequest,
    NEXUZR004OffersAncillaryRequestFromJSON,
    NEXUZR004OffersAncillaryRequestToJSON,
} from '../models/NEXUZR004OffersAncillaryRequest';
import {
    type NEXUZR004OffersAncillaryResponse,
    NEXUZR004OffersAncillaryResponseFromJSON,
    NEXUZR004OffersAncillaryResponseToJSON,
} from '../models/NEXUZR004OffersAncillaryResponse';
import {
    type NEXUZR004OffersErrorResponse,
    NEXUZR004OffersErrorResponseFromJSON,
    NEXUZR004OffersErrorResponseToJSON,
} from '../models/NEXUZR004OffersErrorResponse';

export interface OffersAncillariesPostRequest {
    currency: string;
    nEXUZR004OffersAncillaryRequest: NEXUZR004OffersAncillaryRequest;
}

/**
 * AncillariesApi - interface
 * 
 * @export
 * @interface AncillariesApiInterface
 */
export interface AncillariesApiInterface {
    /**
     * Creates request options for offersAncillariesPost without sending the request
     * @param {string} currency Currency code for retrieving ancillaries amount.
     * @param {NEXUZR004OffersAncillaryRequest} nEXUZR004OffersAncillaryRequest Request payload containing flight details, service category and number of passengers.
     * @throws {RequiredError}
     * @memberof AncillariesApiInterface
     */
    offersAncillariesPostRequestOpts(requestParameters: OffersAncillariesPostRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieves ancillary services for a given flight based on service category and passenger details. 
     * @summary Retrieve ancillaries
     * @param {string} currency Currency code for retrieving ancillaries amount.
     * @param {NEXUZR004OffersAncillaryRequest} nEXUZR004OffersAncillaryRequest Request payload containing flight details, service category and number of passengers.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AncillariesApiInterface
     */
    offersAncillariesPostRaw(requestParameters: OffersAncillariesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR004OffersAncillaryResponse>>;

    /**
     * Retrieves ancillary services for a given flight based on service category and passenger details. 
     * Retrieve ancillaries
     */
    offersAncillariesPost(requestParameters: OffersAncillariesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR004OffersAncillaryResponse>;

}

/**
 * 
 */
export class AncillariesApi extends runtime.BaseAPI implements AncillariesApiInterface {

    /**
     * Creates request options for offersAncillariesPost without sending the request
     */
    async offersAncillariesPostRequestOpts(requestParameters: OffersAncillariesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['currency'] == null) {
            throw new runtime.RequiredError(
                'currency',
                'Required parameter "currency" was null or undefined when calling offersAncillariesPost().'
            );
        }

        if (requestParameters['nEXUZR004OffersAncillaryRequest'] == null) {
            throw new runtime.RequiredError(
                'nEXUZR004OffersAncillaryRequest',
                'Required parameter "nEXUZR004OffersAncillaryRequest" was null or undefined when calling offersAncillariesPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/offers/ancillaries`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NEXUZR004OffersAncillaryRequestToJSON(requestParameters['nEXUZR004OffersAncillaryRequest']),
        };
    }

    /**
     * Retrieves ancillary services for a given flight based on service category and passenger details. 
     * Retrieve ancillaries
     */
    async offersAncillariesPostRaw(requestParameters: OffersAncillariesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR004OffersAncillaryResponse>> {
        const requestOptions = await this.offersAncillariesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NEXUZR004OffersAncillaryResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves ancillary services for a given flight based on service category and passenger details. 
     * Retrieve ancillaries
     */
    async offersAncillariesPost(requestParameters: OffersAncillariesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR004OffersAncillaryResponse> {
        const response = await this.offersAncillariesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
