/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type NEXUZR006PaymentErrorResponse,
    NEXUZR006PaymentErrorResponseFromJSON,
    NEXUZR006PaymentErrorResponseToJSON,
} from '../models/NEXUZR006PaymentErrorResponse';
import {
    type NEXUZR006PaymentPaymentStatusRequest,
    NEXUZR006PaymentPaymentStatusRequestFromJSON,
    NEXUZR006PaymentPaymentStatusRequestToJSON,
} from '../models/NEXUZR006PaymentPaymentStatusRequest';
import {
    type NEXUZR006PaymentPaymentStatusResponse,
    NEXUZR006PaymentPaymentStatusResponseFromJSON,
    NEXUZR006PaymentPaymentStatusResponseToJSON,
} from '../models/NEXUZR006PaymentPaymentStatusResponse';
import {
    type RetrievePaymentStatus422Response,
    RetrievePaymentStatus422ResponseFromJSON,
    RetrievePaymentStatus422ResponseToJSON,
} from '../models/RetrievePaymentStatus422Response';

export interface RetrievePaymentStatusRequest {
    statusCheckKey: string;
    currency: string;
    language: string;
    nEXUZR006PaymentPaymentStatusRequest: NEXUZR006PaymentPaymentStatusRequest;
}

/**
 * PaymentStatusApi - interface
 * 
 * @export
 * @interface PaymentStatusApiInterface
 */
export interface PaymentStatusApiInterface {
    /**
     * Creates request options for retrievePaymentStatus without sending the request
     * @param {string} statusCheckKey Represents order identifier to look up the payment order in POP.
     * @param {string} currency Represents reservation currency.
     * @param {string} language Represents reservation language.
     * @param {NEXUZR006PaymentPaymentStatusRequest} nEXUZR006PaymentPaymentStatusRequest 
     * @throws {RequiredError}
     * @memberof PaymentStatusApiInterface
     */
    retrievePaymentStatusRequestOpts(requestParameters: RetrievePaymentStatusRequest): Promise<runtime.RequestOpts>;

    /**
     * This endpoint is responsible for retrieving the payment status from POP and updating other systems based on the status, and returning a consolidated status to the UI. 
     * @summary Retrieve payment status
     * @param {string} statusCheckKey Represents order identifier to look up the payment order in POP.
     * @param {string} currency Represents reservation currency.
     * @param {string} language Represents reservation language.
     * @param {NEXUZR006PaymentPaymentStatusRequest} nEXUZR006PaymentPaymentStatusRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentStatusApiInterface
     */
    retrievePaymentStatusRaw(requestParameters: RetrievePaymentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR006PaymentPaymentStatusResponse>>;

    /**
     * This endpoint is responsible for retrieving the payment status from POP and updating other systems based on the status, and returning a consolidated status to the UI. 
     * Retrieve payment status
     */
    retrievePaymentStatus(requestParameters: RetrievePaymentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR006PaymentPaymentStatusResponse>;

}

/**
 * 
 */
export class PaymentStatusApi extends runtime.BaseAPI implements PaymentStatusApiInterface {

    /**
     * Creates request options for retrievePaymentStatus without sending the request
     */
    async retrievePaymentStatusRequestOpts(requestParameters: RetrievePaymentStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['statusCheckKey'] == null) {
            throw new runtime.RequiredError(
                'statusCheckKey',
                'Required parameter "statusCheckKey" was null or undefined when calling retrievePaymentStatus().'
            );
        }

        if (requestParameters['currency'] == null) {
            throw new runtime.RequiredError(
                'currency',
                'Required parameter "currency" was null or undefined when calling retrievePaymentStatus().'
            );
        }

        if (requestParameters['language'] == null) {
            throw new runtime.RequiredError(
                'language',
                'Required parameter "language" was null or undefined when calling retrievePaymentStatus().'
            );
        }

        if (requestParameters['nEXUZR006PaymentPaymentStatusRequest'] == null) {
            throw new runtime.RequiredError(
                'nEXUZR006PaymentPaymentStatusRequest',
                'Required parameter "nEXUZR006PaymentPaymentStatusRequest" was null or undefined when calling retrievePaymentStatus().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['language'] != null) {
            queryParameters['language'] = requestParameters['language'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/payment/{statusCheckKey}/status`;
        urlPath = urlPath.replace('{statusCheckKey}', encodeURIComponent(String(requestParameters['statusCheckKey'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NEXUZR006PaymentPaymentStatusRequestToJSON(requestParameters['nEXUZR006PaymentPaymentStatusRequest']),
        };
    }

    /**
     * This endpoint is responsible for retrieving the payment status from POP and updating other systems based on the status, and returning a consolidated status to the UI. 
     * Retrieve payment status
     */
    async retrievePaymentStatusRaw(requestParameters: RetrievePaymentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR006PaymentPaymentStatusResponse>> {
        const requestOptions = await this.retrievePaymentStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NEXUZR006PaymentPaymentStatusResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint is responsible for retrieving the payment status from POP and updating other systems based on the status, and returning a consolidated status to the UI. 
     * Retrieve payment status
     */
    async retrievePaymentStatus(requestParameters: RetrievePaymentStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR006PaymentPaymentStatusResponse> {
        const response = await this.retrievePaymentStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
