/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type NEXUZR006PaymentErrorResponse,
    NEXUZR006PaymentErrorResponseFromJSON,
    NEXUZR006PaymentErrorResponseToJSON,
} from '../models/NEXUZR006PaymentErrorResponse';
import {
    type NEXUZR006PaymentInitializePaymentRequest,
    NEXUZR006PaymentInitializePaymentRequestFromJSON,
    NEXUZR006PaymentInitializePaymentRequestToJSON,
} from '../models/NEXUZR006PaymentInitializePaymentRequest';
import {
    type NEXUZR006PaymentInitializePaymentResponse,
    NEXUZR006PaymentInitializePaymentResponseFromJSON,
    NEXUZR006PaymentInitializePaymentResponseToJSON,
} from '../models/NEXUZR006PaymentInitializePaymentResponse';

export interface PaymentInitializePostRequest {
    currency: string;
    language: string;
    nEXUZR006PaymentInitializePaymentRequest: NEXUZR006PaymentInitializePaymentRequest;
}

/**
 * PaymentApi - interface
 * 
 * @export
 * @interface PaymentApiInterface
 */
export interface PaymentApiInterface {
    /**
     * Creates request options for paymentInitializePost without sending the request
     * @param {string} currency Represents the reservation currency.
     * @param {string} language Represents the reservation language.
     * @param {NEXUZR006PaymentInitializePaymentRequest} nEXUZR006PaymentInitializePaymentRequest 
     * @throws {RequiredError}
     * @memberof PaymentApiInterface
     */
    paymentInitializePostRequestOpts(requestParameters: PaymentInitializePostRequest): Promise<runtime.RequestOpts>;

    /**
     * This endpoint is responsible for generating the Payment Reference ID, creating the POP Order ID, and obtaining the payment redirection URL from POP.
     * @summary Initiate payment session
     * @param {string} currency Represents the reservation currency.
     * @param {string} language Represents the reservation language.
     * @param {NEXUZR006PaymentInitializePaymentRequest} nEXUZR006PaymentInitializePaymentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentApiInterface
     */
    paymentInitializePostRaw(requestParameters: PaymentInitializePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR006PaymentInitializePaymentResponse>>;

    /**
     * This endpoint is responsible for generating the Payment Reference ID, creating the POP Order ID, and obtaining the payment redirection URL from POP.
     * Initiate payment session
     */
    paymentInitializePost(requestParameters: PaymentInitializePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR006PaymentInitializePaymentResponse>;

}

/**
 * 
 */
export class PaymentApi extends runtime.BaseAPI implements PaymentApiInterface {

    /**
     * Creates request options for paymentInitializePost without sending the request
     */
    async paymentInitializePostRequestOpts(requestParameters: PaymentInitializePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['currency'] == null) {
            throw new runtime.RequiredError(
                'currency',
                'Required parameter "currency" was null or undefined when calling paymentInitializePost().'
            );
        }

        if (requestParameters['language'] == null) {
            throw new runtime.RequiredError(
                'language',
                'Required parameter "language" was null or undefined when calling paymentInitializePost().'
            );
        }

        if (requestParameters['nEXUZR006PaymentInitializePaymentRequest'] == null) {
            throw new runtime.RequiredError(
                'nEXUZR006PaymentInitializePaymentRequest',
                'Required parameter "nEXUZR006PaymentInitializePaymentRequest" was null or undefined when calling paymentInitializePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['language'] != null) {
            queryParameters['language'] = requestParameters['language'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/payment/initialize`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NEXUZR006PaymentInitializePaymentRequestToJSON(requestParameters['nEXUZR006PaymentInitializePaymentRequest']),
        };
    }

    /**
     * This endpoint is responsible for generating the Payment Reference ID, creating the POP Order ID, and obtaining the payment redirection URL from POP.
     * Initiate payment session
     */
    async paymentInitializePostRaw(requestParameters: PaymentInitializePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR006PaymentInitializePaymentResponse>> {
        const requestOptions = await this.paymentInitializePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NEXUZR006PaymentInitializePaymentResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint is responsible for generating the Payment Reference ID, creating the POP Order ID, and obtaining the payment redirection URL from POP.
     * Initiate payment session
     */
    async paymentInitializePost(requestParameters: PaymentInitializePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR006PaymentInitializePaymentResponse> {
        const response = await this.paymentInitializePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
