/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type NEXUZR002SearchAirportRouteResponse,
    NEXUZR002SearchAirportRouteResponseFromJSON,
    NEXUZR002SearchAirportRouteResponseToJSON,
} from '../models/NEXUZR002SearchAirportRouteResponse';
import {
    type NEXUZR002SearchCalendarFaresResponse,
    NEXUZR002SearchCalendarFaresResponseFromJSON,
    NEXUZR002SearchCalendarFaresResponseToJSON,
} from '../models/NEXUZR002SearchCalendarFaresResponse';
import {
    type NEXUZR002SearchErrorResponse,
    NEXUZR002SearchErrorResponseFromJSON,
    NEXUZR002SearchErrorResponseToJSON,
} from '../models/NEXUZR002SearchErrorResponse';
import {
    type NEXUZR003FlightsErrorResponse,
    NEXUZR003FlightsErrorResponseFromJSON,
    NEXUZR003FlightsErrorResponseToJSON,
} from '../models/NEXUZR003FlightsErrorResponse';
import {
    type NEXUZR003FlightsFlightSearchResponse,
    NEXUZR003FlightsFlightSearchResponseFromJSON,
    NEXUZR003FlightsFlightSearchResponseToJSON,
} from '../models/NEXUZR003FlightsFlightSearchResponse';

export interface SearchCalendarFaresGetRequest {
    routes: string;
    departureDateFrom: string;
    language: string;
    currency: string;
    promotionCode?: string;
    departureDateTo?: string;
}

export interface SearchFlightsRequest {
    routes: string;
    departureDateFrom: string;
    adult: string;
    language: string;
    currency: string;
    departureDateTo?: string;
    childA?: string;
    childB?: string;
    childC?: string;
    infant?: string;
    promotionCode?: string;
}

export interface SearchRoutesGetRequest {
    language: string;
}

/**
 * SearchApi - interface
 * 
 * @export
 * @interface SearchApiInterface
 */
export interface SearchApiInterface {
    /**
     * Creates request options for searchCalendarFaresGet without sending the request
     * @param {string} routes Comma-separated airport codes representing the route. - One-way / Round-trip: &#x60;\&quot;NRT,BKK\&quot;&#x60; (origin,destination) - Connecting: &#x60;\&quot;BKK,NRT,SIN\&quot;&#x60; (origin,stopover,destination) 
     * @param {string} departureDateFrom Outbound departure date in &#x60;yyyy-MM-dd&#x60; format
     * @param {string} language Language code
     * @param {string} currency Currency code
     * @param {string} [promotionCode] Promotional code
     * @param {string} [departureDateTo] Inbound date in &#x60;yyyy-MM-dd&#x60; format for round-trips 
     * @throws {RequiredError}
     * @memberof SearchApiInterface
     */
    searchCalendarFaresGetRequestOpts(requestParameters: SearchCalendarFaresGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieves the lowest fare details for each date and cabin within a specified calendar date range.
     * @summary Retrieve calendar fare date range
     * @param {string} routes Comma-separated airport codes representing the route. - One-way / Round-trip: &#x60;\&quot;NRT,BKK\&quot;&#x60; (origin,destination) - Connecting: &#x60;\&quot;BKK,NRT,SIN\&quot;&#x60; (origin,stopover,destination) 
     * @param {string} departureDateFrom Outbound departure date in &#x60;yyyy-MM-dd&#x60; format
     * @param {string} language Language code
     * @param {string} currency Currency code
     * @param {string} [promotionCode] Promotional code
     * @param {string} [departureDateTo] Inbound date in &#x60;yyyy-MM-dd&#x60; format for round-trips 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchApiInterface
     */
    searchCalendarFaresGetRaw(requestParameters: SearchCalendarFaresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR002SearchCalendarFaresResponse>>;

    /**
     * Retrieves the lowest fare details for each date and cabin within a specified calendar date range.
     * Retrieve calendar fare date range
     */
    searchCalendarFaresGet(requestParameters: SearchCalendarFaresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR002SearchCalendarFaresResponse>;

    /**
     * Creates request options for searchFlights without sending the request
     * @param {string} routes Comma-separated airport codes representing the route.
     * @param {string} departureDateFrom Outbound departure date in &#x60;yyyy-MM-dd&#x60; format.
     * @param {string} adult Number of adult passengers.
     * @param {string} language Language code for response content.
     * @param {string} currency Currency code for fare amounts.
     * @param {string} [departureDateTo] Return departure date in &#x60;yyyy-MM-dd&#x60; format for round-trips.
     * @param {string} [childA] Number of Child A passengers.
     * @param {string} [childB] Number of Child B passengers.
     * @param {string} [childC] Number of Child C passengers.
     * @param {string} [infant] Number of infant passengers.
     * @param {string} [promotionCode] Promotional code to apply discounts.
     * @throws {RequiredError}
     * @memberof SearchApiInterface
     */
    searchFlightsRequestOpts(requestParameters: SearchFlightsRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieves available flights and fare quotes.
     * @summary Search available flights and retrieve fare quotes
     * @param {string} routes Comma-separated airport codes representing the route.
     * @param {string} departureDateFrom Outbound departure date in &#x60;yyyy-MM-dd&#x60; format.
     * @param {string} adult Number of adult passengers.
     * @param {string} language Language code for response content.
     * @param {string} currency Currency code for fare amounts.
     * @param {string} [departureDateTo] Return departure date in &#x60;yyyy-MM-dd&#x60; format for round-trips.
     * @param {string} [childA] Number of Child A passengers.
     * @param {string} [childB] Number of Child B passengers.
     * @param {string} [childC] Number of Child C passengers.
     * @param {string} [infant] Number of infant passengers.
     * @param {string} [promotionCode] Promotional code to apply discounts.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchApiInterface
     */
    searchFlightsRaw(requestParameters: SearchFlightsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR003FlightsFlightSearchResponse>>;

    /**
     * Retrieves available flights and fare quotes.
     * Search available flights and retrieve fare quotes
     */
    searchFlights(requestParameters: SearchFlightsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR003FlightsFlightSearchResponse>;

    /**
     * Creates request options for searchRoutesGet without sending the request
     * @param {string} language language code is required.
     * @throws {RequiredError}
     * @memberof SearchApiInterface
     */
    searchRoutesGetRequestOpts(requestParameters: SearchRoutesGetRequest): Promise<runtime.RequestOpts>;

    /**
     * To retrieve travel routes from the Radixx System and return valid origin and destination airport codes as the response.
     * @summary Retrieve airport route
     * @param {string} language language code is required.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchApiInterface
     */
    searchRoutesGetRaw(requestParameters: SearchRoutesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR002SearchAirportRouteResponse>>;

    /**
     * To retrieve travel routes from the Radixx System and return valid origin and destination airport codes as the response.
     * Retrieve airport route
     */
    searchRoutesGet(requestParameters: SearchRoutesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR002SearchAirportRouteResponse>;

}

/**
 * 
 */
export class SearchApi extends runtime.BaseAPI implements SearchApiInterface {

    /**
     * Creates request options for searchCalendarFaresGet without sending the request
     */
    async searchCalendarFaresGetRequestOpts(requestParameters: SearchCalendarFaresGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['routes'] == null) {
            throw new runtime.RequiredError(
                'routes',
                'Required parameter "routes" was null or undefined when calling searchCalendarFaresGet().'
            );
        }

        if (requestParameters['departureDateFrom'] == null) {
            throw new runtime.RequiredError(
                'departureDateFrom',
                'Required parameter "departureDateFrom" was null or undefined when calling searchCalendarFaresGet().'
            );
        }

        if (requestParameters['language'] == null) {
            throw new runtime.RequiredError(
                'language',
                'Required parameter "language" was null or undefined when calling searchCalendarFaresGet().'
            );
        }

        if (requestParameters['currency'] == null) {
            throw new runtime.RequiredError(
                'currency',
                'Required parameter "currency" was null or undefined when calling searchCalendarFaresGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['promotionCode'] != null) {
            queryParameters['promotionCode'] = requestParameters['promotionCode'];
        }

        if (requestParameters['routes'] != null) {
            queryParameters['routes'] = requestParameters['routes'];
        }

        if (requestParameters['departureDateFrom'] != null) {
            queryParameters['departureDateFrom'] = requestParameters['departureDateFrom'];
        }

        if (requestParameters['departureDateTo'] != null) {
            queryParameters['departureDateTo'] = requestParameters['departureDateTo'];
        }

        if (requestParameters['language'] != null) {
            queryParameters['language'] = requestParameters['language'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/search/calendar-fares`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves the lowest fare details for each date and cabin within a specified calendar date range.
     * Retrieve calendar fare date range
     */
    async searchCalendarFaresGetRaw(requestParameters: SearchCalendarFaresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR002SearchCalendarFaresResponse>> {
        const requestOptions = await this.searchCalendarFaresGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NEXUZR002SearchCalendarFaresResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the lowest fare details for each date and cabin within a specified calendar date range.
     * Retrieve calendar fare date range
     */
    async searchCalendarFaresGet(requestParameters: SearchCalendarFaresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR002SearchCalendarFaresResponse> {
        const response = await this.searchCalendarFaresGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchFlights without sending the request
     */
    async searchFlightsRequestOpts(requestParameters: SearchFlightsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['routes'] == null) {
            throw new runtime.RequiredError(
                'routes',
                'Required parameter "routes" was null or undefined when calling searchFlights().'
            );
        }

        if (requestParameters['departureDateFrom'] == null) {
            throw new runtime.RequiredError(
                'departureDateFrom',
                'Required parameter "departureDateFrom" was null or undefined when calling searchFlights().'
            );
        }

        if (requestParameters['adult'] == null) {
            throw new runtime.RequiredError(
                'adult',
                'Required parameter "adult" was null or undefined when calling searchFlights().'
            );
        }

        if (requestParameters['language'] == null) {
            throw new runtime.RequiredError(
                'language',
                'Required parameter "language" was null or undefined when calling searchFlights().'
            );
        }

        if (requestParameters['currency'] == null) {
            throw new runtime.RequiredError(
                'currency',
                'Required parameter "currency" was null or undefined when calling searchFlights().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['routes'] != null) {
            queryParameters['routes'] = requestParameters['routes'];
        }

        if (requestParameters['departureDateFrom'] != null) {
            queryParameters['departureDateFrom'] = requestParameters['departureDateFrom'];
        }

        if (requestParameters['departureDateTo'] != null) {
            queryParameters['departureDateTo'] = requestParameters['departureDateTo'];
        }

        if (requestParameters['adult'] != null) {
            queryParameters['adult'] = requestParameters['adult'];
        }

        if (requestParameters['childA'] != null) {
            queryParameters['childA'] = requestParameters['childA'];
        }

        if (requestParameters['childB'] != null) {
            queryParameters['childB'] = requestParameters['childB'];
        }

        if (requestParameters['childC'] != null) {
            queryParameters['childC'] = requestParameters['childC'];
        }

        if (requestParameters['infant'] != null) {
            queryParameters['infant'] = requestParameters['infant'];
        }

        if (requestParameters['language'] != null) {
            queryParameters['language'] = requestParameters['language'];
        }

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['promotionCode'] != null) {
            queryParameters['promotionCode'] = requestParameters['promotionCode'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/search/flights`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves available flights and fare quotes.
     * Search available flights and retrieve fare quotes
     */
    async searchFlightsRaw(requestParameters: SearchFlightsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR003FlightsFlightSearchResponse>> {
        const requestOptions = await this.searchFlightsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NEXUZR003FlightsFlightSearchResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves available flights and fare quotes.
     * Search available flights and retrieve fare quotes
     */
    async searchFlights(requestParameters: SearchFlightsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR003FlightsFlightSearchResponse> {
        const response = await this.searchFlightsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchRoutesGet without sending the request
     */
    async searchRoutesGetRequestOpts(requestParameters: SearchRoutesGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['language'] == null) {
            throw new runtime.RequiredError(
                'language',
                'Required parameter "language" was null or undefined when calling searchRoutesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['language'] != null) {
            queryParameters['language'] = requestParameters['language'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/search/routes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * To retrieve travel routes from the Radixx System and return valid origin and destination airport codes as the response.
     * Retrieve airport route
     */
    async searchRoutesGetRaw(requestParameters: SearchRoutesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR002SearchAirportRouteResponse>> {
        const requestOptions = await this.searchRoutesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NEXUZR002SearchAirportRouteResponseFromJSON(jsonValue));
    }

    /**
     * To retrieve travel routes from the Radixx System and return valid origin and destination airport codes as the response.
     * Retrieve airport route
     */
    async searchRoutesGet(requestParameters: SearchRoutesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR002SearchAirportRouteResponse> {
        const response = await this.searchRoutesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
