/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type NEXUZR005APIsErrorResponse,
    NEXUZR005APIsErrorResponseFromJSON,
    NEXUZR005APIsErrorResponseToJSON,
} from '../models/NEXUZR005APIsErrorResponse';
import {
    type NEXUZR005APIsSummaryRequest,
    NEXUZR005APIsSummaryRequestFromJSON,
    NEXUZR005APIsSummaryRequestToJSON,
} from '../models/NEXUZR005APIsSummaryRequest';
import {
    type NEXUZR005APIsSummaryResponse,
    NEXUZR005APIsSummaryResponseFromJSON,
    NEXUZR005APIsSummaryResponseToJSON,
} from '../models/NEXUZR005APIsSummaryResponse';

export interface SummaryPNRRequest {
    currency: string;
    language: string;
    nEXUZR005APIsSummaryRequest: NEXUZR005APIsSummaryRequest;
}

/**
 * SummaryPNRApi - interface
 * 
 * @export
 * @interface SummaryPNRApiInterface
 */
export interface SummaryPNRApiInterface {
    /**
     * Creates request options for summaryPNR without sending the request
     * @param {string} currency currency code.
     * @param {string} language language code.
     * @param {NEXUZR005APIsSummaryRequest} nEXUZR005APIsSummaryRequest Summary PNR preparation request containing flight and passenger details.
     * @throws {RequiredError}
     * @memberof SummaryPNRApiInterface
     */
    summaryPNRRequestOpts(requestParameters: SummaryPNRRequest): Promise<runtime.RequestOpts>;

    /**
     * Prepares a summary PNR by validating inputs, retrieving fare quotes, processing ancillary services, bundles and seat selections, and generating an encrypted Arkose token. 
     * @summary Summary PNR
     * @param {string} currency currency code.
     * @param {string} language language code.
     * @param {NEXUZR005APIsSummaryRequest} nEXUZR005APIsSummaryRequest Summary PNR preparation request containing flight and passenger details.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SummaryPNRApiInterface
     */
    summaryPNRRaw(requestParameters: SummaryPNRRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR005APIsSummaryResponse>>;

    /**
     * Prepares a summary PNR by validating inputs, retrieving fare quotes, processing ancillary services, bundles and seat selections, and generating an encrypted Arkose token. 
     * Summary PNR
     */
    summaryPNR(requestParameters: SummaryPNRRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR005APIsSummaryResponse>;

}

/**
 * 
 */
export class SummaryPNRApi extends runtime.BaseAPI implements SummaryPNRApiInterface {

    /**
     * Creates request options for summaryPNR without sending the request
     */
    async summaryPNRRequestOpts(requestParameters: SummaryPNRRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['currency'] == null) {
            throw new runtime.RequiredError(
                'currency',
                'Required parameter "currency" was null or undefined when calling summaryPNR().'
            );
        }

        if (requestParameters['language'] == null) {
            throw new runtime.RequiredError(
                'language',
                'Required parameter "language" was null or undefined when calling summaryPNR().'
            );
        }

        if (requestParameters['nEXUZR005APIsSummaryRequest'] == null) {
            throw new runtime.RequiredError(
                'nEXUZR005APIsSummaryRequest',
                'Required parameter "nEXUZR005APIsSummaryRequest" was null or undefined when calling summaryPNR().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['language'] != null) {
            queryParameters['language'] = requestParameters['language'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/orders/prepare`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NEXUZR005APIsSummaryRequestToJSON(requestParameters['nEXUZR005APIsSummaryRequest']),
        };
    }

    /**
     * Prepares a summary PNR by validating inputs, retrieving fare quotes, processing ancillary services, bundles and seat selections, and generating an encrypted Arkose token. 
     * Summary PNR
     */
    async summaryPNRRaw(requestParameters: SummaryPNRRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR005APIsSummaryResponse>> {
        const requestOptions = await this.summaryPNRRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NEXUZR005APIsSummaryResponseFromJSON(jsonValue));
    }

    /**
     * Prepares a summary PNR by validating inputs, retrieving fare quotes, processing ancillary services, bundles and seat selections, and generating an encrypted Arkose token. 
     * Summary PNR
     */
    async summaryPNR(requestParameters: SummaryPNRRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR005APIsSummaryResponse> {
        const response = await this.summaryPNRRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
