/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Flight details including departure date, cabin class, logical flight ID, fare basis code, and fare class.
 * @export
 * @interface NEXUZR004OffersFlight
 */
export interface NEXUZR004OffersFlight {
    /**
     * Departure date in `2026-06-28T23:10:00` format.
     * @type {Date}
     * @memberof NEXUZR004OffersFlight
     */
    departureDate: Date;
    /**
     * Cabin class for the flight. Valid values are "STANDARD" and "ZIPFULLFLAT".
     * @type {NEXUZR004OffersFlightCabinEnum}
     * @memberof NEXUZR004OffersFlight
     */
    cabin: NEXUZR004OffersFlightCabinEnum;
    /**
     * Logical Flight ID (LFID) representing the flight segment.
     * @type {number}
     * @memberof NEXUZR004OffersFlight
     */
    lfid: number;
    /**
     * Fare basis code for the flight.
     * @type {string}
     * @memberof NEXUZR004OffersFlight
     */
    fareBasisCode?: string;
    /**
     * Fare class for the flight.
     * @type {string}
     * @memberof NEXUZR004OffersFlight
     */
    fareClass?: string;
}


/**
 * @export
 */
export const NEXUZR004OffersFlightCabinEnum = {
    standard: 'STANDARD',
    zipfullflat: 'ZIPFULLFLAT'
} as const;
export type NEXUZR004OffersFlightCabinEnum = typeof NEXUZR004OffersFlightCabinEnum[keyof typeof NEXUZR004OffersFlightCabinEnum];


/**
 * Check if a given object implements the NEXUZR004OffersFlight interface.
 */
export function instanceOfNEXUZR004OffersFlight(value: object): value is NEXUZR004OffersFlight {
    if (!('departureDate' in value) || value['departureDate'] === undefined) return false;
    if (!('cabin' in value) || value['cabin'] === undefined) return false;
    if (!('lfid' in value) || value['lfid'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersFlightFromJSON(json: any): NEXUZR004OffersFlight {
    return NEXUZR004OffersFlightFromJSONTyped(json, false);
}

export function NEXUZR004OffersFlightFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersFlight {
    if (json == null) {
        return json;
    }
    return {
        
        'departureDate': (new Date(json['departureDate'])),
        'cabin': json['cabin'],
        'lfid': json['lfid'],
        'fareBasisCode': json['fareBasisCode'] == null ? undefined : json['fareBasisCode'],
        'fareClass': json['fareClass'] == null ? undefined : json['fareClass'],
    };
}

export function NEXUZR004OffersFlightToJSON(json: any): NEXUZR004OffersFlight {
    return NEXUZR004OffersFlightToJSONTyped(json, false);
}

export function NEXUZR004OffersFlightToJSONTyped(value?: NEXUZR004OffersFlight | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'departureDate': value['departureDate'].toISOString().substring(0,10),
        'cabin': value['cabin'],
        'lfid': value['lfid'],
        'fareBasisCode': value['fareBasisCode'],
        'fareClass': value['fareClass'],
    };
}

