/* tslint:disable */
/* eslint-disable */
// @ts-nocheck -- auto-generated file; TS7053 from the "_class"/"class" reserved-word rename in instanceOf guard
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR007OrderManagementFare
 */
export interface NEXUZR007OrderManagementFare {
    /**
     * Fare Class of the cabin
     * @type {string}
     * @memberof NEXUZR007OrderManagementFare
     */
    _class: string;
    /**
     * Fare Basis Code of the cabin
     * @type {string}
     * @memberof NEXUZR007OrderManagementFare
     */
    basis: string;
}

/**
 * Check if a given object implements the NEXUZR007OrderManagementFare interface.
 */
export function instanceOfNEXUZR007OrderManagementFare(value: object): value is NEXUZR007OrderManagementFare {
    if ((!('_class' in value) && !('class' in value)) || (value['_class'] === undefined && value['class'] === undefined)) return false;
    if (!('basis' in value) || value['basis'] === undefined) return false;
    return true;
}

export function NEXUZR007OrderManagementFareFromJSON(json: any): NEXUZR007OrderManagementFare {
    return NEXUZR007OrderManagementFareFromJSONTyped(json, false);
}

export function NEXUZR007OrderManagementFareFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR007OrderManagementFare {
    if (json == null) {
        return json;
    }
    return {
        
        '_class': json['class'],
        'basis': json['basis'],
    };
}

export function NEXUZR007OrderManagementFareToJSON(json: any): NEXUZR007OrderManagementFare {
    return NEXUZR007OrderManagementFareToJSONTyped(json, false);
}

export function NEXUZR007OrderManagementFareToJSONTyped(value?: NEXUZR007OrderManagementFare | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'class': value['_class'],
        'basis': value['basis'],
    };
}

