/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR007OrderManagementAgent
 */
export interface NEXUZR007OrderManagementAgent {
    /**
     * Agent Code.
     * @type {string}
     * @memberof NEXUZR007OrderManagementAgent
     */
    code: string;
    /**
     * Name of the Agent.
     * @type {string}
     * @memberof NEXUZR007OrderManagementAgent
     */
    name: string;
}

/**
 * Check if a given object implements the NEXUZR007OrderManagementAgent interface.
 */
export function instanceOfNEXUZR007OrderManagementAgent(value: object): value is NEXUZR007OrderManagementAgent {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function NEXUZR007OrderManagementAgentFromJSON(json: any): NEXUZR007OrderManagementAgent {
    return NEXUZR007OrderManagementAgentFromJSONTyped(json, false);
}

export function NEXUZR007OrderManagementAgentFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR007OrderManagementAgent {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'name': json['name'],
    };
}

export function NEXUZR007OrderManagementAgentToJSON(json: any): NEXUZR007OrderManagementAgent {
    return NEXUZR007OrderManagementAgentToJSONTyped(json, false);
}

export function NEXUZR007OrderManagementAgentToJSONTyped(value?: NEXUZR007OrderManagementAgent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
    };
}

