/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR007OrderManagementFare } from './NEXUZR007OrderManagementFare';
import {
    NEXUZR007OrderManagementFareFromJSON,
    NEXUZR007OrderManagementFareFromJSONTyped,
    NEXUZR007OrderManagementFareToJSON,
    NEXUZR007OrderManagementFareToJSONTyped,
} from './NEXUZR007OrderManagementFare';
import type { NEXUZR007OrderManagementDateParts } from './NEXUZR007OrderManagementDateParts';
import {
    NEXUZR007OrderManagementDatePartsFromJSON,
    NEXUZR007OrderManagementDatePartsFromJSONTyped,
    NEXUZR007OrderManagementDatePartsToJSON,
    NEXUZR007OrderManagementDatePartsToJSONTyped,
} from './NEXUZR007OrderManagementDateParts';
import type { NEXUZR007OrderManagementAmount } from './NEXUZR007OrderManagementAmount';
import {
    NEXUZR007OrderManagementAmountFromJSON,
    NEXUZR007OrderManagementAmountFromJSONTyped,
    NEXUZR007OrderManagementAmountToJSON,
    NEXUZR007OrderManagementAmountToJSONTyped,
} from './NEXUZR007OrderManagementAmount';

/**
 * 
 * @export
 * @interface NEXUZR007OrderManagementFlight
 */
export interface NEXUZR007OrderManagementFlight {
    /**
     * Carrier Code of the Airline.
     * @type {string}
     * @memberof NEXUZR007OrderManagementFlight
     */
    carrierCode: string;
    /**
     * Operating FlightId.
     * @type {string}
     * @memberof NEXUZR007OrderManagementFlight
     */
    flightCode: string;
    /**
     * Stop Over Code of the flight.
     * @type {number}
     * @memberof NEXUZR007OrderManagementFlight
     */
    stopOverCode: number;
    /**
     * Departure airport code.
     * @type {string}
     * @memberof NEXUZR007OrderManagementFlight
     */
    departureAirport: string;
    /**
     * Arrival airport code.
     * @type {string}
     * @memberof NEXUZR007OrderManagementFlight
     */
    arrivalAirport: string;
    /**
     * 
     * @type {NEXUZR007OrderManagementDateParts}
     * @memberof NEXUZR007OrderManagementFlight
     */
    departureDate: NEXUZR007OrderManagementDateParts;
    /**
     * 
     * @type {NEXUZR007OrderManagementFare}
     * @memberof NEXUZR007OrderManagementFlight
     */
    fare: NEXUZR007OrderManagementFare;
    /**
     * 
     * @type {NEXUZR007OrderManagementAmount}
     * @memberof NEXUZR007OrderManagementFlight
     */
    amount: NEXUZR007OrderManagementAmount;
}

/**
 * Check if a given object implements the NEXUZR007OrderManagementFlight interface.
 */
export function instanceOfNEXUZR007OrderManagementFlight(value: object): value is NEXUZR007OrderManagementFlight {
    if (!('carrierCode' in value) || value['carrierCode'] === undefined) return false;
    if (!('flightCode' in value) || value['flightCode'] === undefined) return false;
    if (!('stopOverCode' in value) || value['stopOverCode'] === undefined) return false;
    if (!('departureAirport' in value) || value['departureAirport'] === undefined) return false;
    if (!('arrivalAirport' in value) || value['arrivalAirport'] === undefined) return false;
    if (!('departureDate' in value) || value['departureDate'] === undefined) return false;
    if (!('fare' in value) || value['fare'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function NEXUZR007OrderManagementFlightFromJSON(json: any): NEXUZR007OrderManagementFlight {
    return NEXUZR007OrderManagementFlightFromJSONTyped(json, false);
}

export function NEXUZR007OrderManagementFlightFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR007OrderManagementFlight {
    if (json == null) {
        return json;
    }
    return {
        
        'carrierCode': json['carrierCode'],
        'flightCode': json['flightCode'],
        'stopOverCode': json['stopOverCode'],
        'departureAirport': json['departureAirport'],
        'arrivalAirport': json['arrivalAirport'],
        'departureDate': NEXUZR007OrderManagementDatePartsFromJSON(json['departureDate']),
        'fare': NEXUZR007OrderManagementFareFromJSON(json['fare']),
        'amount': NEXUZR007OrderManagementAmountFromJSON(json['amount']),
    };
}

export function NEXUZR007OrderManagementFlightToJSON(json: any): NEXUZR007OrderManagementFlight {
    return NEXUZR007OrderManagementFlightToJSONTyped(json, false);
}

export function NEXUZR007OrderManagementFlightToJSONTyped(value?: NEXUZR007OrderManagementFlight | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'carrierCode': value['carrierCode'],
        'flightCode': value['flightCode'],
        'stopOverCode': value['stopOverCode'],
        'departureAirport': value['departureAirport'],
        'arrivalAirport': value['arrivalAirport'],
        'departureDate': NEXUZR007OrderManagementDatePartsToJSON(value['departureDate']),
        'fare': NEXUZR007OrderManagementFareToJSON(value['fare']),
        'amount': NEXUZR007OrderManagementAmountToJSON(value['amount']),
    };
}

