/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR003FlightsPassengerWiseFare } from './NEXUZR003FlightsPassengerWiseFare';
import {
    NEXUZR003FlightsPassengerWiseFareFromJSON,
    NEXUZR003FlightsPassengerWiseFareFromJSONTyped,
    NEXUZR003FlightsPassengerWiseFareToJSON,
    NEXUZR003FlightsPassengerWiseFareToJSONTyped,
} from './NEXUZR003FlightsPassengerWiseFare';
import type { NEXUZR003FlightsTaxBreakDown } from './NEXUZR003FlightsTaxBreakDown';
import {
    NEXUZR003FlightsTaxBreakDownFromJSON,
    NEXUZR003FlightsTaxBreakDownFromJSONTyped,
    NEXUZR003FlightsTaxBreakDownToJSON,
    NEXUZR003FlightsTaxBreakDownToJSONTyped,
} from './NEXUZR003FlightsTaxBreakDown';

/**
 * Aggregated fare summary for a specific cabin, covering all requested passenger types.
 * 
 * @export
 * @interface NEXUZR003FlightsBoundSummary
 */
export interface NEXUZR003FlightsBoundSummary {
    /**
     * Total fare amount for all passengers in this cabin.
     * @type {number}
     * @memberof NEXUZR003FlightsBoundSummary
     */
    totalFlightAmount: number;
    /**
     * Total promotional discount amount applied to this cabin.
     * @type {number}
     * @memberof NEXUZR003FlightsBoundSummary
     */
    promotionalAmount?: number | null;
    /**
     * Fare breakdown per passenger type.
     * @type {Array<NEXUZR003FlightsPassengerWiseFare>}
     * @memberof NEXUZR003FlightsBoundSummary
     */
    passengerWiseFares: Array<NEXUZR003FlightsPassengerWiseFare>;
    /**
     * Total tax amount for all passengers in this cabin.
     * @type {number}
     * @memberof NEXUZR003FlightsBoundSummary
     */
    totalTaxAmount: number;
    /**
     * Tax breakdown by tax code across all passenger types.
     * @type {Array<NEXUZR003FlightsTaxBreakDown>}
     * @memberof NEXUZR003FlightsBoundSummary
     */
    taxBreakDown: Array<NEXUZR003FlightsTaxBreakDown>;
}

/**
 * Check if a given object implements the NEXUZR003FlightsBoundSummary interface.
 */
export function instanceOfNEXUZR003FlightsBoundSummary(value: object): value is NEXUZR003FlightsBoundSummary {
    if (!('totalFlightAmount' in value) || value['totalFlightAmount'] === undefined) return false;
    if (!('passengerWiseFares' in value) || value['passengerWiseFares'] === undefined) return false;
    if (!('totalTaxAmount' in value) || value['totalTaxAmount'] === undefined) return false;
    if (!('taxBreakDown' in value) || value['taxBreakDown'] === undefined) return false;
    return true;
}

export function NEXUZR003FlightsBoundSummaryFromJSON(json: any): NEXUZR003FlightsBoundSummary {
    return NEXUZR003FlightsBoundSummaryFromJSONTyped(json, false);
}

export function NEXUZR003FlightsBoundSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR003FlightsBoundSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'totalFlightAmount': json['totalFlightAmount'],
        'promotionalAmount': json['promotionalAmount'] == null ? undefined : json['promotionalAmount'],
        'passengerWiseFares': ((json['passengerWiseFares'] as Array<any>).map(NEXUZR003FlightsPassengerWiseFareFromJSON)),
        'totalTaxAmount': json['totalTaxAmount'],
        'taxBreakDown': ((json['taxBreakDown'] as Array<any>).map(NEXUZR003FlightsTaxBreakDownFromJSON)),
    };
}

export function NEXUZR003FlightsBoundSummaryToJSON(json: any): NEXUZR003FlightsBoundSummary {
    return NEXUZR003FlightsBoundSummaryToJSONTyped(json, false);
}

export function NEXUZR003FlightsBoundSummaryToJSONTyped(value?: NEXUZR003FlightsBoundSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalFlightAmount': value['totalFlightAmount'],
        'promotionalAmount': value['promotionalAmount'],
        'passengerWiseFares': ((value['passengerWiseFares'] as Array<any>).map(NEXUZR003FlightsPassengerWiseFareToJSON)),
        'totalTaxAmount': value['totalTaxAmount'],
        'taxBreakDown': ((value['taxBreakDown'] as Array<any>).map(NEXUZR003FlightsTaxBreakDownToJSON)),
    };
}

