/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR005APIsScheduledDateTime
 */
export interface NEXUZR005APIsScheduledDateTime {
    /**
     * Scheduled departure date and time.
     * @type {string}
     * @memberof NEXUZR005APIsScheduledDateTime
     */
    departureDateTime: string;
    /**
     * Scheduled arrival date and time.
     * @type {string}
     * @memberof NEXUZR005APIsScheduledDateTime
     */
    arrivalDateTime: string;
}

/**
 * Check if a given object implements the NEXUZR005APIsScheduledDateTime interface.
 */
export function instanceOfNEXUZR005APIsScheduledDateTime(value: object): value is NEXUZR005APIsScheduledDateTime {
    if (!('departureDateTime' in value) || value['departureDateTime'] === undefined) return false;
    if (!('arrivalDateTime' in value) || value['arrivalDateTime'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsScheduledDateTimeFromJSON(json: any): NEXUZR005APIsScheduledDateTime {
    return NEXUZR005APIsScheduledDateTimeFromJSONTyped(json, false);
}

export function NEXUZR005APIsScheduledDateTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsScheduledDateTime {
    if (json == null) {
        return json;
    }
    return {
        
        'departureDateTime': json['departureDateTime'],
        'arrivalDateTime': json['arrivalDateTime'],
    };
}

export function NEXUZR005APIsScheduledDateTimeToJSON(json: any): NEXUZR005APIsScheduledDateTime {
    return NEXUZR005APIsScheduledDateTimeToJSONTyped(json, false);
}

export function NEXUZR005APIsScheduledDateTimeToJSONTyped(value?: NEXUZR005APIsScheduledDateTime | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'departureDateTime': value['departureDateTime'],
        'arrivalDateTime': value['arrivalDateTime'],
    };
}

