/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR005APIsPassengerDetails } from './NEXUZR005APIsPassengerDetails';
import {
    NEXUZR005APIsPassengerDetailsFromJSON,
    NEXUZR005APIsPassengerDetailsFromJSONTyped,
    NEXUZR005APIsPassengerDetailsToJSON,
    NEXUZR005APIsPassengerDetailsToJSONTyped,
} from './NEXUZR005APIsPassengerDetails';
import type { NEXUZR005APIsFlights } from './NEXUZR005APIsFlights';
import {
    NEXUZR005APIsFlightsFromJSON,
    NEXUZR005APIsFlightsFromJSONTyped,
    NEXUZR005APIsFlightsToJSON,
    NEXUZR005APIsFlightsToJSONTyped,
} from './NEXUZR005APIsFlights';

/**
 * 
 * @export
 * @interface NEXUZR005APIsSummaryRequest
 */
export interface NEXUZR005APIsSummaryRequest {
    /**
     * Trip type classification.
     * @type {NEXUZR005APIsSummaryRequestTripTypeEnum}
     * @memberof NEXUZR005APIsSummaryRequest
     */
    tripType: NEXUZR005APIsSummaryRequestTripTypeEnum;
    /**
     * Alphanumeric promotion code (optional).
     * @type {string}
     * @memberof NEXUZR005APIsSummaryRequest
     */
    promotionCode?: string;
    /**
     * Total reservation amount.
     * @type {number}
     * @memberof NEXUZR005APIsSummaryRequest
     */
    reservationAmount: number;
    /**
     * 
     * @type {NEXUZR005APIsFlights}
     * @memberof NEXUZR005APIsSummaryRequest
     */
    flights: NEXUZR005APIsFlights;
    /**
     * List of passengers in the booking.
     * @type {Array<NEXUZR005APIsPassengerDetails>}
     * @memberof NEXUZR005APIsSummaryRequest
     */
    passengers: Array<NEXUZR005APIsPassengerDetails>;
}


/**
 * @export
 */
export const NEXUZR005APIsSummaryRequestTripTypeEnum = {
    oneway: 'oneway',
    onewayConnecting: 'onewayConnecting',
    roundTrip: 'roundTrip'
} as const;
export type NEXUZR005APIsSummaryRequestTripTypeEnum = typeof NEXUZR005APIsSummaryRequestTripTypeEnum[keyof typeof NEXUZR005APIsSummaryRequestTripTypeEnum];


/**
 * Check if a given object implements the NEXUZR005APIsSummaryRequest interface.
 */
export function instanceOfNEXUZR005APIsSummaryRequest(value: object): value is NEXUZR005APIsSummaryRequest {
    if (!('tripType' in value) || value['tripType'] === undefined) return false;
    if (!('reservationAmount' in value) || value['reservationAmount'] === undefined) return false;
    if (!('flights' in value) || value['flights'] === undefined) return false;
    if (!('passengers' in value) || value['passengers'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsSummaryRequestFromJSON(json: any): NEXUZR005APIsSummaryRequest {
    return NEXUZR005APIsSummaryRequestFromJSONTyped(json, false);
}

export function NEXUZR005APIsSummaryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsSummaryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'tripType': json['tripType'],
        'promotionCode': json['promotionCode'] == null ? undefined : json['promotionCode'],
        'reservationAmount': json['reservationAmount'],
        'flights': NEXUZR005APIsFlightsFromJSON(json['flights']),
        'passengers': ((json['passengers'] as Array<any>).map(NEXUZR005APIsPassengerDetailsFromJSON)),
    };
}

export function NEXUZR005APIsSummaryRequestToJSON(json: any): NEXUZR005APIsSummaryRequest {
    return NEXUZR005APIsSummaryRequestToJSONTyped(json, false);
}

export function NEXUZR005APIsSummaryRequestToJSONTyped(value?: NEXUZR005APIsSummaryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tripType': value['tripType'],
        'promotionCode': value['promotionCode'],
        'reservationAmount': value['reservationAmount'],
        'flights': NEXUZR005APIsFlightsToJSON(value['flights']),
        'passengers': ((value['passengers'] as Array<any>).map(NEXUZR005APIsPassengerDetailsToJSON)),
    };
}

