/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR005APIsService
 */
export interface NEXUZR005APIsService {
    /**
     * Logical Flight ID for the service.
     * @type {number}
     * @memberof NEXUZR005APIsService
     */
    lfid: number;
    /**
     * Physical Flight ID for the service.
     * @type {number}
     * @memberof NEXUZR005APIsService
     */
    pfid: number;
    /**
     * Service amount (numeric with max 2 decimal places).
     * @type {number}
     * @memberof NEXUZR005APIsService
     */
    amount: number;
    /**
     * Service category identifier.
     * @type {number}
     * @memberof NEXUZR005APIsService
     */
    categoryId: number;
    /**
     * 4-character SSR code.
     * @type {string}
     * @memberof NEXUZR005APIsService
     */
    ssrCode: string;
    /**
     * Numeric service identifier.
     * @type {number}
     * @memberof NEXUZR005APIsService
     */
    serviceID: number;
    /**
     * Descriptive comment for service charge (optional).
     * @type {string}
     * @memberof NEXUZR005APIsService
     */
    chargeComment?: string;
    /**
     * 4-character bundle code (optional).
     * @type {string}
     * @memberof NEXUZR005APIsService
     */
    bundleCode?: string;
}

/**
 * Check if a given object implements the NEXUZR005APIsService interface.
 */
export function instanceOfNEXUZR005APIsService(value: object): value is NEXUZR005APIsService {
    if (!('lfid' in value) || value['lfid'] === undefined) return false;
    if (!('pfid' in value) || value['pfid'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    if (!('ssrCode' in value) || value['ssrCode'] === undefined) return false;
    if (!('serviceID' in value) || value['serviceID'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsServiceFromJSON(json: any): NEXUZR005APIsService {
    return NEXUZR005APIsServiceFromJSONTyped(json, false);
}

export function NEXUZR005APIsServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsService {
    if (json == null) {
        return json;
    }
    return {
        
        'lfid': json['lfid'],
        'pfid': json['pfid'],
        'amount': json['amount'],
        'categoryId': json['categoryId'],
        'ssrCode': json['ssrCode'],
        'serviceID': json['serviceID'],
        'chargeComment': json['chargeComment'] == null ? undefined : json['chargeComment'],
        'bundleCode': json['bundleCode'] == null ? undefined : json['bundleCode'],
    };
}

export function NEXUZR005APIsServiceToJSON(json: any): NEXUZR005APIsService {
    return NEXUZR005APIsServiceToJSONTyped(json, false);
}

export function NEXUZR005APIsServiceToJSONTyped(value?: NEXUZR005APIsService | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lfid': value['lfid'],
        'pfid': value['pfid'],
        'amount': value['amount'],
        'categoryId': value['categoryId'],
        'ssrCode': value['ssrCode'],
        'serviceID': value['serviceID'],
        'chargeComment': value['chargeComment'],
        'bundleCode': value['bundleCode'],
    };
}

