/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Information about a specific service within a category, including the service code, quantity available, and description.
 * @export
 * @interface NEXUZR004OffersService
 */
export interface NEXUZR004OffersService {
    /**
     * Code representing the service.
     * @type {string}
     * @memberof NEXUZR004OffersService
     */
    code: string;
    /**
     * Quantity of the service available.
     * @type {number}
     * @memberof NEXUZR004OffersService
     */
    quantityAvailable: number;
    /**
     * Description of the service.
     * @type {string}
     * @memberof NEXUZR004OffersService
     */
    description: string;
}

/**
 * Check if a given object implements the NEXUZR004OffersService interface.
 */
export function instanceOfNEXUZR004OffersService(value: object): value is NEXUZR004OffersService {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('quantityAvailable' in value) || value['quantityAvailable'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersServiceFromJSON(json: any): NEXUZR004OffersService {
    return NEXUZR004OffersServiceFromJSONTyped(json, false);
}

export function NEXUZR004OffersServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersService {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'quantityAvailable': json['quantityAvailable'],
        'description': json['description'],
    };
}

export function NEXUZR004OffersServiceToJSON(json: any): NEXUZR004OffersService {
    return NEXUZR004OffersServiceToJSONTyped(json, false);
}

export function NEXUZR004OffersServiceToJSONTyped(value?: NEXUZR004OffersService | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'quantityAvailable': value['quantityAvailable'],
        'description': value['description'],
    };
}

