/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR002SearchCalendarFaresData } from './NEXUZR002SearchCalendarFaresData';
import {
    NEXUZR002SearchCalendarFaresDataFromJSON,
    NEXUZR002SearchCalendarFaresDataFromJSONTyped,
    NEXUZR002SearchCalendarFaresDataToJSON,
    NEXUZR002SearchCalendarFaresDataToJSONTyped,
} from './NEXUZR002SearchCalendarFaresData';

/**
 * 
 * @export
 * @interface NEXUZR002SearchCalendarFaresResponse
 */
export interface NEXUZR002SearchCalendarFaresResponse {
    /**
     * 
     * @type {NEXUZR002SearchCalendarFaresData}
     * @memberof NEXUZR002SearchCalendarFaresResponse
     */
    data: NEXUZR002SearchCalendarFaresData;
}

/**
 * Check if a given object implements the NEXUZR002SearchCalendarFaresResponse interface.
 */
export function instanceOfNEXUZR002SearchCalendarFaresResponse(value: object): value is NEXUZR002SearchCalendarFaresResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function NEXUZR002SearchCalendarFaresResponseFromJSON(json: any): NEXUZR002SearchCalendarFaresResponse {
    return NEXUZR002SearchCalendarFaresResponseFromJSONTyped(json, false);
}

export function NEXUZR002SearchCalendarFaresResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR002SearchCalendarFaresResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': NEXUZR002SearchCalendarFaresDataFromJSON(json['data']),
    };
}

export function NEXUZR002SearchCalendarFaresResponseToJSON(json: any): NEXUZR002SearchCalendarFaresResponse {
    return NEXUZR002SearchCalendarFaresResponseToJSONTyped(json, false);
}

export function NEXUZR002SearchCalendarFaresResponseToJSONTyped(value?: NEXUZR002SearchCalendarFaresResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': NEXUZR002SearchCalendarFaresDataToJSON(value['data']),
    };
}

