/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR004OffersPassengers
 */
export interface NEXUZR004OffersPassengers {
    /**
     * Number of adult passengers.
     * @type {number}
     * @memberof NEXUZR004OffersPassengers
     */
    adult: number;
    /**
     * Number of child passengers in category A.
     * @type {number}
     * @memberof NEXUZR004OffersPassengers
     */
    childA?: number;
    /**
     * Number of child passengers in category B.
     * @type {number}
     * @memberof NEXUZR004OffersPassengers
     */
    childB?: number;
    /**
     * Number of child passengers in category C.
     * @type {number}
     * @memberof NEXUZR004OffersPassengers
     */
    childC?: number;
    /**
     * Number of infant passengers.
     * @type {number}
     * @memberof NEXUZR004OffersPassengers
     */
    infant?: number;
}

/**
 * Check if a given object implements the NEXUZR004OffersPassengers interface.
 */
export function instanceOfNEXUZR004OffersPassengers(value: object): value is NEXUZR004OffersPassengers {
    if (!('adult' in value) || value['adult'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersPassengersFromJSON(json: any): NEXUZR004OffersPassengers {
    return NEXUZR004OffersPassengersFromJSONTyped(json, false);
}

export function NEXUZR004OffersPassengersFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersPassengers {
    if (json == null) {
        return json;
    }
    return {
        
        'adult': json['adult'],
        'childA': json['childA'] == null ? undefined : json['childA'],
        'childB': json['childB'] == null ? undefined : json['childB'],
        'childC': json['childC'] == null ? undefined : json['childC'],
        'infant': json['infant'] == null ? undefined : json['infant'],
    };
}

export function NEXUZR004OffersPassengersToJSON(json: any): NEXUZR004OffersPassengers {
    return NEXUZR004OffersPassengersToJSONTyped(json, false);
}

export function NEXUZR004OffersPassengersToJSONTyped(value?: NEXUZR004OffersPassengers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'adult': value['adult'],
        'childA': value['childA'],
        'childB': value['childB'],
        'childC': value['childC'],
        'infant': value['infant'],
    };
}

