/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for retrieving payment status.
 * @export
 * @interface NEXUZR006PaymentPaymentStatusRequest
 */
export interface NEXUZR006PaymentPaymentStatusRequest {
    /**
     * Reference ID for the payment transaction.
     * @type {number}
     * @memberof NEXUZR006PaymentPaymentStatusRequest
     */
    paymentReferenceId: number;
}

/**
 * Check if a given object implements the NEXUZR006PaymentPaymentStatusRequest interface.
 */
export function instanceOfNEXUZR006PaymentPaymentStatusRequest(value: object): value is NEXUZR006PaymentPaymentStatusRequest {
    if (!('paymentReferenceId' in value) || value['paymentReferenceId'] === undefined) return false;
    return true;
}

export function NEXUZR006PaymentPaymentStatusRequestFromJSON(json: any): NEXUZR006PaymentPaymentStatusRequest {
    return NEXUZR006PaymentPaymentStatusRequestFromJSONTyped(json, false);
}

export function NEXUZR006PaymentPaymentStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR006PaymentPaymentStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentReferenceId': json['paymentReferenceId'],
    };
}

export function NEXUZR006PaymentPaymentStatusRequestToJSON(json: any): NEXUZR006PaymentPaymentStatusRequest {
    return NEXUZR006PaymentPaymentStatusRequestToJSONTyped(json, false);
}

export function NEXUZR006PaymentPaymentStatusRequestToJSONTyped(value?: NEXUZR006PaymentPaymentStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paymentReferenceId': value['paymentReferenceId'],
    };
}

