/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR005APIsResponseData } from './NEXUZR005APIsResponseData';
import {
    NEXUZR005APIsResponseDataFromJSON,
    NEXUZR005APIsResponseDataFromJSONTyped,
    NEXUZR005APIsResponseDataToJSON,
    NEXUZR005APIsResponseDataToJSONTyped,
} from './NEXUZR005APIsResponseData';
import type { NEXUZR005APIsWarningMessage } from './NEXUZR005APIsWarningMessage';
import {
    NEXUZR005APIsWarningMessageFromJSON,
    NEXUZR005APIsWarningMessageFromJSONTyped,
    NEXUZR005APIsWarningMessageToJSON,
    NEXUZR005APIsWarningMessageToJSONTyped,
} from './NEXUZR005APIsWarningMessage';

/**
 * Successful order preparation response.
 * @export
 * @interface NEXUZR005APIsSummaryResponse
 */
export interface NEXUZR005APIsSummaryResponse {
    /**
     * 
     * @type {NEXUZR005APIsResponseData}
     * @memberof NEXUZR005APIsSummaryResponse
     */
    data: NEXUZR005APIsResponseData;
    /**
     * 
     * @type {NEXUZR005APIsWarningMessage}
     * @memberof NEXUZR005APIsSummaryResponse
     */
    warning?: NEXUZR005APIsWarningMessage;
}

/**
 * Check if a given object implements the NEXUZR005APIsSummaryResponse interface.
 */
export function instanceOfNEXUZR005APIsSummaryResponse(value: object): value is NEXUZR005APIsSummaryResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsSummaryResponseFromJSON(json: any): NEXUZR005APIsSummaryResponse {
    return NEXUZR005APIsSummaryResponseFromJSONTyped(json, false);
}

export function NEXUZR005APIsSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': NEXUZR005APIsResponseDataFromJSON(json['data']),
        'warning': json['warning'] == null ? undefined : NEXUZR005APIsWarningMessageFromJSON(json['warning']),
    };
}

export function NEXUZR005APIsSummaryResponseToJSON(json: any): NEXUZR005APIsSummaryResponse {
    return NEXUZR005APIsSummaryResponseToJSONTyped(json, false);
}

export function NEXUZR005APIsSummaryResponseToJSONTyped(value?: NEXUZR005APIsSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': NEXUZR005APIsResponseDataToJSON(value['data']),
        'warning': NEXUZR005APIsWarningMessageToJSON(value['warning']),
    };
}

