/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR004OffersSeats } from './NEXUZR004OffersSeats';
import {
    NEXUZR004OffersSeatsFromJSON,
    NEXUZR004OffersSeatsFromJSONTyped,
    NEXUZR004OffersSeatsToJSON,
    NEXUZR004OffersSeatsToJSONTyped,
} from './NEXUZR004OffersSeats';

/**
 * List of rows with associated seat details.
 * @export
 * @interface NEXUZR004OffersSeatInfo
 */
export interface NEXUZR004OffersSeatInfo {
    /**
     * Represents  the row number.
     * @type {number}
     * @memberof NEXUZR004OffersSeatInfo
     */
    row: number;
    /**
     * Contains the column seat details for the corresponding row cabin.
     * @type {Array<NEXUZR004OffersSeats>}
     * @memberof NEXUZR004OffersSeatInfo
     */
    seats: Array<NEXUZR004OffersSeats>;
}

/**
 * Check if a given object implements the NEXUZR004OffersSeatInfo interface.
 */
export function instanceOfNEXUZR004OffersSeatInfo(value: object): value is NEXUZR004OffersSeatInfo {
    if (!('row' in value) || value['row'] === undefined) return false;
    if (!('seats' in value) || value['seats'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersSeatInfoFromJSON(json: any): NEXUZR004OffersSeatInfo {
    return NEXUZR004OffersSeatInfoFromJSONTyped(json, false);
}

export function NEXUZR004OffersSeatInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersSeatInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'row': json['row'],
        'seats': ((json['seats'] as Array<any>).map(NEXUZR004OffersSeatsFromJSON)),
    };
}

export function NEXUZR004OffersSeatInfoToJSON(json: any): NEXUZR004OffersSeatInfo {
    return NEXUZR004OffersSeatInfoToJSONTyped(json, false);
}

export function NEXUZR004OffersSeatInfoToJSONTyped(value?: NEXUZR004OffersSeatInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'row': value['row'],
        'seats': ((value['seats'] as Array<any>).map(NEXUZR004OffersSeatsToJSON)),
    };
}

