/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR005APIsDestinationAddress } from './NEXUZR005APIsDestinationAddress';
import {
    NEXUZR005APIsDestinationAddressFromJSON,
    NEXUZR005APIsDestinationAddressFromJSONTyped,
    NEXUZR005APIsDestinationAddressToJSON,
    NEXUZR005APIsDestinationAddressToJSONTyped,
} from './NEXUZR005APIsDestinationAddress';
import type { NEXUZR005APIsDocument } from './NEXUZR005APIsDocument';
import {
    NEXUZR005APIsDocumentFromJSON,
    NEXUZR005APIsDocumentFromJSONTyped,
    NEXUZR005APIsDocumentToJSON,
    NEXUZR005APIsDocumentToJSONTyped,
} from './NEXUZR005APIsDocument';

/**
 * 
 * @export
 * @interface NEXUZR005APIsPassenger
 */
export interface NEXUZR005APIsPassenger {
    /**
     * Passenger identifier.
     * @type {number}
     * @memberof NEXUZR005APIsPassenger
     */
    id: number;
    /**
     * Passenger type.
     * @type {NEXUZR005APIsPassengerPassengerTypeEnum}
     * @memberof NEXUZR005APIsPassenger
     */
    passengerType: NEXUZR005APIsPassengerPassengerTypeEnum;
    /**
     * Passenger first name.
     * @type {string}
     * @memberof NEXUZR005APIsPassenger
     */
    firstName: string;
    /**
     * Passenger middle name.
     * @type {string}
     * @memberof NEXUZR005APIsPassenger
     */
    middleName?: string;
    /**
     * Passenger last name.
     * @type {string}
     * @memberof NEXUZR005APIsPassenger
     */
    lastName: string;
    /**
     * Passenger gender.
     * @type {NEXUZR005APIsPassengerGenderEnum}
     * @memberof NEXUZR005APIsPassenger
     */
    gender: NEXUZR005APIsPassengerGenderEnum;
    /**
     * Passenger date of birth.
     * @type {string}
     * @memberof NEXUZR005APIsPassenger
     */
    dateOfBirth: string;
    /**
     * Passenger nationality.
     * @type {string}
     * @memberof NEXUZR005APIsPassenger
     */
    nationality: string;
    /**
     * Passenger residence country.
     * @type {string}
     * @memberof NEXUZR005APIsPassenger
     */
    residenceCountry?: string;
    /**
     * 
     * @type {NEXUZR005APIsDestinationAddress}
     * @memberof NEXUZR005APIsPassenger
     */
    destinationAddress?: NEXUZR005APIsDestinationAddress;
    /**
     * Passenger travel documents.
     * @type {Array<NEXUZR005APIsDocument>}
     * @memberof NEXUZR005APIsPassenger
     */
    documents: Array<NEXUZR005APIsDocument>;
}


/**
 * @export
 */
export const NEXUZR005APIsPassengerPassengerTypeEnum = {
    adult: 'Adult',
    childA: 'ChildA',
    childB: 'ChildB',
    childC: 'ChildC',
    infant: 'Infant'
} as const;
export type NEXUZR005APIsPassengerPassengerTypeEnum = typeof NEXUZR005APIsPassengerPassengerTypeEnum[keyof typeof NEXUZR005APIsPassengerPassengerTypeEnum];

/**
 * @export
 */
export const NEXUZR005APIsPassengerGenderEnum = {
    m: 'M',
    f: 'F'
} as const;
export type NEXUZR005APIsPassengerGenderEnum = typeof NEXUZR005APIsPassengerGenderEnum[keyof typeof NEXUZR005APIsPassengerGenderEnum];


/**
 * Check if a given object implements the NEXUZR005APIsPassenger interface.
 */
export function instanceOfNEXUZR005APIsPassenger(value: object): value is NEXUZR005APIsPassenger {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('passengerType' in value) || value['passengerType'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('gender' in value) || value['gender'] === undefined) return false;
    if (!('dateOfBirth' in value) || value['dateOfBirth'] === undefined) return false;
    if (!('nationality' in value) || value['nationality'] === undefined) return false;
    if (!('documents' in value) || value['documents'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsPassengerFromJSON(json: any): NEXUZR005APIsPassenger {
    return NEXUZR005APIsPassengerFromJSONTyped(json, false);
}

export function NEXUZR005APIsPassengerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsPassenger {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'passengerType': json['passengerType'],
        'firstName': json['firstName'],
        'middleName': json['middleName'] == null ? undefined : json['middleName'],
        'lastName': json['lastName'],
        'gender': json['gender'],
        'dateOfBirth': json['dateOfBirth'],
        'nationality': json['nationality'],
        'residenceCountry': json['residenceCountry'] == null ? undefined : json['residenceCountry'],
        'destinationAddress': json['destinationAddress'] == null ? undefined : NEXUZR005APIsDestinationAddressFromJSON(json['destinationAddress']),
        'documents': ((json['documents'] as Array<any>).map(NEXUZR005APIsDocumentFromJSON)),
    };
}

export function NEXUZR005APIsPassengerToJSON(json: any): NEXUZR005APIsPassenger {
    return NEXUZR005APIsPassengerToJSONTyped(json, false);
}

export function NEXUZR005APIsPassengerToJSONTyped(value?: NEXUZR005APIsPassenger | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'passengerType': value['passengerType'],
        'firstName': value['firstName'],
        'middleName': value['middleName'],
        'lastName': value['lastName'],
        'gender': value['gender'],
        'dateOfBirth': value['dateOfBirth'],
        'nationality': value['nationality'],
        'residenceCountry': value['residenceCountry'],
        'destinationAddress': NEXUZR005APIsDestinationAddressToJSON(value['destinationAddress']),
        'documents': ((value['documents'] as Array<any>).map(NEXUZR005APIsDocumentToJSON)),
    };
}

