/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR002SearchArrayOfRoutes } from './NEXUZR002SearchArrayOfRoutes';
import {
    NEXUZR002SearchArrayOfRoutesFromJSON,
    NEXUZR002SearchArrayOfRoutesFromJSONTyped,
    NEXUZR002SearchArrayOfRoutesToJSON,
    NEXUZR002SearchArrayOfRoutesToJSONTyped,
} from './NEXUZR002SearchArrayOfRoutes';

/**
 * 
 * @export
 * @interface NEXUZR002SearchAirportRouteResponse
 */
export interface NEXUZR002SearchAirportRouteResponse {
    /**
     * 
     * @type {NEXUZR002SearchArrayOfRoutes}
     * @memberof NEXUZR002SearchAirportRouteResponse
     */
    data: NEXUZR002SearchArrayOfRoutes;
}

/**
 * Check if a given object implements the NEXUZR002SearchAirportRouteResponse interface.
 */
export function instanceOfNEXUZR002SearchAirportRouteResponse(value: object): value is NEXUZR002SearchAirportRouteResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function NEXUZR002SearchAirportRouteResponseFromJSON(json: any): NEXUZR002SearchAirportRouteResponse {
    return NEXUZR002SearchAirportRouteResponseFromJSONTyped(json, false);
}

export function NEXUZR002SearchAirportRouteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR002SearchAirportRouteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': NEXUZR002SearchArrayOfRoutesFromJSON(json['data']),
    };
}

export function NEXUZR002SearchAirportRouteResponseToJSON(json: any): NEXUZR002SearchAirportRouteResponse {
    return NEXUZR002SearchAirportRouteResponseToJSONTyped(json, false);
}

export function NEXUZR002SearchAirportRouteResponseToJSONTyped(value?: NEXUZR002SearchAirportRouteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': NEXUZR002SearchArrayOfRoutesToJSON(value['data']),
    };
}

