/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR005APIsDocument
 */
export interface NEXUZR005APIsDocument {
    /**
     * Document type ID.
     * @type {number}
     * @memberof NEXUZR005APIsDocument
     */
    documentId: number;
    /**
     * Document number.
     * @type {string}
     * @memberof NEXUZR005APIsDocument
     */
    documentNumber: string;
    /**
     * Issued country.
     * @type {string}
     * @memberof NEXUZR005APIsDocument
     */
    issuedCountry?: string;
    /**
     * Document expiry date.
     * @type {string}
     * @memberof NEXUZR005APIsDocument
     */
    expiryDate: string;
    /**
     * Indicates whether the document was scanned.
     * @type {boolean}
     * @memberof NEXUZR005APIsDocument
     */
    isScanned: boolean;
}

/**
 * Check if a given object implements the NEXUZR005APIsDocument interface.
 */
export function instanceOfNEXUZR005APIsDocument(value: object): value is NEXUZR005APIsDocument {
    if (!('documentId' in value) || value['documentId'] === undefined) return false;
    if (!('documentNumber' in value) || value['documentNumber'] === undefined) return false;
    if (!('expiryDate' in value) || value['expiryDate'] === undefined) return false;
    if (!('isScanned' in value) || value['isScanned'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsDocumentFromJSON(json: any): NEXUZR005APIsDocument {
    return NEXUZR005APIsDocumentFromJSONTyped(json, false);
}

export function NEXUZR005APIsDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'documentId': json['documentId'],
        'documentNumber': json['documentNumber'],
        'issuedCountry': json['issuedCountry'] == null ? undefined : json['issuedCountry'],
        'expiryDate': json['expiryDate'],
        'isScanned': json['isScanned'],
    };
}

export function NEXUZR005APIsDocumentToJSON(json: any): NEXUZR005APIsDocument {
    return NEXUZR005APIsDocumentToJSONTyped(json, false);
}

export function NEXUZR005APIsDocumentToJSONTyped(value?: NEXUZR005APIsDocument | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'documentId': value['documentId'],
        'documentNumber': value['documentNumber'],
        'issuedCountry': value['issuedCountry'],
        'expiryDate': value['expiryDate'],
        'isScanned': value['isScanned'],
    };
}

