/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR007OrderManagementIssuer
 */
export interface NEXUZR007OrderManagementIssuer {
    /**
     * Name of the issuer.
     * @type {string}
     * @memberof NEXUZR007OrderManagementIssuer
     */
    address1: string;
    /**
     * Postal Code of the city.
     * @type {string}
     * @memberof NEXUZR007OrderManagementIssuer
     */
    postalCode: string;
    /**
     * Name of the city.
     * @type {string}
     * @memberof NEXUZR007OrderManagementIssuer
     */
    city: string;
    /**
     * Country Code of the city.
     * @type {string}
     * @memberof NEXUZR007OrderManagementIssuer
     */
    countryCode: string;
}

/**
 * Check if a given object implements the NEXUZR007OrderManagementIssuer interface.
 */
export function instanceOfNEXUZR007OrderManagementIssuer(value: object): value is NEXUZR007OrderManagementIssuer {
    if (!('address1' in value) || value['address1'] === undefined) return false;
    if (!('postalCode' in value) || value['postalCode'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('countryCode' in value) || value['countryCode'] === undefined) return false;
    return true;
}

export function NEXUZR007OrderManagementIssuerFromJSON(json: any): NEXUZR007OrderManagementIssuer {
    return NEXUZR007OrderManagementIssuerFromJSONTyped(json, false);
}

export function NEXUZR007OrderManagementIssuerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR007OrderManagementIssuer {
    if (json == null) {
        return json;
    }
    return {
        
        'address1': json['address1'],
        'postalCode': json['postalCode'],
        'city': json['city'],
        'countryCode': json['countryCode'],
    };
}

export function NEXUZR007OrderManagementIssuerToJSON(json: any): NEXUZR007OrderManagementIssuer {
    return NEXUZR007OrderManagementIssuerToJSONTyped(json, false);
}

export function NEXUZR007OrderManagementIssuerToJSONTyped(value?: NEXUZR007OrderManagementIssuer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address1': value['address1'],
        'postalCode': value['postalCode'],
        'city': value['city'],
        'countryCode': value['countryCode'],
    };
}

