/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR005APIsBundle
 */
export interface NEXUZR005APIsBundle {
    /**
     * Logical Flight ID for the bundle.
     * @type {number}
     * @memberof NEXUZR005APIsBundle
     */
    lfid: number;
    /**
     * Physical Flight ID for the bundle.
     * @type {number}
     * @memberof NEXUZR005APIsBundle
     */
    pfid: number;
    /**
     * 4-character bundle code.
     * @type {string}
     * @memberof NEXUZR005APIsBundle
     */
    bundleCode: string;
    /**
     * Bundle amount (numeric with max 2 decimal places).
     * @type {number}
     * @memberof NEXUZR005APIsBundle
     */
    amount: number;
    /**
     * Bundle category identifier.
     * @type {number}
     * @memberof NEXUZR005APIsBundle
     */
    categoryId: number;
    /**
     * Numeric service identifier for bundle.
     * @type {number}
     * @memberof NEXUZR005APIsBundle
     */
    serviceId: number;
}

/**
 * Check if a given object implements the NEXUZR005APIsBundle interface.
 */
export function instanceOfNEXUZR005APIsBundle(value: object): value is NEXUZR005APIsBundle {
    if (!('lfid' in value) || value['lfid'] === undefined) return false;
    if (!('pfid' in value) || value['pfid'] === undefined) return false;
    if (!('bundleCode' in value) || value['bundleCode'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsBundleFromJSON(json: any): NEXUZR005APIsBundle {
    return NEXUZR005APIsBundleFromJSONTyped(json, false);
}

export function NEXUZR005APIsBundleFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsBundle {
    if (json == null) {
        return json;
    }
    return {
        
        'lfid': json['lfid'],
        'pfid': json['pfid'],
        'bundleCode': json['bundleCode'],
        'amount': json['amount'],
        'categoryId': json['categoryId'],
        'serviceId': json['serviceId'],
    };
}

export function NEXUZR005APIsBundleToJSON(json: any): NEXUZR005APIsBundle {
    return NEXUZR005APIsBundleToJSONTyped(json, false);
}

export function NEXUZR005APIsBundleToJSONTyped(value?: NEXUZR005APIsBundle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lfid': value['lfid'],
        'pfid': value['pfid'],
        'bundleCode': value['bundleCode'],
        'amount': value['amount'],
        'categoryId': value['categoryId'],
        'serviceId': value['serviceId'],
    };
}

