/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR004OffersSeatMapRequest
 */
export interface NEXUZR004OffersSeatMapRequest {
    /**
     * Cabin class selected by the user.
     * @type {NEXUZR004OffersSeatMapRequestCabinEnum}
     * @memberof NEXUZR004OffersSeatMapRequest
     */
    cabin: NEXUZR004OffersSeatMapRequestCabinEnum;
    /**
     * Selected pricing currency.
     * @type {string}
     * @memberof NEXUZR004OffersSeatMapRequest
     */
    currency: string;
    /**
     * Departure date time of the selected flight.
     * @type {string}
     * @memberof NEXUZR004OffersSeatMapRequest
     */
    departureDateTime: string;
    /**
     * Origin and Destination airport details.
     * @type {string}
     * @memberof NEXUZR004OffersSeatMapRequest
     */
    routes: string;
    /**
     * Unique identifier of the selected flight (LFID).
     * @type {number}
     * @memberof NEXUZR004OffersSeatMapRequest
     */
    logicalFlightId: number;
}


/**
 * @export
 */
export const NEXUZR004OffersSeatMapRequestCabinEnum = {
    standard: 'STANDARD',
    zipfullflat: 'ZIPFULLFLAT'
} as const;
export type NEXUZR004OffersSeatMapRequestCabinEnum = typeof NEXUZR004OffersSeatMapRequestCabinEnum[keyof typeof NEXUZR004OffersSeatMapRequestCabinEnum];


/**
 * Check if a given object implements the NEXUZR004OffersSeatMapRequest interface.
 */
export function instanceOfNEXUZR004OffersSeatMapRequest(value: object): value is NEXUZR004OffersSeatMapRequest {
    if (!('cabin' in value) || value['cabin'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('departureDateTime' in value) || value['departureDateTime'] === undefined) return false;
    if (!('routes' in value) || value['routes'] === undefined) return false;
    if (!('logicalFlightId' in value) || value['logicalFlightId'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersSeatMapRequestFromJSON(json: any): NEXUZR004OffersSeatMapRequest {
    return NEXUZR004OffersSeatMapRequestFromJSONTyped(json, false);
}

export function NEXUZR004OffersSeatMapRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersSeatMapRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'cabin': json['cabin'],
        'currency': json['currency'],
        'departureDateTime': json['departureDateTime'],
        'routes': json['routes'],
        'logicalFlightId': json['logicalFlightId'],
    };
}

export function NEXUZR004OffersSeatMapRequestToJSON(json: any): NEXUZR004OffersSeatMapRequest {
    return NEXUZR004OffersSeatMapRequestToJSONTyped(json, false);
}

export function NEXUZR004OffersSeatMapRequestToJSONTyped(value?: NEXUZR004OffersSeatMapRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cabin': value['cabin'],
        'currency': value['currency'],
        'departureDateTime': value['departureDateTime'],
        'routes': value['routes'],
        'logicalFlightId': value['logicalFlightId'],
    };
}

