/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR004OffersFlight } from './NEXUZR004OffersFlight';
import {
    NEXUZR004OffersFlightFromJSON,
    NEXUZR004OffersFlightFromJSONTyped,
    NEXUZR004OffersFlightToJSON,
    NEXUZR004OffersFlightToJSONTyped,
} from './NEXUZR004OffersFlight';

/**
 * Request payload containing flight route, passenger composition, and flight segment details.
 * @export
 * @interface NEXUZR004OffersBundleRequest
 */
export interface NEXUZR004OffersBundleRequest {
    /**
     * Comma-separated airport codes (e.g., BKK,NRT).
     * @type {string}
     * @memberof NEXUZR004OffersBundleRequest
     */
    routes: string;
    /**
     * number of adult passengers.
     * @type {number}
     * @memberof NEXUZR004OffersBundleRequest
     */
    adult: number;
    /**
     * number of child passengers in category A.
     * @type {number}
     * @memberof NEXUZR004OffersBundleRequest
     */
    childA?: number;
    /**
     * number of child passengers in category B.
     * @type {number}
     * @memberof NEXUZR004OffersBundleRequest
     */
    childB?: number;
    /**
     * number of child passengers in category C.
     * @type {number}
     * @memberof NEXUZR004OffersBundleRequest
     */
    childC?: number;
    /**
     * number of infant passengers.
     * @type {number}
     * @memberof NEXUZR004OffersBundleRequest
     */
    infant?: number;
    /**
     * Flight details for the outbound journey. For one-way trips, only `outbound` is required. For round-trips, both `outbound` and `inbound` are required.
     * 
     * @type {Array<NEXUZR004OffersFlight>}
     * @memberof NEXUZR004OffersBundleRequest
     */
    outbound: Array<NEXUZR004OffersFlight>;
    /**
     * Flight details for the inbound journey. Required only for round-trips.
     * 
     * @type {Array<NEXUZR004OffersFlight>}
     * @memberof NEXUZR004OffersBundleRequest
     */
    inbound?: Array<NEXUZR004OffersFlight>;
}

/**
 * Check if a given object implements the NEXUZR004OffersBundleRequest interface.
 */
export function instanceOfNEXUZR004OffersBundleRequest(value: object): value is NEXUZR004OffersBundleRequest {
    if (!('routes' in value) || value['routes'] === undefined) return false;
    if (!('adult' in value) || value['adult'] === undefined) return false;
    if (!('outbound' in value) || value['outbound'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersBundleRequestFromJSON(json: any): NEXUZR004OffersBundleRequest {
    return NEXUZR004OffersBundleRequestFromJSONTyped(json, false);
}

export function NEXUZR004OffersBundleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersBundleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'routes': json['routes'],
        'adult': json['adult'],
        'childA': json['childA'] == null ? undefined : json['childA'],
        'childB': json['childB'] == null ? undefined : json['childB'],
        'childC': json['childC'] == null ? undefined : json['childC'],
        'infant': json['infant'] == null ? undefined : json['infant'],
        'outbound': ((json['outbound'] as Array<any>).map(NEXUZR004OffersFlightFromJSON)),
        'inbound': json['inbound'] == null ? undefined : ((json['inbound'] as Array<any>).map(NEXUZR004OffersFlightFromJSON)),
    };
}

export function NEXUZR004OffersBundleRequestToJSON(json: any): NEXUZR004OffersBundleRequest {
    return NEXUZR004OffersBundleRequestToJSONTyped(json, false);
}

export function NEXUZR004OffersBundleRequestToJSONTyped(value?: NEXUZR004OffersBundleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'routes': value['routes'],
        'adult': value['adult'],
        'childA': value['childA'],
        'childB': value['childB'],
        'childC': value['childC'],
        'infant': value['infant'],
        'outbound': ((value['outbound'] as Array<any>).map(NEXUZR004OffersFlightToJSON)),
        'inbound': value['inbound'] == null ? undefined : ((value['inbound'] as Array<any>).map(NEXUZR004OffersFlightToJSON)),
    };
}

