/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR004OffersService } from './NEXUZR004OffersService';
import {
    NEXUZR004OffersServiceFromJSON,
    NEXUZR004OffersServiceFromJSONTyped,
    NEXUZR004OffersServiceToJSON,
    NEXUZR004OffersServiceToJSONTyped,
} from './NEXUZR004OffersService';

/**
 * Information about a specific service category within a bundle, including the category name and associated services.
 * @export
 * @interface NEXUZR004OffersCategory
 */
export interface NEXUZR004OffersCategory {
    /**
     * Name of the service category such as "Baggage", "Seat", "Meal", etc.
     * @type {string}
     * @memberof NEXUZR004OffersCategory
     */
    category: string;
    /**
     * List of services available within the category.
     * @type {Array<NEXUZR004OffersService>}
     * @memberof NEXUZR004OffersCategory
     */
    services: Array<NEXUZR004OffersService>;
}

/**
 * Check if a given object implements the NEXUZR004OffersCategory interface.
 */
export function instanceOfNEXUZR004OffersCategory(value: object): value is NEXUZR004OffersCategory {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('services' in value) || value['services'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersCategoryFromJSON(json: any): NEXUZR004OffersCategory {
    return NEXUZR004OffersCategoryFromJSONTyped(json, false);
}

export function NEXUZR004OffersCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'],
        'services': ((json['services'] as Array<any>).map(NEXUZR004OffersServiceFromJSON)),
    };
}

export function NEXUZR004OffersCategoryToJSON(json: any): NEXUZR004OffersCategory {
    return NEXUZR004OffersCategoryToJSONTyped(json, false);
}

export function NEXUZR004OffersCategoryToJSONTyped(value?: NEXUZR004OffersCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'services': ((value['services'] as Array<any>).map(NEXUZR004OffersServiceToJSON)),
    };
}

