/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR003FlightsScheduledDateTime
 */
export interface NEXUZR003FlightsScheduledDateTime {
    /**
     * Scheduled departure date/time (local time, no offset).
     * @type {string}
     * @memberof NEXUZR003FlightsScheduledDateTime
     */
    departureDateTime: string;
    /**
     * Departure date/time in UTC with timezone offset.
     * @type {string}
     * @memberof NEXUZR003FlightsScheduledDateTime
     */
    departureDateTimeOffset: string;
    /**
     * Scheduled arrival date/time (local time, no offset).
     * @type {string}
     * @memberof NEXUZR003FlightsScheduledDateTime
     */
    arrivalDateTime: string;
    /**
     * Arrival date/time in UTC with timezone offset.
     * @type {string}
     * @memberof NEXUZR003FlightsScheduledDateTime
     */
    arrivalDateTimeOffset: string;
}

/**
 * Check if a given object implements the NEXUZR003FlightsScheduledDateTime interface.
 */
export function instanceOfNEXUZR003FlightsScheduledDateTime(value: object): value is NEXUZR003FlightsScheduledDateTime {
    if (!('departureDateTime' in value) || value['departureDateTime'] === undefined) return false;
    if (!('departureDateTimeOffset' in value) || value['departureDateTimeOffset'] === undefined) return false;
    if (!('arrivalDateTime' in value) || value['arrivalDateTime'] === undefined) return false;
    if (!('arrivalDateTimeOffset' in value) || value['arrivalDateTimeOffset'] === undefined) return false;
    return true;
}

export function NEXUZR003FlightsScheduledDateTimeFromJSON(json: any): NEXUZR003FlightsScheduledDateTime {
    return NEXUZR003FlightsScheduledDateTimeFromJSONTyped(json, false);
}

export function NEXUZR003FlightsScheduledDateTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR003FlightsScheduledDateTime {
    if (json == null) {
        return json;
    }
    return {
        
        'departureDateTime': json['departureDateTime'],
        'departureDateTimeOffset': json['departureDateTimeOffset'],
        'arrivalDateTime': json['arrivalDateTime'],
        'arrivalDateTimeOffset': json['arrivalDateTimeOffset'],
    };
}

export function NEXUZR003FlightsScheduledDateTimeToJSON(json: any): NEXUZR003FlightsScheduledDateTime {
    return NEXUZR003FlightsScheduledDateTimeToJSONTyped(json, false);
}

export function NEXUZR003FlightsScheduledDateTimeToJSONTyped(value?: NEXUZR003FlightsScheduledDateTime | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'departureDateTime': value['departureDateTime'],
        'departureDateTimeOffset': value['departureDateTimeOffset'],
        'arrivalDateTime': value['arrivalDateTime'],
        'arrivalDateTimeOffset': value['arrivalDateTimeOffset'],
    };
}

