/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR003FlightsFlight } from './NEXUZR003FlightsFlight';
import {
    NEXUZR003FlightsFlightFromJSON,
    NEXUZR003FlightsFlightFromJSONTyped,
    NEXUZR003FlightsFlightToJSON,
    NEXUZR003FlightsFlightToJSONTyped,
} from './NEXUZR003FlightsFlight';

/**
 * Flights available on a specific departure date.
 * @export
 * @interface NEXUZR003FlightsFlightsByDate
 */
export interface NEXUZR003FlightsFlightsByDate {
    /**
     * Departure date in `yyyy-MM-dd` format.
     * @type {string}
     * @memberof NEXUZR003FlightsFlightsByDate
     */
    date: string;
    /**
     * List of available flights on this date.
     * @type {Array<NEXUZR003FlightsFlight>}
     * @memberof NEXUZR003FlightsFlightsByDate
     */
    flights: Array<NEXUZR003FlightsFlight>;
}

/**
 * Check if a given object implements the NEXUZR003FlightsFlightsByDate interface.
 */
export function instanceOfNEXUZR003FlightsFlightsByDate(value: object): value is NEXUZR003FlightsFlightsByDate {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('flights' in value) || value['flights'] === undefined) return false;
    return true;
}

export function NEXUZR003FlightsFlightsByDateFromJSON(json: any): NEXUZR003FlightsFlightsByDate {
    return NEXUZR003FlightsFlightsByDateFromJSONTyped(json, false);
}

export function NEXUZR003FlightsFlightsByDateFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR003FlightsFlightsByDate {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'flights': ((json['flights'] as Array<any>).map(NEXUZR003FlightsFlightFromJSON)),
    };
}

export function NEXUZR003FlightsFlightsByDateToJSON(json: any): NEXUZR003FlightsFlightsByDate {
    return NEXUZR003FlightsFlightsByDateToJSONTyped(json, false);
}

export function NEXUZR003FlightsFlightsByDateToJSONTyped(value?: NEXUZR003FlightsFlightsByDate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'flights': ((value['flights'] as Array<any>).map(NEXUZR003FlightsFlightToJSON)),
    };
}

