/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR005APIsFlightSegment } from './NEXUZR005APIsFlightSegment';
import {
    NEXUZR005APIsFlightSegmentFromJSON,
    NEXUZR005APIsFlightSegmentFromJSONTyped,
    NEXUZR005APIsFlightSegmentToJSON,
    NEXUZR005APIsFlightSegmentToJSONTyped,
} from './NEXUZR005APIsFlightSegment';

/**
 * 
 * @export
 * @interface NEXUZR005APIsFlightBound
 */
export interface NEXUZR005APIsFlightBound {
    /**
     * List of flight segments within bound.
     * @type {Array<NEXUZR005APIsFlightSegment>}
     * @memberof NEXUZR005APIsFlightBound
     */
    segments: Array<NEXUZR005APIsFlightSegment>;
}

/**
 * Check if a given object implements the NEXUZR005APIsFlightBound interface.
 */
export function instanceOfNEXUZR005APIsFlightBound(value: object): value is NEXUZR005APIsFlightBound {
    if (!('segments' in value) || value['segments'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsFlightBoundFromJSON(json: any): NEXUZR005APIsFlightBound {
    return NEXUZR005APIsFlightBoundFromJSONTyped(json, false);
}

export function NEXUZR005APIsFlightBoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsFlightBound {
    if (json == null) {
        return json;
    }
    return {
        
        'segments': ((json['segments'] as Array<any>).map(NEXUZR005APIsFlightSegmentFromJSON)),
    };
}

export function NEXUZR005APIsFlightBoundToJSON(json: any): NEXUZR005APIsFlightBound {
    return NEXUZR005APIsFlightBoundToJSONTyped(json, false);
}

export function NEXUZR005APIsFlightBoundToJSONTyped(value?: NEXUZR005APIsFlightBound | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'segments': ((value['segments'] as Array<any>).map(NEXUZR005APIsFlightSegmentToJSON)),
    };
}

