/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR004OffersPassengerType } from './NEXUZR004OffersPassengerType';
import {
    NEXUZR004OffersPassengerTypeFromJSON,
    NEXUZR004OffersPassengerTypeFromJSONTyped,
    NEXUZR004OffersPassengerTypeToJSON,
    NEXUZR004OffersPassengerTypeToJSONTyped,
} from './NEXUZR004OffersPassengerType';

/**
 * Bundle information including bundle code and passenger types with their associated services.
 * @export
 * @interface NEXUZR004OffersBundle
 */
export interface NEXUZR004OffersBundle {
    /**
     * Code representing the bundle.
     * @type {string}
     * @memberof NEXUZR004OffersBundle
     */
    bundleCode: string;
    /**
     * List of passenger types and their associated services within the bundle.
     * @type {Array<NEXUZR004OffersPassengerType>}
     * @memberof NEXUZR004OffersBundle
     */
    passengerTypes: Array<NEXUZR004OffersPassengerType>;
}

/**
 * Check if a given object implements the NEXUZR004OffersBundle interface.
 */
export function instanceOfNEXUZR004OffersBundle(value: object): value is NEXUZR004OffersBundle {
    if (!('bundleCode' in value) || value['bundleCode'] === undefined) return false;
    if (!('passengerTypes' in value) || value['passengerTypes'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersBundleFromJSON(json: any): NEXUZR004OffersBundle {
    return NEXUZR004OffersBundleFromJSONTyped(json, false);
}

export function NEXUZR004OffersBundleFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersBundle {
    if (json == null) {
        return json;
    }
    return {
        
        'bundleCode': json['bundleCode'],
        'passengerTypes': ((json['passengerTypes'] as Array<any>).map(NEXUZR004OffersPassengerTypeFromJSON)),
    };
}

export function NEXUZR004OffersBundleToJSON(json: any): NEXUZR004OffersBundle {
    return NEXUZR004OffersBundleToJSONTyped(json, false);
}

export function NEXUZR004OffersBundleToJSONTyped(value?: NEXUZR004OffersBundle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bundleCode': value['bundleCode'],
        'passengerTypes': ((value['passengerTypes'] as Array<any>).map(NEXUZR004OffersPassengerTypeToJSON)),
    };
}

