/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR004OffersSpecialService } from './NEXUZR004OffersSpecialService';
import {
    NEXUZR004OffersSpecialServiceFromJSON,
    NEXUZR004OffersSpecialServiceFromJSONTyped,
    NEXUZR004OffersSpecialServiceToJSON,
    NEXUZR004OffersSpecialServiceToJSONTyped,
} from './NEXUZR004OffersSpecialService';

/**
 * 
 * @export
 * @interface NEXUZR004OffersServiceCategory
 */
export interface NEXUZR004OffersServiceCategory {
    /**
     * Category title.
     * @type {string}
     * @memberof NEXUZR004OffersServiceCategory
     */
    title: string;
    /**
     * Category ID.
     * @type {number}
     * @memberof NEXUZR004OffersServiceCategory
     */
    categoryId: number;
    /**
     * 
     * @type {Array<NEXUZR004OffersSpecialService>}
     * @memberof NEXUZR004OffersServiceCategory
     */
    specialServices: Array<NEXUZR004OffersSpecialService>;
}

/**
 * Check if a given object implements the NEXUZR004OffersServiceCategory interface.
 */
export function instanceOfNEXUZR004OffersServiceCategory(value: object): value is NEXUZR004OffersServiceCategory {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    if (!('specialServices' in value) || value['specialServices'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersServiceCategoryFromJSON(json: any): NEXUZR004OffersServiceCategory {
    return NEXUZR004OffersServiceCategoryFromJSONTyped(json, false);
}

export function NEXUZR004OffersServiceCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersServiceCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'categoryId': json['categoryId'],
        'specialServices': ((json['specialServices'] as Array<any>).map(NEXUZR004OffersSpecialServiceFromJSON)),
    };
}

export function NEXUZR004OffersServiceCategoryToJSON(json: any): NEXUZR004OffersServiceCategory {
    return NEXUZR004OffersServiceCategoryToJSONTyped(json, false);
}

export function NEXUZR004OffersServiceCategoryToJSONTyped(value?: NEXUZR004OffersServiceCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'categoryId': value['categoryId'],
        'specialServices': ((value['specialServices'] as Array<any>).map(NEXUZR004OffersSpecialServiceToJSON)),
    };
}

