/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR005APIsRecipientInfo
 */
export interface NEXUZR005APIsRecipientInfo {
    /**
     * Recipient first name.
     * @type {string}
     * @memberof NEXUZR005APIsRecipientInfo
     */
    firstName: string;
    /**
     * Recipient last name.
     * @type {string}
     * @memberof NEXUZR005APIsRecipientInfo
     */
    lastName: string;
    /**
     * Recipient middle name.
     * @type {string}
     * @memberof NEXUZR005APIsRecipientInfo
     */
    middleName?: string;
    /**
     * Recipient email address.
     * @type {string}
     * @memberof NEXUZR005APIsRecipientInfo
     */
    emailAddress: string;
}

/**
 * Check if a given object implements the NEXUZR005APIsRecipientInfo interface.
 */
export function instanceOfNEXUZR005APIsRecipientInfo(value: object): value is NEXUZR005APIsRecipientInfo {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('emailAddress' in value) || value['emailAddress'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsRecipientInfoFromJSON(json: any): NEXUZR005APIsRecipientInfo {
    return NEXUZR005APIsRecipientInfoFromJSONTyped(json, false);
}

export function NEXUZR005APIsRecipientInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsRecipientInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'middleName': json['middleName'] == null ? undefined : json['middleName'],
        'emailAddress': json['emailAddress'],
    };
}

export function NEXUZR005APIsRecipientInfoToJSON(json: any): NEXUZR005APIsRecipientInfo {
    return NEXUZR005APIsRecipientInfoToJSONTyped(json, false);
}

export function NEXUZR005APIsRecipientInfoToJSONTyped(value?: NEXUZR005APIsRecipientInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'middleName': value['middleName'],
        'emailAddress': value['emailAddress'],
    };
}

