/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR002SearchErrorResponse
 */
export interface NEXUZR002SearchErrorResponse {
    /**
     * Custom error code
     * @type {string}
     * @memberof NEXUZR002SearchErrorResponse
     */
    code: string;
    /**
     * Error description
     * @type {string}
     * @memberof NEXUZR002SearchErrorResponse
     */
    description: string;
}

/**
 * Check if a given object implements the NEXUZR002SearchErrorResponse interface.
 */
export function instanceOfNEXUZR002SearchErrorResponse(value: object): value is NEXUZR002SearchErrorResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function NEXUZR002SearchErrorResponseFromJSON(json: any): NEXUZR002SearchErrorResponse {
    return NEXUZR002SearchErrorResponseFromJSONTyped(json, false);
}

export function NEXUZR002SearchErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR002SearchErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
    };
}

export function NEXUZR002SearchErrorResponseToJSON(json: any): NEXUZR002SearchErrorResponse {
    return NEXUZR002SearchErrorResponseToJSONTyped(json, false);
}

export function NEXUZR002SearchErrorResponseToJSONTyped(value?: NEXUZR002SearchErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
    };
}

