/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR004OffersBundle } from './NEXUZR004OffersBundle';
import {
    NEXUZR004OffersBundleFromJSON,
    NEXUZR004OffersBundleFromJSONTyped,
    NEXUZR004OffersBundleToJSON,
    NEXUZR004OffersBundleToJSONTyped,
} from './NEXUZR004OffersBundle';

/**
 * Bundle information for a specific flight segment, identified by its Logical Flight ID (LFID).
 * @export
 * @interface NEXUZR004OffersSegmentWiseBundle
 */
export interface NEXUZR004OffersSegmentWiseBundle {
    /**
     * Logical Flight ID (LFID) representing the flight segment.
     * @type {number}
     * @memberof NEXUZR004OffersSegmentWiseBundle
     */
    lfid: number;
    /**
     * List of bundles available for the flight segment.
     * @type {Array<NEXUZR004OffersBundle>}
     * @memberof NEXUZR004OffersSegmentWiseBundle
     */
    bundles: Array<NEXUZR004OffersBundle>;
}

/**
 * Check if a given object implements the NEXUZR004OffersSegmentWiseBundle interface.
 */
export function instanceOfNEXUZR004OffersSegmentWiseBundle(value: object): value is NEXUZR004OffersSegmentWiseBundle {
    if (!('lfid' in value) || value['lfid'] === undefined) return false;
    if (!('bundles' in value) || value['bundles'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersSegmentWiseBundleFromJSON(json: any): NEXUZR004OffersSegmentWiseBundle {
    return NEXUZR004OffersSegmentWiseBundleFromJSONTyped(json, false);
}

export function NEXUZR004OffersSegmentWiseBundleFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersSegmentWiseBundle {
    if (json == null) {
        return json;
    }
    return {
        
        'lfid': json['lfid'],
        'bundles': ((json['bundles'] as Array<any>).map(NEXUZR004OffersBundleFromJSON)),
    };
}

export function NEXUZR004OffersSegmentWiseBundleToJSON(json: any): NEXUZR004OffersSegmentWiseBundle {
    return NEXUZR004OffersSegmentWiseBundleToJSONTyped(json, false);
}

export function NEXUZR004OffersSegmentWiseBundleToJSONTyped(value?: NEXUZR004OffersSegmentWiseBundle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lfid': value['lfid'],
        'bundles': ((value['bundles'] as Array<any>).map(NEXUZR004OffersBundleToJSON)),
    };
}

