/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Contains the column seat details for the corresponding row cabin.
 * @export
 * @interface NEXUZR004OffersSeats
 */
export interface NEXUZR004OffersSeats {
    /**
     * Represents the seat column position within the row.
     * @type {string}
     * @memberof NEXUZR004OffersSeats
     */
    column: string;
    /**
     * Indicates whether the seat is available or not.
     * @type {boolean}
     * @memberof NEXUZR004OffersSeats
     */
    isSeatAvailable: boolean;
    /**
     * amount for the requested seat.
     * @type {number}
     * @memberof NEXUZR004OffersSeats
     */
    amount: number;
    /**
     * Service code associated with the seat.
     * @type {string}
     * @memberof NEXUZR004OffersSeats
     */
    serviceCode: string;
}

/**
 * Check if a given object implements the NEXUZR004OffersSeats interface.
 */
export function instanceOfNEXUZR004OffersSeats(value: object): value is NEXUZR004OffersSeats {
    if (!('column' in value) || value['column'] === undefined) return false;
    if (!('isSeatAvailable' in value) || value['isSeatAvailable'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('serviceCode' in value) || value['serviceCode'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersSeatsFromJSON(json: any): NEXUZR004OffersSeats {
    return NEXUZR004OffersSeatsFromJSONTyped(json, false);
}

export function NEXUZR004OffersSeatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersSeats {
    if (json == null) {
        return json;
    }
    return {
        
        'column': json['column'],
        'isSeatAvailable': json['isSeatAvailable'],
        'amount': json['amount'],
        'serviceCode': json['serviceCode'],
    };
}

export function NEXUZR004OffersSeatsToJSON(json: any): NEXUZR004OffersSeats {
    return NEXUZR004OffersSeatsToJSONTyped(json, false);
}

export function NEXUZR004OffersSeatsToJSONTyped(value?: NEXUZR004OffersSeats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'column': value['column'],
        'isSeatAvailable': value['isSeatAvailable'],
        'amount': value['amount'],
        'serviceCode': value['serviceCode'],
    };
}

