/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR001CoreErrorResponse
 */
export interface NEXUZR001CoreErrorResponse {
    /**
     * Custom error code
     * @type {string}
     * @memberof NEXUZR001CoreErrorResponse
     */
    code: string;
    /**
     * Error description
     * @type {string}
     * @memberof NEXUZR001CoreErrorResponse
     */
    description: string;
}

/**
 * Check if a given object implements the NEXUZR001CoreErrorResponse interface.
 */
export function instanceOfNEXUZR001CoreErrorResponse(value: object): value is NEXUZR001CoreErrorResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function NEXUZR001CoreErrorResponseFromJSON(json: any): NEXUZR001CoreErrorResponse {
    return NEXUZR001CoreErrorResponseFromJSONTyped(json, false);
}

export function NEXUZR001CoreErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR001CoreErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
    };
}

export function NEXUZR001CoreErrorResponseToJSON(json: any): NEXUZR001CoreErrorResponse {
    return NEXUZR001CoreErrorResponseToJSONTyped(json, false);
}

export function NEXUZR001CoreErrorResponseToJSONTyped(value?: NEXUZR001CoreErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
    };
}

