/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR005APIsRecipientInfo } from './NEXUZR005APIsRecipientInfo';
import {
    NEXUZR005APIsRecipientInfoFromJSON,
    NEXUZR005APIsRecipientInfoFromJSONTyped,
    NEXUZR005APIsRecipientInfoToJSON,
    NEXUZR005APIsRecipientInfoToJSONTyped,
} from './NEXUZR005APIsRecipientInfo';
import type { NEXUZR005APIsPassenger } from './NEXUZR005APIsPassenger';
import {
    NEXUZR005APIsPassengerFromJSON,
    NEXUZR005APIsPassengerFromJSONTyped,
    NEXUZR005APIsPassengerToJSON,
    NEXUZR005APIsPassengerToJSONTyped,
} from './NEXUZR005APIsPassenger';

/**
 * 
 * @export
 * @interface NEXUZR005APIsCreateOrderRequest
 */
export interface NEXUZR005APIsCreateOrderRequest {
    /**
     * Encrypted value for arkose verification.
     * @type {string}
     * @memberof NEXUZR005APIsCreateOrderRequest
     */
    verifyToken: string;
    /**
     * List of passengers.
     * @type {Array<NEXUZR005APIsPassenger>}
     * @memberof NEXUZR005APIsCreateOrderRequest
     */
    passengers: Array<NEXUZR005APIsPassenger>;
    /**
     * 
     * @type {NEXUZR005APIsRecipientInfo}
     * @memberof NEXUZR005APIsCreateOrderRequest
     */
    recipientInfo: NEXUZR005APIsRecipientInfo;
}

/**
 * Check if a given object implements the NEXUZR005APIsCreateOrderRequest interface.
 */
export function instanceOfNEXUZR005APIsCreateOrderRequest(value: object): value is NEXUZR005APIsCreateOrderRequest {
    if (!('verifyToken' in value) || value['verifyToken'] === undefined) return false;
    if (!('passengers' in value) || value['passengers'] === undefined) return false;
    if (!('recipientInfo' in value) || value['recipientInfo'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsCreateOrderRequestFromJSON(json: any): NEXUZR005APIsCreateOrderRequest {
    return NEXUZR005APIsCreateOrderRequestFromJSONTyped(json, false);
}

export function NEXUZR005APIsCreateOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsCreateOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'verifyToken': json['verifyToken'],
        'passengers': ((json['passengers'] as Array<any>).map(NEXUZR005APIsPassengerFromJSON)),
        'recipientInfo': NEXUZR005APIsRecipientInfoFromJSON(json['recipientInfo']),
    };
}

export function NEXUZR005APIsCreateOrderRequestToJSON(json: any): NEXUZR005APIsCreateOrderRequest {
    return NEXUZR005APIsCreateOrderRequestToJSONTyped(json, false);
}

export function NEXUZR005APIsCreateOrderRequestToJSONTyped(value?: NEXUZR005APIsCreateOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verifyToken': value['verifyToken'],
        'passengers': ((value['passengers'] as Array<any>).map(NEXUZR005APIsPassengerToJSON)),
        'recipientInfo': NEXUZR005APIsRecipientInfoToJSON(value['recipientInfo']),
    };
}

