/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR003FlightsFareInfo } from './NEXUZR003FlightsFareInfo';
import {
    NEXUZR003FlightsFareInfoFromJSON,
    NEXUZR003FlightsFareInfoFromJSONTyped,
    NEXUZR003FlightsFareInfoToJSON,
    NEXUZR003FlightsFareInfoToJSONTyped,
} from './NEXUZR003FlightsFareInfo';
import type { NEXUZR003FlightsScheduledDateTime } from './NEXUZR003FlightsScheduledDateTime';
import {
    NEXUZR003FlightsScheduledDateTimeFromJSON,
    NEXUZR003FlightsScheduledDateTimeFromJSONTyped,
    NEXUZR003FlightsScheduledDateTimeToJSON,
    NEXUZR003FlightsScheduledDateTimeToJSONTyped,
} from './NEXUZR003FlightsScheduledDateTime';

/**
 * A single flight segment (leg).
 * @export
 * @interface NEXUZR003FlightsSegment
 */
export interface NEXUZR003FlightsSegment {
    /**
     * Set to `true` if the arrival date is before the departure date.
     * Set to `null` if arrival date equals departure date.
     * 
     * @type {boolean}
     * @memberof NEXUZR003FlightsSegment
     */
    previousDayIndicator?: boolean | null;
    /**
     * Set to `true` if the arrival date is after the departure date.
     * Set to `null` if arrival date equals departure date.
     * 
     * @type {boolean}
     * @memberof NEXUZR003FlightsSegment
     */
    nextDayIndicator?: boolean | null;
    /**
     * Operating carrier IATA code.
     * @type {string}
     * @memberof NEXUZR003FlightsSegment
     */
    carrierCode: string;
    /**
     * Departure airport IATA code.
     * @type {string}
     * @memberof NEXUZR003FlightsSegment
     */
    origin: string;
    /**
     * Arrival airport IATA code.
     * @type {string}
     * @memberof NEXUZR003FlightsSegment
     */
    destination: string;
    /**
     * 
     * @type {NEXUZR003FlightsScheduledDateTime}
     * @memberof NEXUZR003FlightsSegment
     */
    scheduledDepartureArrivalDateTime: NEXUZR003FlightsScheduledDateTime;
    /**
     * Flight duration in `HH:MM` format.
     * @type {string}
     * @memberof NEXUZR003FlightsSegment
     */
    flightTime: string;
    /**
     * Flight number.
     * @type {string}
     * @memberof NEXUZR003FlightsSegment
     */
    flightNumber: string;
    /**
     * Physical Flight ID.
     * @type {number}
     * @memberof NEXUZR003FlightsSegment
     */
    pfid: number;
    /**
     * Logical Flight ID.
     * @type {number}
     * @memberof NEXUZR003FlightsSegment
     */
    lfid: number;
    /**
     * Fare information grouped by cabin (STANDARD and/or ZIPFULLFLAT).
     * @type {Array<NEXUZR003FlightsFareInfo>}
     * @memberof NEXUZR003FlightsSegment
     */
    fareInfos: Array<NEXUZR003FlightsFareInfo>;
}

/**
 * Check if a given object implements the NEXUZR003FlightsSegment interface.
 */
export function instanceOfNEXUZR003FlightsSegment(value: object): value is NEXUZR003FlightsSegment {
    if (!('carrierCode' in value) || value['carrierCode'] === undefined) return false;
    if (!('origin' in value) || value['origin'] === undefined) return false;
    if (!('destination' in value) || value['destination'] === undefined) return false;
    if (!('scheduledDepartureArrivalDateTime' in value) || value['scheduledDepartureArrivalDateTime'] === undefined) return false;
    if (!('flightTime' in value) || value['flightTime'] === undefined) return false;
    if (!('flightNumber' in value) || value['flightNumber'] === undefined) return false;
    if (!('pfid' in value) || value['pfid'] === undefined) return false;
    if (!('lfid' in value) || value['lfid'] === undefined) return false;
    if (!('fareInfos' in value) || value['fareInfos'] === undefined) return false;
    return true;
}

export function NEXUZR003FlightsSegmentFromJSON(json: any): NEXUZR003FlightsSegment {
    return NEXUZR003FlightsSegmentFromJSONTyped(json, false);
}

export function NEXUZR003FlightsSegmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR003FlightsSegment {
    if (json == null) {
        return json;
    }
    return {
        
        'previousDayIndicator': json['previousDayIndicator'] == null ? undefined : json['previousDayIndicator'],
        'nextDayIndicator': json['nextDayIndicator'] == null ? undefined : json['nextDayIndicator'],
        'carrierCode': json['carrierCode'],
        'origin': json['origin'],
        'destination': json['destination'],
        'scheduledDepartureArrivalDateTime': NEXUZR003FlightsScheduledDateTimeFromJSON(json['scheduledDepartureArrivalDateTime']),
        'flightTime': json['flightTime'],
        'flightNumber': json['flightNumber'],
        'pfid': json['pfid'],
        'lfid': json['lfid'],
        'fareInfos': ((json['fareInfos'] as Array<any>).map(NEXUZR003FlightsFareInfoFromJSON)),
    };
}

export function NEXUZR003FlightsSegmentToJSON(json: any): NEXUZR003FlightsSegment {
    return NEXUZR003FlightsSegmentToJSONTyped(json, false);
}

export function NEXUZR003FlightsSegmentToJSONTyped(value?: NEXUZR003FlightsSegment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'previousDayIndicator': value['previousDayIndicator'],
        'nextDayIndicator': value['nextDayIndicator'],
        'carrierCode': value['carrierCode'],
        'origin': value['origin'],
        'destination': value['destination'],
        'scheduledDepartureArrivalDateTime': NEXUZR003FlightsScheduledDateTimeToJSON(value['scheduledDepartureArrivalDateTime']),
        'flightTime': value['flightTime'],
        'flightNumber': value['flightNumber'],
        'pfid': value['pfid'],
        'lfid': value['lfid'],
        'fareInfos': ((value['fareInfos'] as Array<any>).map(NEXUZR003FlightsFareInfoToJSON)),
    };
}

