/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR005APIsWarningMessage
 */
export interface NEXUZR005APIsWarningMessage {
    /**
     * An application-specific error code
     * @type {string}
     * @memberof NEXUZR005APIsWarningMessage
     */
    code: string;
    /**
     * Warning description
     * @type {string}
     * @memberof NEXUZR005APIsWarningMessage
     */
    description: string;
}

/**
 * Check if a given object implements the NEXUZR005APIsWarningMessage interface.
 */
export function instanceOfNEXUZR005APIsWarningMessage(value: object): value is NEXUZR005APIsWarningMessage {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsWarningMessageFromJSON(json: any): NEXUZR005APIsWarningMessage {
    return NEXUZR005APIsWarningMessageFromJSONTyped(json, false);
}

export function NEXUZR005APIsWarningMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsWarningMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
    };
}

export function NEXUZR005APIsWarningMessageToJSON(json: any): NEXUZR005APIsWarningMessage {
    return NEXUZR005APIsWarningMessageToJSONTyped(json, false);
}

export function NEXUZR005APIsWarningMessageToJSONTyped(value?: NEXUZR005APIsWarningMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
    };
}

