/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR005APIsContactInformation
 */
export interface NEXUZR005APIsContactInformation {
    /**
     * Country dialling code.
     * @type {string}
     * @memberof NEXUZR005APIsContactInformation
     */
    countryCode: string;
    /**
     * Contact phone number.
     * @type {string}
     * @memberof NEXUZR005APIsContactInformation
     */
    phoneNumber: string;
    /**
     * Contact email address.
     * @type {string}
     * @memberof NEXUZR005APIsContactInformation
     */
    email: string;
}

/**
 * Check if a given object implements the NEXUZR005APIsContactInformation interface.
 */
export function instanceOfNEXUZR005APIsContactInformation(value: object): value is NEXUZR005APIsContactInformation {
    if (!('countryCode' in value) || value['countryCode'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsContactInformationFromJSON(json: any): NEXUZR005APIsContactInformation {
    return NEXUZR005APIsContactInformationFromJSONTyped(json, false);
}

export function NEXUZR005APIsContactInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsContactInformation {
    if (json == null) {
        return json;
    }
    return {
        
        'countryCode': json['countryCode'],
        'phoneNumber': json['phoneNumber'],
        'email': json['email'],
    };
}

export function NEXUZR005APIsContactInformationToJSON(json: any): NEXUZR005APIsContactInformation {
    return NEXUZR005APIsContactInformationToJSONTyped(json, false);
}

export function NEXUZR005APIsContactInformationToJSONTyped(value?: NEXUZR005APIsContactInformation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'countryCode': value['countryCode'],
        'phoneNumber': value['phoneNumber'],
        'email': value['email'],
    };
}

