/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR004OffersServicesPerPassengerType } from './NEXUZR004OffersServicesPerPassengerType';
import {
    NEXUZR004OffersServicesPerPassengerTypeFromJSON,
    NEXUZR004OffersServicesPerPassengerTypeFromJSONTyped,
    NEXUZR004OffersServicesPerPassengerTypeToJSON,
    NEXUZR004OffersServicesPerPassengerTypeToJSONTyped,
} from './NEXUZR004OffersServicesPerPassengerType';

/**
 * 
 * @export
 * @interface NEXUZR004OffersServiceGroup
 */
export interface NEXUZR004OffersServiceGroup {
    /**
     * 
     * @type {Array<NEXUZR004OffersServicesPerPassengerType>}
     * @memberof NEXUZR004OffersServiceGroup
     */
    servicesPerPassengerType: Array<NEXUZR004OffersServicesPerPassengerType>;
}

/**
 * Check if a given object implements the NEXUZR004OffersServiceGroup interface.
 */
export function instanceOfNEXUZR004OffersServiceGroup(value: object): value is NEXUZR004OffersServiceGroup {
    if (!('servicesPerPassengerType' in value) || value['servicesPerPassengerType'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersServiceGroupFromJSON(json: any): NEXUZR004OffersServiceGroup {
    return NEXUZR004OffersServiceGroupFromJSONTyped(json, false);
}

export function NEXUZR004OffersServiceGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersServiceGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'servicesPerPassengerType': ((json['servicesPerPassengerType'] as Array<any>).map(NEXUZR004OffersServicesPerPassengerTypeFromJSON)),
    };
}

export function NEXUZR004OffersServiceGroupToJSON(json: any): NEXUZR004OffersServiceGroup {
    return NEXUZR004OffersServiceGroupToJSONTyped(json, false);
}

export function NEXUZR004OffersServiceGroupToJSONTyped(value?: NEXUZR004OffersServiceGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'servicesPerPassengerType': ((value['servicesPerPassengerType'] as Array<any>).map(NEXUZR004OffersServicesPerPassengerTypeToJSON)),
    };
}

