/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR002SearchRoutes
 */
export interface NEXUZR002SearchRoutes {
    /**
     * Origin airport code
     * @type {string}
     * @memberof NEXUZR002SearchRoutes
     */
    origin: string;
    /**
     * Destination airport code
     * @type {string}
     * @memberof NEXUZR002SearchRoutes
     */
    destination: string;
}

/**
 * Check if a given object implements the NEXUZR002SearchRoutes interface.
 */
export function instanceOfNEXUZR002SearchRoutes(value: object): value is NEXUZR002SearchRoutes {
    if (!('origin' in value) || value['origin'] === undefined) return false;
    if (!('destination' in value) || value['destination'] === undefined) return false;
    return true;
}

export function NEXUZR002SearchRoutesFromJSON(json: any): NEXUZR002SearchRoutes {
    return NEXUZR002SearchRoutesFromJSONTyped(json, false);
}

export function NEXUZR002SearchRoutesFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR002SearchRoutes {
    if (json == null) {
        return json;
    }
    return {
        
        'origin': json['origin'],
        'destination': json['destination'],
    };
}

export function NEXUZR002SearchRoutesToJSON(json: any): NEXUZR002SearchRoutes {
    return NEXUZR002SearchRoutesToJSONTyped(json, false);
}

export function NEXUZR002SearchRoutesToJSONTyped(value?: NEXUZR002SearchRoutes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'origin': value['origin'],
        'destination': value['destination'],
    };
}

