/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Warning message returned along with response
 * @export
 * @interface NEXUZR004OffersWarningMessage
 */
export interface NEXUZR004OffersWarningMessage {
    /**
     * 
     * @type {string}
     * @memberof NEXUZR004OffersWarningMessage
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof NEXUZR004OffersWarningMessage
     */
    warningDescription?: string;
}

/**
 * Check if a given object implements the NEXUZR004OffersWarningMessage interface.
 */
export function instanceOfNEXUZR004OffersWarningMessage(value: object): value is NEXUZR004OffersWarningMessage {
    return true;
}

export function NEXUZR004OffersWarningMessageFromJSON(json: any): NEXUZR004OffersWarningMessage {
    return NEXUZR004OffersWarningMessageFromJSONTyped(json, false);
}

export function NEXUZR004OffersWarningMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersWarningMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'warningDescription': json['warningDescription'] == null ? undefined : json['warningDescription'],
    };
}

export function NEXUZR004OffersWarningMessageToJSON(json: any): NEXUZR004OffersWarningMessage {
    return NEXUZR004OffersWarningMessageToJSONTyped(json, false);
}

export function NEXUZR004OffersWarningMessageToJSONTyped(value?: NEXUZR004OffersWarningMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'warningDescription': value['warningDescription'],
    };
}

