/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR004OffersCategory } from './NEXUZR004OffersCategory';
import {
    NEXUZR004OffersCategoryFromJSON,
    NEXUZR004OffersCategoryFromJSONTyped,
    NEXUZR004OffersCategoryToJSON,
    NEXUZR004OffersCategoryToJSONTyped,
} from './NEXUZR004OffersCategory';

/**
 * Information about a specific passenger type within a bundle, including the type, quantity, and associated services.
 * @export
 * @interface NEXUZR004OffersPassengerType
 */
export interface NEXUZR004OffersPassengerType {
    /**
     * Type of the passenger.
     * @type {string}
     * @memberof NEXUZR004OffersPassengerType
     */
    type: string;
    /**
     * Total amount for the passenger type within the bundle.
     * @type {number}
     * @memberof NEXUZR004OffersPassengerType
     */
    amount: number;
    /**
     * Quantity of the passenger type within the bundle.
     * @type {number}
     * @memberof NEXUZR004OffersPassengerType
     */
    bundleQuantity: number;
    /**
     * Actual quantity of the passenger type which is determined based on count of each service for the passenger type in the bundle.
     * @type {number}
     * @memberof NEXUZR004OffersPassengerType
     */
    actualQuantity: number;
    /**
     * id representing categoryId of bundle.
     * @type {number}
     * @memberof NEXUZR004OffersPassengerType
     */
    categoryId: number;
    /**
     * id representing service id of bundle.
     * @type {number}
     * @memberof NEXUZR004OffersPassengerType
     */
    serviceId: number;
    /**
     * id representing representing cutoffHours of bundle
     * @type {number}
     * @memberof NEXUZR004OffersPassengerType
     */
    cutoffHours: number;
    /**
     * List of service categories and their associated services for the passenger type within the bundle.
     * @type {Array<NEXUZR004OffersCategory>}
     * @memberof NEXUZR004OffersPassengerType
     */
    categories: Array<NEXUZR004OffersCategory>;
}

/**
 * Check if a given object implements the NEXUZR004OffersPassengerType interface.
 */
export function instanceOfNEXUZR004OffersPassengerType(value: object): value is NEXUZR004OffersPassengerType {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('bundleQuantity' in value) || value['bundleQuantity'] === undefined) return false;
    if (!('actualQuantity' in value) || value['actualQuantity'] === undefined) return false;
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    if (!('serviceId' in value) || value['serviceId'] === undefined) return false;
    if (!('cutoffHours' in value) || value['cutoffHours'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersPassengerTypeFromJSON(json: any): NEXUZR004OffersPassengerType {
    return NEXUZR004OffersPassengerTypeFromJSONTyped(json, false);
}

export function NEXUZR004OffersPassengerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersPassengerType {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'amount': json['amount'],
        'bundleQuantity': json['bundleQuantity'],
        'actualQuantity': json['actualQuantity'],
        'categoryId': json['categoryId'],
        'serviceId': json['serviceId'],
        'cutoffHours': json['cutoffHours'],
        'categories': ((json['categories'] as Array<any>).map(NEXUZR004OffersCategoryFromJSON)),
    };
}

export function NEXUZR004OffersPassengerTypeToJSON(json: any): NEXUZR004OffersPassengerType {
    return NEXUZR004OffersPassengerTypeToJSONTyped(json, false);
}

export function NEXUZR004OffersPassengerTypeToJSONTyped(value?: NEXUZR004OffersPassengerType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'amount': value['amount'],
        'bundleQuantity': value['bundleQuantity'],
        'actualQuantity': value['actualQuantity'],
        'categoryId': value['categoryId'],
        'serviceId': value['serviceId'],
        'cutoffHours': value['cutoffHours'],
        'categories': ((value['categories'] as Array<any>).map(NEXUZR004OffersCategoryToJSON)),
    };
}

