/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR007OrderManagementTicket } from './NEXUZR007OrderManagementTicket';
import {
    NEXUZR007OrderManagementTicketFromJSON,
    NEXUZR007OrderManagementTicketFromJSONTyped,
    NEXUZR007OrderManagementTicketToJSON,
    NEXUZR007OrderManagementTicketToJSONTyped,
} from './NEXUZR007OrderManagementTicket';
import type { NEXUZR007OrderManagementAirlineInfo } from './NEXUZR007OrderManagementAirlineInfo';
import {
    NEXUZR007OrderManagementAirlineInfoFromJSON,
    NEXUZR007OrderManagementAirlineInfoFromJSONTyped,
    NEXUZR007OrderManagementAirlineInfoToJSON,
    NEXUZR007OrderManagementAirlineInfoToJSONTyped,
} from './NEXUZR007OrderManagementAirlineInfo';
import type { NEXUZR007OrderManagementCapture } from './NEXUZR007OrderManagementCapture';
import {
    NEXUZR007OrderManagementCaptureFromJSON,
    NEXUZR007OrderManagementCaptureFromJSONTyped,
    NEXUZR007OrderManagementCaptureToJSON,
    NEXUZR007OrderManagementCaptureToJSONTyped,
} from './NEXUZR007OrderManagementCapture';
import type { NEXUZR007OrderManagementAgent } from './NEXUZR007OrderManagementAgent';
import {
    NEXUZR007OrderManagementAgentFromJSON,
    NEXUZR007OrderManagementAgentFromJSONTyped,
    NEXUZR007OrderManagementAgentToJSON,
    NEXUZR007OrderManagementAgentToJSONTyped,
} from './NEXUZR007OrderManagementAgent';
import type { NEXUZR007OrderManagementFlight } from './NEXUZR007OrderManagementFlight';
import {
    NEXUZR007OrderManagementFlightFromJSON,
    NEXUZR007OrderManagementFlightFromJSONTyped,
    NEXUZR007OrderManagementFlightToJSON,
    NEXUZR007OrderManagementFlightToJSONTyped,
} from './NEXUZR007OrderManagementFlight';
import type { NEXUZR007OrderManagementIssuer } from './NEXUZR007OrderManagementIssuer';
import {
    NEXUZR007OrderManagementIssuerFromJSON,
    NEXUZR007OrderManagementIssuerFromJSONTyped,
    NEXUZR007OrderManagementIssuerToJSON,
    NEXUZR007OrderManagementIssuerToJSONTyped,
} from './NEXUZR007OrderManagementIssuer';
import type { NEXUZR007OrderManagementPassenger } from './NEXUZR007OrderManagementPassenger';
import {
    NEXUZR007OrderManagementPassengerFromJSON,
    NEXUZR007OrderManagementPassengerFromJSONTyped,
    NEXUZR007OrderManagementPassengerToJSON,
    NEXUZR007OrderManagementPassengerToJSONTyped,
} from './NEXUZR007OrderManagementPassenger';

/**
 * 
 * @export
 * @interface NEXUZR007OrderManagementPnrData
 */
export interface NEXUZR007OrderManagementPnrData {
    /**
     * 
     * @type {NEXUZR007OrderManagementAirlineInfo}
     * @memberof NEXUZR007OrderManagementPnrData
     */
    airlineInfo: NEXUZR007OrderManagementAirlineInfo;
    /**
     * 
     * @type {NEXUZR007OrderManagementPassenger}
     * @memberof NEXUZR007OrderManagementPnrData
     */
    passenger: NEXUZR007OrderManagementPassenger;
    /**
     * 
     * @type {NEXUZR007OrderManagementTicket}
     * @memberof NEXUZR007OrderManagementPnrData
     */
    ticket: NEXUZR007OrderManagementTicket;
    /**
     * 
     * @type {NEXUZR007OrderManagementIssuer}
     * @memberof NEXUZR007OrderManagementPnrData
     */
    issuer: NEXUZR007OrderManagementIssuer;
    /**
     * Flight detail present in the reservation.
     * @type {Array<NEXUZR007OrderManagementFlight>}
     * @memberof NEXUZR007OrderManagementPnrData
     */
    flight: Array<NEXUZR007OrderManagementFlight>;
    /**
     * Invoice Number.
     * @type {string}
     * @memberof NEXUZR007OrderManagementPnrData
     */
    invoiceNumber: string;
    /**
     * 
     * @type {NEXUZR007OrderManagementAgent}
     * @memberof NEXUZR007OrderManagementPnrData
     */
    agent: NEXUZR007OrderManagementAgent;
    /**
     * 
     * @type {NEXUZR007OrderManagementCapture}
     * @memberof NEXUZR007OrderManagementPnrData
     */
    capture: NEXUZR007OrderManagementCapture;
}

/**
 * Check if a given object implements the NEXUZR007OrderManagementPnrData interface.
 */
export function instanceOfNEXUZR007OrderManagementPnrData(value: object): value is NEXUZR007OrderManagementPnrData {
    if (!('airlineInfo' in value) || value['airlineInfo'] === undefined) return false;
    if (!('passenger' in value) || value['passenger'] === undefined) return false;
    if (!('ticket' in value) || value['ticket'] === undefined) return false;
    if (!('issuer' in value) || value['issuer'] === undefined) return false;
    if (!('flight' in value) || value['flight'] === undefined) return false;
    if (!('invoiceNumber' in value) || value['invoiceNumber'] === undefined) return false;
    if (!('agent' in value) || value['agent'] === undefined) return false;
    if (!('capture' in value) || value['capture'] === undefined) return false;
    return true;
}

export function NEXUZR007OrderManagementPnrDataFromJSON(json: any): NEXUZR007OrderManagementPnrData {
    return NEXUZR007OrderManagementPnrDataFromJSONTyped(json, false);
}

export function NEXUZR007OrderManagementPnrDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR007OrderManagementPnrData {
    if (json == null) {
        return json;
    }
    return {
        
        'airlineInfo': NEXUZR007OrderManagementAirlineInfoFromJSON(json['airlineInfo']),
        'passenger': NEXUZR007OrderManagementPassengerFromJSON(json['passenger']),
        'ticket': NEXUZR007OrderManagementTicketFromJSON(json['ticket']),
        'issuer': NEXUZR007OrderManagementIssuerFromJSON(json['issuer']),
        'flight': ((json['flight'] as Array<any>).map(NEXUZR007OrderManagementFlightFromJSON)),
        'invoiceNumber': json['invoiceNumber'],
        'agent': NEXUZR007OrderManagementAgentFromJSON(json['agent']),
        'capture': NEXUZR007OrderManagementCaptureFromJSON(json['capture']),
    };
}

export function NEXUZR007OrderManagementPnrDataToJSON(json: any): NEXUZR007OrderManagementPnrData {
    return NEXUZR007OrderManagementPnrDataToJSONTyped(json, false);
}

export function NEXUZR007OrderManagementPnrDataToJSONTyped(value?: NEXUZR007OrderManagementPnrData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'airlineInfo': NEXUZR007OrderManagementAirlineInfoToJSON(value['airlineInfo']),
        'passenger': NEXUZR007OrderManagementPassengerToJSON(value['passenger']),
        'ticket': NEXUZR007OrderManagementTicketToJSON(value['ticket']),
        'issuer': NEXUZR007OrderManagementIssuerToJSON(value['issuer']),
        'flight': ((value['flight'] as Array<any>).map(NEXUZR007OrderManagementFlightToJSON)),
        'invoiceNumber': value['invoiceNumber'],
        'agent': NEXUZR007OrderManagementAgentToJSON(value['agent']),
        'capture': NEXUZR007OrderManagementCaptureToJSON(value['capture']),
    };
}

