/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Standard warning returned when the API encounters partial failures.
 * @export
 * @interface NEXUZR006PaymentWarningItem
 */
export interface NEXUZR006PaymentWarningItem {
    /**
     * Custom warning code.
     * @type {string}
     * @memberof NEXUZR006PaymentWarningItem
     */
    code: string;
    /**
     * Warning description.
     * @type {string}
     * @memberof NEXUZR006PaymentWarningItem
     */
    description: string;
}

/**
 * Check if a given object implements the NEXUZR006PaymentWarningItem interface.
 */
export function instanceOfNEXUZR006PaymentWarningItem(value: object): value is NEXUZR006PaymentWarningItem {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function NEXUZR006PaymentWarningItemFromJSON(json: any): NEXUZR006PaymentWarningItem {
    return NEXUZR006PaymentWarningItemFromJSONTyped(json, false);
}

export function NEXUZR006PaymentWarningItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR006PaymentWarningItem {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
    };
}

export function NEXUZR006PaymentWarningItemToJSON(json: any): NEXUZR006PaymentWarningItem {
    return NEXUZR006PaymentWarningItemToJSONTyped(json, false);
}

export function NEXUZR006PaymentWarningItemToJSONTyped(value?: NEXUZR006PaymentWarningItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
    };
}

