/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Standard error response body returned when the API fails.
 * @export
 * @interface NEXUZR004OffersErrorResponse
 */
export interface NEXUZR004OffersErrorResponse {
    /**
     * Application-specific error code.
     * @type {string}
     * @memberof NEXUZR004OffersErrorResponse
     */
    code: string;
    /**
     * Human-readable explanation of the error.
     * @type {string}
     * @memberof NEXUZR004OffersErrorResponse
     */
    description: string;
}

/**
 * Check if a given object implements the NEXUZR004OffersErrorResponse interface.
 */
export function instanceOfNEXUZR004OffersErrorResponse(value: object): value is NEXUZR004OffersErrorResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersErrorResponseFromJSON(json: any): NEXUZR004OffersErrorResponse {
    return NEXUZR004OffersErrorResponseFromJSONTyped(json, false);
}

export function NEXUZR004OffersErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
    };
}

export function NEXUZR004OffersErrorResponseToJSON(json: any): NEXUZR004OffersErrorResponse {
    return NEXUZR004OffersErrorResponseToJSONTyped(json, false);
}

export function NEXUZR004OffersErrorResponseToJSONTyped(value?: NEXUZR004OffersErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
    };
}

