/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR001CoreTokenData } from './NEXUZR001CoreTokenData';
import {
    NEXUZR001CoreTokenDataFromJSON,
    NEXUZR001CoreTokenDataFromJSONTyped,
    NEXUZR001CoreTokenDataToJSON,
    NEXUZR001CoreTokenDataToJSONTyped,
} from './NEXUZR001CoreTokenData';

/**
 * 
 * @export
 * @interface NEXUZR001CoreToken
 */
export interface NEXUZR001CoreToken {
    /**
     * 
     * @type {NEXUZR001CoreTokenData}
     * @memberof NEXUZR001CoreToken
     */
    data: NEXUZR001CoreTokenData;
}

/**
 * Check if a given object implements the NEXUZR001CoreToken interface.
 */
export function instanceOfNEXUZR001CoreToken(value: object): value is NEXUZR001CoreToken {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function NEXUZR001CoreTokenFromJSON(json: any): NEXUZR001CoreToken {
    return NEXUZR001CoreTokenFromJSONTyped(json, false);
}

export function NEXUZR001CoreTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR001CoreToken {
    if (json == null) {
        return json;
    }
    return {
        
        'data': NEXUZR001CoreTokenDataFromJSON(json['data']),
    };
}

export function NEXUZR001CoreTokenToJSON(json: any): NEXUZR001CoreToken {
    return NEXUZR001CoreTokenToJSONTyped(json, false);
}

export function NEXUZR001CoreTokenToJSONTyped(value?: NEXUZR001CoreToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': NEXUZR001CoreTokenDataToJSON(value['data']),
    };
}

