/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR005APIsWarningMessage } from './NEXUZR005APIsWarningMessage';
import {
    NEXUZR005APIsWarningMessageFromJSON,
    NEXUZR005APIsWarningMessageFromJSONTyped,
    NEXUZR005APIsWarningMessageToJSON,
    NEXUZR005APIsWarningMessageToJSONTyped,
} from './NEXUZR005APIsWarningMessage';
import type { NEXUZR005APIsOrderData } from './NEXUZR005APIsOrderData';
import {
    NEXUZR005APIsOrderDataFromJSON,
    NEXUZR005APIsOrderDataFromJSONTyped,
    NEXUZR005APIsOrderDataToJSON,
    NEXUZR005APIsOrderDataToJSONTyped,
} from './NEXUZR005APIsOrderData';

/**
 * 
 * @export
 * @interface NEXUZR005APIsCreateOrderResponse
 */
export interface NEXUZR005APIsCreateOrderResponse {
    /**
     * Array of warning messages
     * @type {Array<NEXUZR005APIsWarningMessage>}
     * @memberof NEXUZR005APIsCreateOrderResponse
     */
    warnings?: Array<NEXUZR005APIsWarningMessage>;
    /**
     * 
     * @type {NEXUZR005APIsOrderData}
     * @memberof NEXUZR005APIsCreateOrderResponse
     */
    data: NEXUZR005APIsOrderData;
}

/**
 * Check if a given object implements the NEXUZR005APIsCreateOrderResponse interface.
 */
export function instanceOfNEXUZR005APIsCreateOrderResponse(value: object): value is NEXUZR005APIsCreateOrderResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsCreateOrderResponseFromJSON(json: any): NEXUZR005APIsCreateOrderResponse {
    return NEXUZR005APIsCreateOrderResponseFromJSONTyped(json, false);
}

export function NEXUZR005APIsCreateOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsCreateOrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'warnings': json['warnings'] == null ? undefined : ((json['warnings'] as Array<any>).map(NEXUZR005APIsWarningMessageFromJSON)),
        'data': NEXUZR005APIsOrderDataFromJSON(json['data']),
    };
}

export function NEXUZR005APIsCreateOrderResponseToJSON(json: any): NEXUZR005APIsCreateOrderResponse {
    return NEXUZR005APIsCreateOrderResponseToJSONTyped(json, false);
}

export function NEXUZR005APIsCreateOrderResponseToJSONTyped(value?: NEXUZR005APIsCreateOrderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'warnings': value['warnings'] == null ? undefined : ((value['warnings'] as Array<any>).map(NEXUZR005APIsWarningMessageToJSON)),
        'data': NEXUZR005APIsOrderDataToJSON(value['data']),
    };
}

