/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR004OffersSpecialService
 */
export interface NEXUZR004OffersSpecialService {
    /**
     * Logical flight ID.
     * @type {number}
     * @memberof NEXUZR004OffersSpecialService
     */
    lfid: number;
    /**
     * Amount of the special service.
     * @type {number}
     * @memberof NEXUZR004OffersSpecialService
     */
    amount: number;
    /**
     * Currency of the amount.
     * @type {string}
     * @memberof NEXUZR004OffersSpecialService
     */
    currency: string;
    /**
     * Time limit (hrs) to purchase the special service before flight departure.
     * @type {number}
     * @memberof NEXUZR004OffersSpecialService
     */
    cutOffHours: number;
    /**
     * Description of the special service.
     * @type {string}
     * @memberof NEXUZR004OffersSpecialService
     */
    description: string;
    /**
     * Maximum available quantity of the special service.
     * @type {number}
     * @memberof NEXUZR004OffersSpecialService
     */
    maxCountServiceLevel: number;
    /**
     * Current available quantity of the special service.
     * @type {number}
     * @memberof NEXUZR004OffersSpecialService
     */
    qtyAvailable: number;
    /**
     * SSR code of the special service.
     * @type {string}
     * @memberof NEXUZR004OffersSpecialService
     */
    ssrCode: string;
    /**
     * SSR ID of the special service.
     * @type {number}
     * @memberof NEXUZR004OffersSpecialService
     */
    ssrId: number;
    /**
     * Number of days until sales start.
     * @type {number}
     * @memberof NEXUZR004OffersSpecialService
     */
    startSalesDays: number;
    /**
     * Physical flight ID.
     * @type {number}
     * @memberof NEXUZR004OffersSpecialService
     */
    pfid?: number;
}

/**
 * Check if a given object implements the NEXUZR004OffersSpecialService interface.
 */
export function instanceOfNEXUZR004OffersSpecialService(value: object): value is NEXUZR004OffersSpecialService {
    if (!('lfid' in value) || value['lfid'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('cutOffHours' in value) || value['cutOffHours'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('maxCountServiceLevel' in value) || value['maxCountServiceLevel'] === undefined) return false;
    if (!('qtyAvailable' in value) || value['qtyAvailable'] === undefined) return false;
    if (!('ssrCode' in value) || value['ssrCode'] === undefined) return false;
    if (!('ssrId' in value) || value['ssrId'] === undefined) return false;
    if (!('startSalesDays' in value) || value['startSalesDays'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersSpecialServiceFromJSON(json: any): NEXUZR004OffersSpecialService {
    return NEXUZR004OffersSpecialServiceFromJSONTyped(json, false);
}

export function NEXUZR004OffersSpecialServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersSpecialService {
    if (json == null) {
        return json;
    }
    return {
        
        'lfid': json['lfid'],
        'amount': json['amount'],
        'currency': json['currency'],
        'cutOffHours': json['cutOffHours'],
        'description': json['description'],
        'maxCountServiceLevel': json['maxCountServiceLevel'],
        'qtyAvailable': json['qtyAvailable'],
        'ssrCode': json['ssrCode'],
        'ssrId': json['ssrId'],
        'startSalesDays': json['startSalesDays'],
        'pfid': json['pfid'] == null ? undefined : json['pfid'],
    };
}

export function NEXUZR004OffersSpecialServiceToJSON(json: any): NEXUZR004OffersSpecialService {
    return NEXUZR004OffersSpecialServiceToJSONTyped(json, false);
}

export function NEXUZR004OffersSpecialServiceToJSONTyped(value?: NEXUZR004OffersSpecialService | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lfid': value['lfid'],
        'amount': value['amount'],
        'currency': value['currency'],
        'cutOffHours': value['cutOffHours'],
        'description': value['description'],
        'maxCountServiceLevel': value['maxCountServiceLevel'],
        'qtyAvailable': value['qtyAvailable'],
        'ssrCode': value['ssrCode'],
        'ssrId': value['ssrId'],
        'startSalesDays': value['startSalesDays'],
        'pfid': value['pfid'],
    };
}

