/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR007OrderManagementAirlineInfo
 */
export interface NEXUZR007OrderManagementAirlineInfo {
    /**
     * Carrier code of the airline.
     * @type {string}
     * @memberof NEXUZR007OrderManagementAirlineInfo
     */
    code: string;
    /**
     * Name of the Airline.
     * @type {string}
     * @memberof NEXUZR007OrderManagementAirlineInfo
     */
    airline: string;
}

/**
 * Check if a given object implements the NEXUZR007OrderManagementAirlineInfo interface.
 */
export function instanceOfNEXUZR007OrderManagementAirlineInfo(value: object): value is NEXUZR007OrderManagementAirlineInfo {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('airline' in value) || value['airline'] === undefined) return false;
    return true;
}

export function NEXUZR007OrderManagementAirlineInfoFromJSON(json: any): NEXUZR007OrderManagementAirlineInfo {
    return NEXUZR007OrderManagementAirlineInfoFromJSONTyped(json, false);
}

export function NEXUZR007OrderManagementAirlineInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR007OrderManagementAirlineInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'airline': json['airline'],
    };
}

export function NEXUZR007OrderManagementAirlineInfoToJSON(json: any): NEXUZR007OrderManagementAirlineInfo {
    return NEXUZR007OrderManagementAirlineInfoToJSONTyped(json, false);
}

export function NEXUZR007OrderManagementAirlineInfoToJSONTyped(value?: NEXUZR007OrderManagementAirlineInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'airline': value['airline'],
    };
}

