/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR004OffersSegmentWiseBundle } from './NEXUZR004OffersSegmentWiseBundle';
import {
    NEXUZR004OffersSegmentWiseBundleFromJSON,
    NEXUZR004OffersSegmentWiseBundleFromJSONTyped,
    NEXUZR004OffersSegmentWiseBundleToJSON,
    NEXUZR004OffersSegmentWiseBundleToJSONTyped,
} from './NEXUZR004OffersSegmentWiseBundle';

/**
 * 
 * @export
 * @interface NEXUZR004OffersBundleResponse
 */
export interface NEXUZR004OffersBundleResponse {
    /**
     * Bundle information organized by flight segments.
     * @type {Array<NEXUZR004OffersSegmentWiseBundle>}
     * @memberof NEXUZR004OffersBundleResponse
     */
    data: Array<NEXUZR004OffersSegmentWiseBundle>;
}

/**
 * Check if a given object implements the NEXUZR004OffersBundleResponse interface.
 */
export function instanceOfNEXUZR004OffersBundleResponse(value: object): value is NEXUZR004OffersBundleResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersBundleResponseFromJSON(json: any): NEXUZR004OffersBundleResponse {
    return NEXUZR004OffersBundleResponseFromJSONTyped(json, false);
}

export function NEXUZR004OffersBundleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersBundleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(NEXUZR004OffersSegmentWiseBundleFromJSON)),
    };
}

export function NEXUZR004OffersBundleResponseToJSON(json: any): NEXUZR004OffersBundleResponse {
    return NEXUZR004OffersBundleResponseToJSONTyped(json, false);
}

export function NEXUZR004OffersBundleResponseToJSONTyped(value?: NEXUZR004OffersBundleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(NEXUZR004OffersSegmentWiseBundleToJSON)),
    };
}

