/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR007OrderManagementPnrData } from './NEXUZR007OrderManagementPnrData';
import {
    NEXUZR007OrderManagementPnrDataFromJSON,
    NEXUZR007OrderManagementPnrDataFromJSONTyped,
    NEXUZR007OrderManagementPnrDataToJSON,
    NEXUZR007OrderManagementPnrDataToJSONTyped,
} from './NEXUZR007OrderManagementPnrData';

/**
 * Response body containing PNR details.
 * @export
 * @interface NEXUZR007OrderManagementPnrInfoResponse
 */
export interface NEXUZR007OrderManagementPnrInfoResponse {
    /**
     * 
     * @type {NEXUZR007OrderManagementPnrData}
     * @memberof NEXUZR007OrderManagementPnrInfoResponse
     */
    data: NEXUZR007OrderManagementPnrData;
}

/**
 * Check if a given object implements the NEXUZR007OrderManagementPnrInfoResponse interface.
 */
export function instanceOfNEXUZR007OrderManagementPnrInfoResponse(value: object): value is NEXUZR007OrderManagementPnrInfoResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function NEXUZR007OrderManagementPnrInfoResponseFromJSON(json: any): NEXUZR007OrderManagementPnrInfoResponse {
    return NEXUZR007OrderManagementPnrInfoResponseFromJSONTyped(json, false);
}

export function NEXUZR007OrderManagementPnrInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR007OrderManagementPnrInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': NEXUZR007OrderManagementPnrDataFromJSON(json['data']),
    };
}

export function NEXUZR007OrderManagementPnrInfoResponseToJSON(json: any): NEXUZR007OrderManagementPnrInfoResponse {
    return NEXUZR007OrderManagementPnrInfoResponseToJSONTyped(json, false);
}

export function NEXUZR007OrderManagementPnrInfoResponseToJSONTyped(value?: NEXUZR007OrderManagementPnrInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': NEXUZR007OrderManagementPnrDataToJSON(value['data']),
    };
}

