/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR007OrderManagementDateParts
 */
export interface NEXUZR007OrderManagementDateParts {
    /**
     * 
     * @type {number}
     * @memberof NEXUZR007OrderManagementDateParts
     */
    dayOfMonth: number;
    /**
     * 
     * @type {number}
     * @memberof NEXUZR007OrderManagementDateParts
     */
    month: number;
    /**
     * 
     * @type {number}
     * @memberof NEXUZR007OrderManagementDateParts
     */
    year: number;
}

/**
 * Check if a given object implements the NEXUZR007OrderManagementDateParts interface.
 */
export function instanceOfNEXUZR007OrderManagementDateParts(value: object): value is NEXUZR007OrderManagementDateParts {
    if (!('dayOfMonth' in value) || value['dayOfMonth'] === undefined) return false;
    if (!('month' in value) || value['month'] === undefined) return false;
    if (!('year' in value) || value['year'] === undefined) return false;
    return true;
}

export function NEXUZR007OrderManagementDatePartsFromJSON(json: any): NEXUZR007OrderManagementDateParts {
    return NEXUZR007OrderManagementDatePartsFromJSONTyped(json, false);
}

export function NEXUZR007OrderManagementDatePartsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR007OrderManagementDateParts {
    if (json == null) {
        return json;
    }
    return {
        
        'dayOfMonth': json['dayOfMonth'],
        'month': json['month'],
        'year': json['year'],
    };
}

export function NEXUZR007OrderManagementDatePartsToJSON(json: any): NEXUZR007OrderManagementDateParts {
    return NEXUZR007OrderManagementDatePartsToJSONTyped(json, false);
}

export function NEXUZR007OrderManagementDatePartsToJSONTyped(value?: NEXUZR007OrderManagementDateParts | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dayOfMonth': value['dayOfMonth'],
        'month': value['month'],
        'year': value['year'],
    };
}

