/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR005APIsFareDetails
 */
export interface NEXUZR005APIsFareDetails {
    /**
     * Numeric fare identifier.
     * @type {number}
     * @memberof NEXUZR005APIsFareDetails
     */
    fareId: number;
    /**
     * Single alphabetic character representing fare class.
     * @type {string}
     * @memberof NEXUZR005APIsFareDetails
     */
    fareClass: string;
    /**
     * Alphanumeric fare basis code.
     * @type {string}
     * @memberof NEXUZR005APIsFareDetails
     */
    fareBasisCode: string;
    /**
     * Passenger type in fare details.
     * @type {string}
     * @memberof NEXUZR005APIsFareDetails
     */
    passengerType: string;
    /**
     * Base fare amount including tax.
     * @type {number}
     * @memberof NEXUZR005APIsFareDetails
     */
    baseFareAmtInclTax: number;
    /**
     * Amount including tax.
     * @type {number}
     * @memberof NEXUZR005APIsFareDetails
     */
    amtInclTax: number;
}

/**
 * Check if a given object implements the NEXUZR005APIsFareDetails interface.
 */
export function instanceOfNEXUZR005APIsFareDetails(value: object): value is NEXUZR005APIsFareDetails {
    if (!('fareId' in value) || value['fareId'] === undefined) return false;
    if (!('fareClass' in value) || value['fareClass'] === undefined) return false;
    if (!('fareBasisCode' in value) || value['fareBasisCode'] === undefined) return false;
    if (!('passengerType' in value) || value['passengerType'] === undefined) return false;
    if (!('baseFareAmtInclTax' in value) || value['baseFareAmtInclTax'] === undefined) return false;
    if (!('amtInclTax' in value) || value['amtInclTax'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsFareDetailsFromJSON(json: any): NEXUZR005APIsFareDetails {
    return NEXUZR005APIsFareDetailsFromJSONTyped(json, false);
}

export function NEXUZR005APIsFareDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsFareDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'fareId': json['fareId'],
        'fareClass': json['fareClass'],
        'fareBasisCode': json['fareBasisCode'],
        'passengerType': json['passengerType'],
        'baseFareAmtInclTax': json['baseFareAmtInclTax'],
        'amtInclTax': json['amtInclTax'],
    };
}

export function NEXUZR005APIsFareDetailsToJSON(json: any): NEXUZR005APIsFareDetails {
    return NEXUZR005APIsFareDetailsToJSONTyped(json, false);
}

export function NEXUZR005APIsFareDetailsToJSONTyped(value?: NEXUZR005APIsFareDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fareId': value['fareId'],
        'fareClass': value['fareClass'],
        'fareBasisCode': value['fareBasisCode'],
        'passengerType': value['passengerType'],
        'baseFareAmtInclTax': value['baseFareAmtInclTax'],
        'amtInclTax': value['amtInclTax'],
    };
}

