/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { NEXUZR006PaymentErrorResponse } from './NEXUZR006PaymentErrorResponse';
import {
    instanceOfNEXUZR006PaymentErrorResponse,
    NEXUZR006PaymentErrorResponseFromJSON,
    NEXUZR006PaymentErrorResponseFromJSONTyped,
    NEXUZR006PaymentErrorResponseToJSON,
} from './NEXUZR006PaymentErrorResponse';
import type { NEXUZR006PaymentPaymentStatusResponse } from './NEXUZR006PaymentPaymentStatusResponse';
import {
    instanceOfNEXUZR006PaymentPaymentStatusResponse,
    NEXUZR006PaymentPaymentStatusResponseFromJSON,
    NEXUZR006PaymentPaymentStatusResponseFromJSONTyped,
    NEXUZR006PaymentPaymentStatusResponseToJSON,
} from './NEXUZR006PaymentPaymentStatusResponse';

/**
 * @type RetrievePaymentStatus422Response
 * 
 * @export
 */
export type RetrievePaymentStatus422Response = NEXUZR006PaymentErrorResponse | NEXUZR006PaymentPaymentStatusResponse;

export function RetrievePaymentStatus422ResponseFromJSON(json: any): RetrievePaymentStatus422Response {
    return RetrievePaymentStatus422ResponseFromJSONTyped(json, false);
}

export function RetrievePaymentStatus422ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetrievePaymentStatus422Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfNEXUZR006PaymentErrorResponse(json)) {
        return NEXUZR006PaymentErrorResponseFromJSONTyped(json, true);
    }
    if (instanceOfNEXUZR006PaymentPaymentStatusResponse(json)) {
        return NEXUZR006PaymentPaymentStatusResponseFromJSONTyped(json, true);
    }
    return {} as any;
}

export function RetrievePaymentStatus422ResponseToJSON(json: any): any {
    return RetrievePaymentStatus422ResponseToJSONTyped(json, false);
}

export function RetrievePaymentStatus422ResponseToJSONTyped(value?: RetrievePaymentStatus422Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfNEXUZR006PaymentErrorResponse(value)) {
        return NEXUZR006PaymentErrorResponseToJSON(value as NEXUZR006PaymentErrorResponse);
    }
    if (instanceOfNEXUZR006PaymentPaymentStatusResponse(value)) {
        return NEXUZR006PaymentPaymentStatusResponseToJSON(value as NEXUZR006PaymentPaymentStatusResponse);
    }
    return {};
}

