/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type NEXUZR001CoreErrorResponse,
    NEXUZR001CoreErrorResponseFromJSON,
    NEXUZR001CoreErrorResponseToJSON,
} from '../models/NEXUZR001CoreErrorResponse';
import {
    type NEXUZR001CoreToken,
    NEXUZR001CoreTokenFromJSON,
    NEXUZR001CoreTokenToJSON,
} from '../models/NEXUZR001CoreToken';

/**
 * CoreApi - interface
 * 
 * @export
 * @interface CoreApiInterface
 */
export interface CoreApiInterface {
    /**
     * Creates request options for authTokenPost without sending the request
     * @throws {RequiredError}
     * @memberof CoreApiInterface
     */
    authTokenPostRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * Generates and returns a security token.
     * @summary Retrieve security token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoreApiInterface
     */
    authTokenPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR001CoreToken>>;

    /**
     * Generates and returns a security token.
     * Retrieve security token
     */
    authTokenPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR001CoreToken>;

}

/**
 * 
 */
export class CoreApi extends runtime.BaseAPI implements CoreApiInterface {

    /**
     * Creates request options for authTokenPost without sending the request
     */
    async authTokenPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/token`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Generates and returns a security token.
     * Retrieve security token
     */
    async authTokenPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR001CoreToken>> {
        const requestOptions = await this.authTokenPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NEXUZR001CoreTokenFromJSON(jsonValue));
    }

    /**
     * Generates and returns a security token.
     * Retrieve security token
     */
    async authTokenPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR001CoreToken> {
        const response = await this.authTokenPostRaw(initOverrides);
        return await response.value();
    }

}
