/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type NEXUZR005APIsCreateOrderRequest,
    NEXUZR005APIsCreateOrderRequestFromJSON,
    NEXUZR005APIsCreateOrderRequestToJSON,
} from '../models/NEXUZR005APIsCreateOrderRequest';
import {
    type NEXUZR005APIsCreateOrderResponse,
    NEXUZR005APIsCreateOrderResponseFromJSON,
    NEXUZR005APIsCreateOrderResponseToJSON,
} from '../models/NEXUZR005APIsCreateOrderResponse';
import {
    type NEXUZR005APIsErrorResponse,
    NEXUZR005APIsErrorResponseFromJSON,
    NEXUZR005APIsErrorResponseToJSON,
} from '../models/NEXUZR005APIsErrorResponse';

export interface CreateOrderRequest {
    currency: string;
    language: string;
    nEXUZR005APIsCreateOrderRequest: NEXUZR005APIsCreateOrderRequest;
}

/**
 * CreateOrderApi - interface
 * 
 * @export
 * @interface CreateOrderApiInterface
 */
export interface CreateOrderApiInterface {
    /**
     * Creates request options for createOrder without sending the request
     * @param {string} currency Represents the reservation currency.
     * @param {string} language Represents the reservation language.
     * @param {NEXUZR005APIsCreateOrderRequest} nEXUZR005APIsCreateOrderRequest Request payload containing the arkose token, passengers, and recipient information.
     * @throws {RequiredError}
     * @memberof CreateOrderApiInterface
     */
    createOrderRequestOpts(requestParameters: CreateOrderRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create Order
     * @param {string} currency Represents the reservation currency.
     * @param {string} language Represents the reservation language.
     * @param {NEXUZR005APIsCreateOrderRequest} nEXUZR005APIsCreateOrderRequest Request payload containing the arkose token, passengers, and recipient information.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CreateOrderApiInterface
     */
    createOrderRaw(requestParameters: CreateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR005APIsCreateOrderResponse>>;

    /**
     * Create Order
     */
    createOrder(requestParameters: CreateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR005APIsCreateOrderResponse>;

}

/**
 * 
 */
export class CreateOrderApi extends runtime.BaseAPI implements CreateOrderApiInterface {

    /**
     * Creates request options for createOrder without sending the request
     */
    async createOrderRequestOpts(requestParameters: CreateOrderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['currency'] == null) {
            throw new runtime.RequiredError(
                'currency',
                'Required parameter "currency" was null or undefined when calling createOrder().'
            );
        }

        if (requestParameters['language'] == null) {
            throw new runtime.RequiredError(
                'language',
                'Required parameter "language" was null or undefined when calling createOrder().'
            );
        }

        if (requestParameters['nEXUZR005APIsCreateOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'nEXUZR005APIsCreateOrderRequest',
                'Required parameter "nEXUZR005APIsCreateOrderRequest" was null or undefined when calling createOrder().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        if (requestParameters['language'] != null) {
            queryParameters['language'] = requestParameters['language'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/orders`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NEXUZR005APIsCreateOrderRequestToJSON(requestParameters['nEXUZR005APIsCreateOrderRequest']),
        };
    }

    /**
     * Create Order
     */
    async createOrderRaw(requestParameters: CreateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR005APIsCreateOrderResponse>> {
        const requestOptions = await this.createOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NEXUZR005APIsCreateOrderResponseFromJSON(jsonValue));
    }

    /**
     * Create Order
     */
    async createOrder(requestParameters: CreateOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR005APIsCreateOrderResponse> {
        const response = await this.createOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
