/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type NEXUZR004OffersBundleRequest,
    NEXUZR004OffersBundleRequestFromJSON,
    NEXUZR004OffersBundleRequestToJSON,
} from '../models/NEXUZR004OffersBundleRequest';
import {
    type NEXUZR004OffersBundleResponse,
    NEXUZR004OffersBundleResponseFromJSON,
    NEXUZR004OffersBundleResponseToJSON,
} from '../models/NEXUZR004OffersBundleResponse';
import {
    type NEXUZR004OffersErrorResponse,
    NEXUZR004OffersErrorResponseFromJSON,
    NEXUZR004OffersErrorResponseToJSON,
} from '../models/NEXUZR004OffersErrorResponse';

export interface RetrieveOfferBundlesRequest {
    currency: string;
    nEXUZR004OffersBundleRequest: NEXUZR004OffersBundleRequest;
}

/**
 * OffersApi - interface
 * 
 * @export
 * @interface OffersApiInterface
 */
export interface OffersApiInterface {
    /**
     * Creates request options for retrieveOfferBundles without sending the request
     * @param {string} currency 
     * @param {NEXUZR004OffersBundleRequest} nEXUZR004OffersBundleRequest Request payload containing route, passenger, and flight details.
     * @throws {RequiredError}
     * @memberof OffersApiInterface
     */
    retrieveOfferBundlesRequestOpts(requestParameters: RetrieveOfferBundlesRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns available service bundles (e.g., meals+baggage, etc.) for given flight segments and passenger composition.
     * @summary Retrieve bundles available for specified flight details
     * @param {string} currency 
     * @param {NEXUZR004OffersBundleRequest} nEXUZR004OffersBundleRequest Request payload containing route, passenger, and flight details.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OffersApiInterface
     */
    retrieveOfferBundlesRaw(requestParameters: RetrieveOfferBundlesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR004OffersBundleResponse>>;

    /**
     * Returns available service bundles (e.g., meals+baggage, etc.) for given flight segments and passenger composition.
     * Retrieve bundles available for specified flight details
     */
    retrieveOfferBundles(requestParameters: RetrieveOfferBundlesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR004OffersBundleResponse>;

}

/**
 * 
 */
export class OffersApi extends runtime.BaseAPI implements OffersApiInterface {

    /**
     * Creates request options for retrieveOfferBundles without sending the request
     */
    async retrieveOfferBundlesRequestOpts(requestParameters: RetrieveOfferBundlesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['currency'] == null) {
            throw new runtime.RequiredError(
                'currency',
                'Required parameter "currency" was null or undefined when calling retrieveOfferBundles().'
            );
        }

        if (requestParameters['nEXUZR004OffersBundleRequest'] == null) {
            throw new runtime.RequiredError(
                'nEXUZR004OffersBundleRequest',
                'Required parameter "nEXUZR004OffersBundleRequest" was null or undefined when calling retrieveOfferBundles().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['currency'] != null) {
            queryParameters['currency'] = requestParameters['currency'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/offers/bundles`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NEXUZR004OffersBundleRequestToJSON(requestParameters['nEXUZR004OffersBundleRequest']),
        };
    }

    /**
     * Returns available service bundles (e.g., meals+baggage, etc.) for given flight segments and passenger composition.
     * Retrieve bundles available for specified flight details
     */
    async retrieveOfferBundlesRaw(requestParameters: RetrieveOfferBundlesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR004OffersBundleResponse>> {
        const requestOptions = await this.retrieveOfferBundlesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NEXUZR004OffersBundleResponseFromJSON(jsonValue));
    }

    /**
     * Returns available service bundles (e.g., meals+baggage, etc.) for given flight segments and passenger composition.
     * Retrieve bundles available for specified flight details
     */
    async retrieveOfferBundles(requestParameters: RetrieveOfferBundlesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR004OffersBundleResponse> {
        const response = await this.retrieveOfferBundlesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
