/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type NEXUZR007OrderManagementErrorResponse,
    NEXUZR007OrderManagementErrorResponseFromJSON,
    NEXUZR007OrderManagementErrorResponseToJSON,
} from '../models/NEXUZR007OrderManagementErrorResponse';
import {
    type NEXUZR007OrderManagementPnrInfoRequest,
    NEXUZR007OrderManagementPnrInfoRequestFromJSON,
    NEXUZR007OrderManagementPnrInfoRequestToJSON,
} from '../models/NEXUZR007OrderManagementPnrInfoRequest';
import {
    type NEXUZR007OrderManagementPnrInfoResponse,
    NEXUZR007OrderManagementPnrInfoResponseFromJSON,
    NEXUZR007OrderManagementPnrInfoResponseToJSON,
} from '../models/NEXUZR007OrderManagementPnrInfoResponse';

export interface RetrievePnrInfoRequest {
    nEXUZR007OrderManagementPnrInfoRequest: NEXUZR007OrderManagementPnrInfoRequest;
}

/**
 * RetrievePNRApi - interface
 * 
 * @export
 * @interface RetrievePNRApiInterface
 */
export interface RetrievePNRApiInterface {
    /**
     * Creates request options for retrievePnrInfo without sending the request
     * @param {NEXUZR007OrderManagementPnrInfoRequest} nEXUZR007OrderManagementPnrInfoRequest Request body containing the confirmationNumber detail.
     * @throws {RequiredError}
     * @memberof RetrievePNRApiInterface
     */
    retrievePnrInfoRequestOpts(requestParameters: RetrievePnrInfoRequest): Promise<runtime.RequestOpts>;

    /**
     * Returns flight, passenger, ticket and related information for the specified PNR.
     * @summary Retrieve PNR information for specified confirmation number.
     * @param {NEXUZR007OrderManagementPnrInfoRequest} nEXUZR007OrderManagementPnrInfoRequest Request body containing the confirmationNumber detail.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RetrievePNRApiInterface
     */
    retrievePnrInfoRaw(requestParameters: RetrievePnrInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR007OrderManagementPnrInfoResponse>>;

    /**
     * Returns flight, passenger, ticket and related information for the specified PNR.
     * Retrieve PNR information for specified confirmation number.
     */
    retrievePnrInfo(requestParameters: RetrievePnrInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR007OrderManagementPnrInfoResponse>;

}

/**
 * 
 */
export class RetrievePNRApi extends runtime.BaseAPI implements RetrievePNRApiInterface {

    /**
     * Creates request options for retrievePnrInfo without sending the request
     */
    async retrievePnrInfoRequestOpts(requestParameters: RetrievePnrInfoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['nEXUZR007OrderManagementPnrInfoRequest'] == null) {
            throw new runtime.RequiredError(
                'nEXUZR007OrderManagementPnrInfoRequest',
                'Required parameter "nEXUZR007OrderManagementPnrInfoRequest" was null or undefined when calling retrievePnrInfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/orders/info`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NEXUZR007OrderManagementPnrInfoRequestToJSON(requestParameters['nEXUZR007OrderManagementPnrInfoRequest']),
        };
    }

    /**
     * Returns flight, passenger, ticket and related information for the specified PNR.
     * Retrieve PNR information for specified confirmation number.
     */
    async retrievePnrInfoRaw(requestParameters: RetrievePnrInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR007OrderManagementPnrInfoResponse>> {
        const requestOptions = await this.retrievePnrInfoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NEXUZR007OrderManagementPnrInfoResponseFromJSON(jsonValue));
    }

    /**
     * Returns flight, passenger, ticket and related information for the specified PNR.
     * Retrieve PNR information for specified confirmation number.
     */
    async retrievePnrInfo(requestParameters: RetrievePnrInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR007OrderManagementPnrInfoResponse> {
        const response = await this.retrievePnrInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
