/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type NEXUZR004OffersErrorResponse,
    NEXUZR004OffersErrorResponseFromJSON,
    NEXUZR004OffersErrorResponseToJSON,
} from '../models/NEXUZR004OffersErrorResponse';
import {
    type NEXUZR004OffersFlightSeatMapResponse,
    NEXUZR004OffersFlightSeatMapResponseFromJSON,
    NEXUZR004OffersFlightSeatMapResponseToJSON,
} from '../models/NEXUZR004OffersFlightSeatMapResponse';
import {
    type NEXUZR004OffersSeatMapRequest,
    NEXUZR004OffersSeatMapRequestFromJSON,
    NEXUZR004OffersSeatMapRequestToJSON,
} from '../models/NEXUZR004OffersSeatMapRequest';

export interface RetrieveSeatMapRequest {
    nEXUZR004OffersSeatMapRequest: NEXUZR004OffersSeatMapRequest;
}

/**
 * SeatMapApi - interface
 * 
 * @export
 * @interface SeatMapApiInterface
 */
export interface SeatMapApiInterface {
    /**
     * Creates request options for retrieveSeatMap without sending the request
     * @param {NEXUZR004OffersSeatMapRequest} nEXUZR004OffersSeatMapRequest 
     * @throws {RequiredError}
     * @memberof SeatMapApiInterface
     */
    retrieveSeatMapRequestOpts(requestParameters: RetrieveSeatMapRequest): Promise<runtime.RequestOpts>;

    /**
     * Provides the seat map details, including real-time seat availability, for a specified flight and cabin requested by the passenger.
     * @summary Search seat availability for requested cabin
     * @param {NEXUZR004OffersSeatMapRequest} nEXUZR004OffersSeatMapRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SeatMapApiInterface
     */
    retrieveSeatMapRaw(requestParameters: RetrieveSeatMapRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR004OffersFlightSeatMapResponse>>;

    /**
     * Provides the seat map details, including real-time seat availability, for a specified flight and cabin requested by the passenger.
     * Search seat availability for requested cabin
     */
    retrieveSeatMap(requestParameters: RetrieveSeatMapRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR004OffersFlightSeatMapResponse>;

}

/**
 * 
 */
export class SeatMapApi extends runtime.BaseAPI implements SeatMapApiInterface {

    /**
     * Creates request options for retrieveSeatMap without sending the request
     */
    async retrieveSeatMapRequestOpts(requestParameters: RetrieveSeatMapRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['nEXUZR004OffersSeatMapRequest'] == null) {
            throw new runtime.RequiredError(
                'nEXUZR004OffersSeatMapRequest',
                'Required parameter "nEXUZR004OffersSeatMapRequest" was null or undefined when calling retrieveSeatMap().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/offers/seatMap`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NEXUZR004OffersSeatMapRequestToJSON(requestParameters['nEXUZR004OffersSeatMapRequest']),
        };
    }

    /**
     * Provides the seat map details, including real-time seat availability, for a specified flight and cabin requested by the passenger.
     * Search seat availability for requested cabin
     */
    async retrieveSeatMapRaw(requestParameters: RetrieveSeatMapRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NEXUZR004OffersFlightSeatMapResponse>> {
        const requestOptions = await this.retrieveSeatMapRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NEXUZR004OffersFlightSeatMapResponseFromJSON(jsonValue));
    }

    /**
     * Provides the seat map details, including real-time seat availability, for a specified flight and cabin requested by the passenger.
     * Search seat availability for requested cabin
     */
    async retrieveSeatMap(requestParameters: RetrieveSeatMapRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NEXUZR004OffersFlightSeatMapResponse> {
        const response = await this.retrieveSeatMapRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
