/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR007OrderManagementCapture
 */
export interface NEXUZR007OrderManagementCapture {
    /**
     * Transaction Type.
     * @type {string}
     * @memberof NEXUZR007OrderManagementCapture
     */
    debitCreditIndicator: string;
}

/**
 * Check if a given object implements the NEXUZR007OrderManagementCapture interface.
 */
export function instanceOfNEXUZR007OrderManagementCapture(value: object): value is NEXUZR007OrderManagementCapture {
    if (!('debitCreditIndicator' in value) || value['debitCreditIndicator'] === undefined) return false;
    return true;
}

export function NEXUZR007OrderManagementCaptureFromJSON(json: any): NEXUZR007OrderManagementCapture {
    return NEXUZR007OrderManagementCaptureFromJSONTyped(json, false);
}

export function NEXUZR007OrderManagementCaptureFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR007OrderManagementCapture {
    if (json == null) {
        return json;
    }
    return {
        
        'debitCreditIndicator': json['debitCreditIndicator'],
    };
}

export function NEXUZR007OrderManagementCaptureToJSON(json: any): NEXUZR007OrderManagementCapture {
    return NEXUZR007OrderManagementCaptureToJSONTyped(json, false);
}

export function NEXUZR007OrderManagementCaptureToJSONTyped(value?: NEXUZR007OrderManagementCapture | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'debitCreditIndicator': value['debitCreditIndicator'],
    };
}

