/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR002SearchFareDateEntry } from './NEXUZR002SearchFareDateEntry';
import {
    NEXUZR002SearchFareDateEntryFromJSON,
    NEXUZR002SearchFareDateEntryFromJSONTyped,
    NEXUZR002SearchFareDateEntryToJSON,
    NEXUZR002SearchFareDateEntryToJSONTyped,
} from './NEXUZR002SearchFareDateEntry';

/**
 * 
 * @export
 * @interface NEXUZR002SearchBoundFareDataInner
 */
export interface NEXUZR002SearchBoundFareDataInner {
    /**
     * Cabin type (e.g., STANDARD or ZIPFULLFLAT).
     * @type {string}
     * @memberof NEXUZR002SearchBoundFareDataInner
     */
    cabin: string;
    /**
     * Fare details for the bound grouped by travel date.
     * @type {Array<NEXUZR002SearchFareDateEntry>}
     * @memberof NEXUZR002SearchBoundFareDataInner
     */
    dates: Array<NEXUZR002SearchFareDateEntry>;
}

/**
 * Check if a given object implements the NEXUZR002SearchBoundFareDataInner interface.
 */
export function instanceOfNEXUZR002SearchBoundFareDataInner(value: object): value is NEXUZR002SearchBoundFareDataInner {
    if (!('cabin' in value) || value['cabin'] === undefined) return false;
    if (!('dates' in value) || value['dates'] === undefined) return false;
    return true;
}

export function NEXUZR002SearchBoundFareDataInnerFromJSON(json: any): NEXUZR002SearchBoundFareDataInner {
    return NEXUZR002SearchBoundFareDataInnerFromJSONTyped(json, false);
}

export function NEXUZR002SearchBoundFareDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR002SearchBoundFareDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'cabin': json['cabin'],
        'dates': ((json['dates'] as Array<any>).map(NEXUZR002SearchFareDateEntryFromJSON)),
    };
}

export function NEXUZR002SearchBoundFareDataInnerToJSON(json: any): NEXUZR002SearchBoundFareDataInner {
    return NEXUZR002SearchBoundFareDataInnerToJSONTyped(json, false);
}

export function NEXUZR002SearchBoundFareDataInnerToJSONTyped(value?: NEXUZR002SearchBoundFareDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cabin': value['cabin'],
        'dates': ((value['dates'] as Array<any>).map(NEXUZR002SearchFareDateEntryToJSON)),
    };
}

