/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR007OrderManagementPassenger
 */
export interface NEXUZR007OrderManagementPassenger {
    /**
     * Passenger code.
     * @type {string}
     * @memberof NEXUZR007OrderManagementPassenger
     */
    code: string;
    /**
     * Name of the Passenger.
     * @type {string}
     * @memberof NEXUZR007OrderManagementPassenger
     */
    name: string;
}

/**
 * Check if a given object implements the NEXUZR007OrderManagementPassenger interface.
 */
export function instanceOfNEXUZR007OrderManagementPassenger(value: object): value is NEXUZR007OrderManagementPassenger {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function NEXUZR007OrderManagementPassengerFromJSON(json: any): NEXUZR007OrderManagementPassenger {
    return NEXUZR007OrderManagementPassengerFromJSONTyped(json, false);
}

export function NEXUZR007OrderManagementPassengerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR007OrderManagementPassenger {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'name': json['name'],
    };
}

export function NEXUZR007OrderManagementPassengerToJSON(json: any): NEXUZR007OrderManagementPassenger {
    return NEXUZR007OrderManagementPassengerToJSONTyped(json, false);
}

export function NEXUZR007OrderManagementPassengerToJSONTyped(value?: NEXUZR007OrderManagementPassenger | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
    };
}

