/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR004OffersSeatInfo } from './NEXUZR004OffersSeatInfo';
import {
    NEXUZR004OffersSeatInfoFromJSON,
    NEXUZR004OffersSeatInfoFromJSONTyped,
    NEXUZR004OffersSeatInfoToJSON,
    NEXUZR004OffersSeatInfoToJSONTyped,
} from './NEXUZR004OffersSeatInfo';

/**
 * 
 * @export
 * @interface NEXUZR004OffersFlightSeatMapResponseData
 */
export interface NEXUZR004OffersFlightSeatMapResponseData {
    /**
     * List of rows with associated seat details.
     * @type {Array<NEXUZR004OffersSeatInfo>}
     * @memberof NEXUZR004OffersFlightSeatMapResponseData
     */
    seatInfo: Array<NEXUZR004OffersSeatInfo>;
}

/**
 * Check if a given object implements the NEXUZR004OffersFlightSeatMapResponseData interface.
 */
export function instanceOfNEXUZR004OffersFlightSeatMapResponseData(value: object): value is NEXUZR004OffersFlightSeatMapResponseData {
    if (!('seatInfo' in value) || value['seatInfo'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersFlightSeatMapResponseDataFromJSON(json: any): NEXUZR004OffersFlightSeatMapResponseData {
    return NEXUZR004OffersFlightSeatMapResponseDataFromJSONTyped(json, false);
}

export function NEXUZR004OffersFlightSeatMapResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersFlightSeatMapResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'seatInfo': ((json['seatInfo'] as Array<any>).map(NEXUZR004OffersSeatInfoFromJSON)),
    };
}

export function NEXUZR004OffersFlightSeatMapResponseDataToJSON(json: any): NEXUZR004OffersFlightSeatMapResponseData {
    return NEXUZR004OffersFlightSeatMapResponseDataToJSONTyped(json, false);
}

export function NEXUZR004OffersFlightSeatMapResponseDataToJSONTyped(value?: NEXUZR004OffersFlightSeatMapResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'seatInfo': ((value['seatInfo'] as Array<any>).map(NEXUZR004OffersSeatInfoToJSON)),
    };
}

