/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR005APIsOrderData
 */
export interface NEXUZR005APIsOrderData {
    /**
     * This field contains the orderId.
     * @type {string}
     * @memberof NEXUZR005APIsOrderData
     */
    statusCheckKey: string;
    /**
     * This field contains the ReservationPaymentID.
     * @type {string}
     * @memberof NEXUZR005APIsOrderData
     */
    paymentReferenceId: string;
    /**
     * This field contains the UI redirection URL.
     * @type {string}
     * @memberof NEXUZR005APIsOrderData
     */
    redirectionUrl: string;
}

/**
 * Check if a given object implements the NEXUZR005APIsOrderData interface.
 */
export function instanceOfNEXUZR005APIsOrderData(value: object): value is NEXUZR005APIsOrderData {
    if (!('statusCheckKey' in value) || value['statusCheckKey'] === undefined) return false;
    if (!('paymentReferenceId' in value) || value['paymentReferenceId'] === undefined) return false;
    if (!('redirectionUrl' in value) || value['redirectionUrl'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsOrderDataFromJSON(json: any): NEXUZR005APIsOrderData {
    return NEXUZR005APIsOrderDataFromJSONTyped(json, false);
}

export function NEXUZR005APIsOrderDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsOrderData {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCheckKey': json['statusCheckKey'],
        'paymentReferenceId': json['paymentReferenceId'],
        'redirectionUrl': json['redirectionUrl'],
    };
}

export function NEXUZR005APIsOrderDataToJSON(json: any): NEXUZR005APIsOrderData {
    return NEXUZR005APIsOrderDataToJSONTyped(json, false);
}

export function NEXUZR005APIsOrderDataToJSONTyped(value?: NEXUZR005APIsOrderData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCheckKey': value['statusCheckKey'],
        'paymentReferenceId': value['paymentReferenceId'],
        'redirectionUrl': value['redirectionUrl'],
    };
}

