/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR006PaymentRecipientInfo } from './NEXUZR006PaymentRecipientInfo';
import {
    NEXUZR006PaymentRecipientInfoFromJSON,
    NEXUZR006PaymentRecipientInfoFromJSONTyped,
    NEXUZR006PaymentRecipientInfoToJSON,
    NEXUZR006PaymentRecipientInfoToJSONTyped,
} from './NEXUZR006PaymentRecipientInfo';
import type { NEXUZR006PaymentContactInfo } from './NEXUZR006PaymentContactInfo';
import {
    NEXUZR006PaymentContactInfoFromJSON,
    NEXUZR006PaymentContactInfoFromJSONTyped,
    NEXUZR006PaymentContactInfoToJSON,
    NEXUZR006PaymentContactInfoToJSONTyped,
} from './NEXUZR006PaymentContactInfo';

/**
 * 
 * @export
 * @interface NEXUZR006PaymentInitializePaymentRequest
 */
export interface NEXUZR006PaymentInitializePaymentRequest {
    /**
     * Reservation confirmation number (PNR).
     * @type {string}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    confirmationNumber: string;
    /**
     * Base payment amount.
     * @type {number}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    baseAmount: number;
    /**
     * Date and time of payment in ISO 8601 format.
     * @type {string}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    datePaid: string;
    /**
     * Exchange rate applied for currency conversion.
     * @type {number}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    exchangeRate: number;
    /**
     * Date and time when the exchange rate was captured.
     * @type {string}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    exchangeRateDate: string;
    /**
     * Payment expiration date and time.
     * @type {string}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    expirationDate: string;
    /**
     * Original payment amount before conversion.
     * @type {number}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    originalAmount: number;
    /**
     * Final payment amount to be processed.
     * @type {number}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    paymentAmount: number;
    /**
     * Person/Organization ID of the payor.
     * @type {number}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    personOrgID: number;
    /**
     * Date of birth of the payor (YYYY-MM-DD).
     * @type {Date}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    dob: Date;
    /**
     * Age of the payor in years.
     * @type {number}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    age: number;
    /**
     * First name of the payor.
     * @type {string}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    firstName: string;
    /**
     * Middle name of the payor.
     * @type {string}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    middleName?: string;
    /**
     * Gender of the payor.
     * @type {NEXUZR006PaymentInitializePaymentRequestGenderEnum}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    gender: NEXUZR006PaymentInitializePaymentRequestGenderEnum;
    /**
     * Last name of the payor.
     * @type {string}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    lastName: string;
    /**
     * Whether the payor has opted in for marketing communications.
     * @type {boolean}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    marketingOptIn: boolean;
    /**
     * Nationality country code of the payor.
     * @type {string}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    nationality: string;
    /**
     * List of contact information for the payor.
     * @type {Array<NEXUZR006PaymentContactInfo>}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    contactInfos: Array<NEXUZR006PaymentContactInfo>;
    /**
     * 
     * @type {NEXUZR006PaymentRecipientInfo}
     * @memberof NEXUZR006PaymentInitializePaymentRequest
     */
    recipientInfo: NEXUZR006PaymentRecipientInfo;
}


/**
 * @export
 */
export const NEXUZR006PaymentInitializePaymentRequestGenderEnum = {
    m: 'M',
    f: 'F'
} as const;
export type NEXUZR006PaymentInitializePaymentRequestGenderEnum = typeof NEXUZR006PaymentInitializePaymentRequestGenderEnum[keyof typeof NEXUZR006PaymentInitializePaymentRequestGenderEnum];


/**
 * Check if a given object implements the NEXUZR006PaymentInitializePaymentRequest interface.
 */
export function instanceOfNEXUZR006PaymentInitializePaymentRequest(value: object): value is NEXUZR006PaymentInitializePaymentRequest {
    if (!('confirmationNumber' in value) || value['confirmationNumber'] === undefined) return false;
    if (!('baseAmount' in value) || value['baseAmount'] === undefined) return false;
    if (!('datePaid' in value) || value['datePaid'] === undefined) return false;
    if (!('exchangeRate' in value) || value['exchangeRate'] === undefined) return false;
    if (!('exchangeRateDate' in value) || value['exchangeRateDate'] === undefined) return false;
    if (!('expirationDate' in value) || value['expirationDate'] === undefined) return false;
    if (!('originalAmount' in value) || value['originalAmount'] === undefined) return false;
    if (!('paymentAmount' in value) || value['paymentAmount'] === undefined) return false;
    if (!('personOrgID' in value) || value['personOrgID'] === undefined) return false;
    if (!('dob' in value) || value['dob'] === undefined) return false;
    if (!('age' in value) || value['age'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('gender' in value) || value['gender'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('marketingOptIn' in value) || value['marketingOptIn'] === undefined) return false;
    if (!('nationality' in value) || value['nationality'] === undefined) return false;
    if (!('contactInfos' in value) || value['contactInfos'] === undefined) return false;
    if (!('recipientInfo' in value) || value['recipientInfo'] === undefined) return false;
    return true;
}

export function NEXUZR006PaymentInitializePaymentRequestFromJSON(json: any): NEXUZR006PaymentInitializePaymentRequest {
    return NEXUZR006PaymentInitializePaymentRequestFromJSONTyped(json, false);
}

export function NEXUZR006PaymentInitializePaymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR006PaymentInitializePaymentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'confirmationNumber': json['confirmationNumber'],
        'baseAmount': json['baseAmount'],
        'datePaid': json['datePaid'],
        'exchangeRate': json['exchangeRate'],
        'exchangeRateDate': json['exchangeRateDate'],
        'expirationDate': json['expirationDate'],
        'originalAmount': json['originalAmount'],
        'paymentAmount': json['paymentAmount'],
        'personOrgID': json['personOrgID'],
        'dob': (new Date(json['dob'])),
        'age': json['age'],
        'firstName': json['firstName'],
        'middleName': json['middleName'] == null ? undefined : json['middleName'],
        'gender': json['gender'],
        'lastName': json['lastName'],
        'marketingOptIn': json['marketingOptIn'],
        'nationality': json['nationality'],
        'contactInfos': ((json['contactInfos'] as Array<any>).map(NEXUZR006PaymentContactInfoFromJSON)),
        'recipientInfo': NEXUZR006PaymentRecipientInfoFromJSON(json['recipientInfo']),
    };
}

export function NEXUZR006PaymentInitializePaymentRequestToJSON(json: any): NEXUZR006PaymentInitializePaymentRequest {
    return NEXUZR006PaymentInitializePaymentRequestToJSONTyped(json, false);
}

export function NEXUZR006PaymentInitializePaymentRequestToJSONTyped(value?: NEXUZR006PaymentInitializePaymentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'confirmationNumber': value['confirmationNumber'],
        'baseAmount': value['baseAmount'],
        'datePaid': value['datePaid'],
        'exchangeRate': value['exchangeRate'],
        'exchangeRateDate': value['exchangeRateDate'],
        'expirationDate': value['expirationDate'],
        'originalAmount': value['originalAmount'],
        'paymentAmount': value['paymentAmount'],
        'personOrgID': value['personOrgID'],
        'dob': value['dob'].toISOString().substring(0,10),
        'age': value['age'],
        'firstName': value['firstName'],
        'middleName': value['middleName'],
        'gender': value['gender'],
        'lastName': value['lastName'],
        'marketingOptIn': value['marketingOptIn'],
        'nationality': value['nationality'],
        'contactInfos': ((value['contactInfos'] as Array<any>).map(NEXUZR006PaymentContactInfoToJSON)),
        'recipientInfo': NEXUZR006PaymentRecipientInfoToJSON(value['recipientInfo']),
    };
}

