/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR003FlightsFlightSearchResponseData } from './NEXUZR003FlightsFlightSearchResponseData';
import {
    NEXUZR003FlightsFlightSearchResponseDataFromJSON,
    NEXUZR003FlightsFlightSearchResponseDataFromJSONTyped,
    NEXUZR003FlightsFlightSearchResponseDataToJSON,
    NEXUZR003FlightsFlightSearchResponseDataToJSONTyped,
} from './NEXUZR003FlightsFlightSearchResponseData';

/**
 * Top-level response wrapper for flight search.
 * @export
 * @interface NEXUZR003FlightsFlightSearchResponse
 */
export interface NEXUZR003FlightsFlightSearchResponse {
    /**
     * 
     * @type {NEXUZR003FlightsFlightSearchResponseData}
     * @memberof NEXUZR003FlightsFlightSearchResponse
     */
    data?: NEXUZR003FlightsFlightSearchResponseData;
}

/**
 * Check if a given object implements the NEXUZR003FlightsFlightSearchResponse interface.
 */
export function instanceOfNEXUZR003FlightsFlightSearchResponse(value: object): value is NEXUZR003FlightsFlightSearchResponse {
    return true;
}

export function NEXUZR003FlightsFlightSearchResponseFromJSON(json: any): NEXUZR003FlightsFlightSearchResponse {
    return NEXUZR003FlightsFlightSearchResponseFromJSONTyped(json, false);
}

export function NEXUZR003FlightsFlightSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR003FlightsFlightSearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : NEXUZR003FlightsFlightSearchResponseDataFromJSON(json['data']),
    };
}

export function NEXUZR003FlightsFlightSearchResponseToJSON(json: any): NEXUZR003FlightsFlightSearchResponse {
    return NEXUZR003FlightsFlightSearchResponseToJSONTyped(json, false);
}

export function NEXUZR003FlightsFlightSearchResponseToJSONTyped(value?: NEXUZR003FlightsFlightSearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': NEXUZR003FlightsFlightSearchResponseDataToJSON(value['data']),
    };
}

