/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR007OrderManagementAmount
 */
export interface NEXUZR007OrderManagementAmount {
    /**
     * Amount to be paid by the passenger.
     * @type {number}
     * @memberof NEXUZR007OrderManagementAmount
     */
    value: number;
    /**
     * Currency denotion for amount.
     * @type {string}
     * @memberof NEXUZR007OrderManagementAmount
     */
    currencyCode: string;
    /**
     * 
     * @type {number}
     * @memberof NEXUZR007OrderManagementAmount
     */
    exponent: number;
}

/**
 * Check if a given object implements the NEXUZR007OrderManagementAmount interface.
 */
export function instanceOfNEXUZR007OrderManagementAmount(value: object): value is NEXUZR007OrderManagementAmount {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('currencyCode' in value) || value['currencyCode'] === undefined) return false;
    if (!('exponent' in value) || value['exponent'] === undefined) return false;
    return true;
}

export function NEXUZR007OrderManagementAmountFromJSON(json: any): NEXUZR007OrderManagementAmount {
    return NEXUZR007OrderManagementAmountFromJSONTyped(json, false);
}

export function NEXUZR007OrderManagementAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR007OrderManagementAmount {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'],
        'currencyCode': json['currencyCode'],
        'exponent': json['exponent'],
    };
}

export function NEXUZR007OrderManagementAmountToJSON(json: any): NEXUZR007OrderManagementAmount {
    return NEXUZR007OrderManagementAmountToJSONTyped(json, false);
}

export function NEXUZR007OrderManagementAmountToJSONTyped(value?: NEXUZR007OrderManagementAmount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
        'currencyCode': value['currencyCode'],
        'exponent': value['exponent'],
    };
}

