/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR003FlightsBoundData } from './NEXUZR003FlightsBoundData';
import {
    NEXUZR003FlightsBoundDataFromJSON,
    NEXUZR003FlightsBoundDataFromJSONTyped,
    NEXUZR003FlightsBoundDataToJSON,
    NEXUZR003FlightsBoundDataToJSONTyped,
} from './NEXUZR003FlightsBoundData';

/**
 * 
 * @export
 * @interface NEXUZR003FlightsFlightSearchResponseData
 */
export interface NEXUZR003FlightsFlightSearchResponseData {
    /**
     * 
     * @type {NEXUZR003FlightsBoundData}
     * @memberof NEXUZR003FlightsFlightSearchResponseData
     */
    outbound?: NEXUZR003FlightsBoundData;
    /**
     * Inbound flight data. Only present for round-trip requests.
     * @type {NEXUZR003FlightsBoundData}
     * @memberof NEXUZR003FlightsFlightSearchResponseData
     */
    inbound?: NEXUZR003FlightsBoundData | null;
}

/**
 * Check if a given object implements the NEXUZR003FlightsFlightSearchResponseData interface.
 */
export function instanceOfNEXUZR003FlightsFlightSearchResponseData(value: object): value is NEXUZR003FlightsFlightSearchResponseData {
    return true;
}

export function NEXUZR003FlightsFlightSearchResponseDataFromJSON(json: any): NEXUZR003FlightsFlightSearchResponseData {
    return NEXUZR003FlightsFlightSearchResponseDataFromJSONTyped(json, false);
}

export function NEXUZR003FlightsFlightSearchResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR003FlightsFlightSearchResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'outbound': json['outbound'] == null ? undefined : NEXUZR003FlightsBoundDataFromJSON(json['outbound']),
        'inbound': json['inbound'] == null ? undefined : NEXUZR003FlightsBoundDataFromJSON(json['inbound']),
    };
}

export function NEXUZR003FlightsFlightSearchResponseDataToJSON(json: any): NEXUZR003FlightsFlightSearchResponseData {
    return NEXUZR003FlightsFlightSearchResponseDataToJSONTyped(json, false);
}

export function NEXUZR003FlightsFlightSearchResponseDataToJSONTyped(value?: NEXUZR003FlightsFlightSearchResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'outbound': NEXUZR003FlightsBoundDataToJSON(value['outbound']),
        'inbound': NEXUZR003FlightsBoundDataToJSON(value['inbound']),
    };
}

