/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Standard error response body.
 * @export
 * @interface NEXUZR003FlightsErrorResponse
 */
export interface NEXUZR003FlightsErrorResponse {
    /**
     * Application-level error code.
     * @type {string}
     * @memberof NEXUZR003FlightsErrorResponse
     */
    code: string;
    /**
     * Error description.
     * @type {string}
     * @memberof NEXUZR003FlightsErrorResponse
     */
    description: string;
}

/**
 * Check if a given object implements the NEXUZR003FlightsErrorResponse interface.
 */
export function instanceOfNEXUZR003FlightsErrorResponse(value: object): value is NEXUZR003FlightsErrorResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function NEXUZR003FlightsErrorResponseFromJSON(json: any): NEXUZR003FlightsErrorResponse {
    return NEXUZR003FlightsErrorResponseFromJSONTyped(json, false);
}

export function NEXUZR003FlightsErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR003FlightsErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
    };
}

export function NEXUZR003FlightsErrorResponseToJSON(json: any): NEXUZR003FlightsErrorResponse {
    return NEXUZR003FlightsErrorResponseToJSONTyped(json, false);
}

export function NEXUZR003FlightsErrorResponseToJSONTyped(value?: NEXUZR003FlightsErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
    };
}

