/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR007OrderManagementDateParts } from './NEXUZR007OrderManagementDateParts';
import {
    NEXUZR007OrderManagementDatePartsFromJSON,
    NEXUZR007OrderManagementDatePartsFromJSONTyped,
    NEXUZR007OrderManagementDatePartsToJSON,
    NEXUZR007OrderManagementDatePartsToJSONTyped,
} from './NEXUZR007OrderManagementDateParts';

/**
 * 
 * @export
 * @interface NEXUZR007OrderManagementTicket
 */
export interface NEXUZR007OrderManagementTicket {
    /**
     * Confirmation number.
     * @type {string}
     * @memberof NEXUZR007OrderManagementTicket
     */
    code: string;
    /**
     * Count of the Adult Passengers.
     * @type {number}
     * @memberof NEXUZR007OrderManagementTicket
     */
    adultCount: number;
    /**
     * Count of the Child passengers.
     * @type {number}
     * @memberof NEXUZR007OrderManagementTicket
     */
    childCount: number;
    /**
     * 
     * @type {number}
     * @memberof NEXUZR007OrderManagementTicket
     */
    restricted: number;
    /**
     * 
     * @type {NEXUZR007OrderManagementDateParts}
     * @memberof NEXUZR007OrderManagementTicket
     */
    issueDate: NEXUZR007OrderManagementDateParts;
}

/**
 * Check if a given object implements the NEXUZR007OrderManagementTicket interface.
 */
export function instanceOfNEXUZR007OrderManagementTicket(value: object): value is NEXUZR007OrderManagementTicket {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('adultCount' in value) || value['adultCount'] === undefined) return false;
    if (!('childCount' in value) || value['childCount'] === undefined) return false;
    if (!('restricted' in value) || value['restricted'] === undefined) return false;
    if (!('issueDate' in value) || value['issueDate'] === undefined) return false;
    return true;
}

export function NEXUZR007OrderManagementTicketFromJSON(json: any): NEXUZR007OrderManagementTicket {
    return NEXUZR007OrderManagementTicketFromJSONTyped(json, false);
}

export function NEXUZR007OrderManagementTicketFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR007OrderManagementTicket {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'adultCount': json['adultCount'],
        'childCount': json['childCount'],
        'restricted': json['restricted'],
        'issueDate': NEXUZR007OrderManagementDatePartsFromJSON(json['issueDate']),
    };
}

export function NEXUZR007OrderManagementTicketToJSON(json: any): NEXUZR007OrderManagementTicket {
    return NEXUZR007OrderManagementTicketToJSONTyped(json, false);
}

export function NEXUZR007OrderManagementTicketToJSONTyped(value?: NEXUZR007OrderManagementTicket | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'adultCount': value['adultCount'],
        'childCount': value['childCount'],
        'restricted': value['restricted'],
        'issueDate': NEXUZR007OrderManagementDatePartsToJSON(value['issueDate']),
    };
}

