/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR005APIsErrorResponse
 */
export interface NEXUZR005APIsErrorResponse {
    /**
     * Custom error code
     * @type {string}
     * @memberof NEXUZR005APIsErrorResponse
     */
    code: string;
    /**
     * Error description
     * @type {string}
     * @memberof NEXUZR005APIsErrorResponse
     */
    description: string;
}

/**
 * Check if a given object implements the NEXUZR005APIsErrorResponse interface.
 */
export function instanceOfNEXUZR005APIsErrorResponse(value: object): value is NEXUZR005APIsErrorResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsErrorResponseFromJSON(json: any): NEXUZR005APIsErrorResponse {
    return NEXUZR005APIsErrorResponseFromJSONTyped(json, false);
}

export function NEXUZR005APIsErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
    };
}

export function NEXUZR005APIsErrorResponseToJSON(json: any): NEXUZR005APIsErrorResponse {
    return NEXUZR005APIsErrorResponseToJSONTyped(json, false);
}

export function NEXUZR005APIsErrorResponseToJSONTyped(value?: NEXUZR005APIsErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
    };
}

