/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR002SearchBoundFareDataInner } from './NEXUZR002SearchBoundFareDataInner';
import {
    NEXUZR002SearchBoundFareDataInnerFromJSON,
    NEXUZR002SearchBoundFareDataInnerFromJSONTyped,
    NEXUZR002SearchBoundFareDataInnerToJSON,
    NEXUZR002SearchBoundFareDataInnerToJSONTyped,
} from './NEXUZR002SearchBoundFareDataInner';

/**
 * 
 * @export
 * @interface NEXUZR002SearchCalendarFaresData
 */
export interface NEXUZR002SearchCalendarFaresData {
    /**
     * 
     * @type {Array<NEXUZR002SearchBoundFareDataInner>}
     * @memberof NEXUZR002SearchCalendarFaresData
     */
    outbound: Array<NEXUZR002SearchBoundFareDataInner>;
    /**
     * 
     * @type {Array<NEXUZR002SearchBoundFareDataInner>}
     * @memberof NEXUZR002SearchCalendarFaresData
     */
    inbound?: Array<NEXUZR002SearchBoundFareDataInner>;
}

/**
 * Check if a given object implements the NEXUZR002SearchCalendarFaresData interface.
 */
export function instanceOfNEXUZR002SearchCalendarFaresData(value: object): value is NEXUZR002SearchCalendarFaresData {
    if (!('outbound' in value) || value['outbound'] === undefined) return false;
    return true;
}

export function NEXUZR002SearchCalendarFaresDataFromJSON(json: any): NEXUZR002SearchCalendarFaresData {
    return NEXUZR002SearchCalendarFaresDataFromJSONTyped(json, false);
}

export function NEXUZR002SearchCalendarFaresDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR002SearchCalendarFaresData {
    if (json == null) {
        return json;
    }
    return {
        
        'outbound': ((json['outbound'] as Array<any>).map(NEXUZR002SearchBoundFareDataInnerFromJSON)),
        'inbound': json['inbound'] == null ? undefined : ((json['inbound'] as Array<any>).map(NEXUZR002SearchBoundFareDataInnerFromJSON)),
    };
}

export function NEXUZR002SearchCalendarFaresDataToJSON(json: any): NEXUZR002SearchCalendarFaresData {
    return NEXUZR002SearchCalendarFaresDataToJSONTyped(json, false);
}

export function NEXUZR002SearchCalendarFaresDataToJSONTyped(value?: NEXUZR002SearchCalendarFaresData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'outbound': ((value['outbound'] as Array<any>).map(NEXUZR002SearchBoundFareDataInnerToJSON)),
        'inbound': value['inbound'] == null ? undefined : ((value['inbound'] as Array<any>).map(NEXUZR002SearchBoundFareDataInnerToJSON)),
    };
}

