/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Standard error response body.
 * @export
 * @interface NEXUZR006PaymentErrorResponse
 */
export interface NEXUZR006PaymentErrorResponse {
    /**
     * Application-level error code.
     * @type {string}
     * @memberof NEXUZR006PaymentErrorResponse
     */
    code: string;
    /**
     * Error description.
     * @type {string}
     * @memberof NEXUZR006PaymentErrorResponse
     */
    description: string;
}

/**
 * Check if a given object implements the NEXUZR006PaymentErrorResponse interface.
 */
export function instanceOfNEXUZR006PaymentErrorResponse(value: object): value is NEXUZR006PaymentErrorResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function NEXUZR006PaymentErrorResponseFromJSON(json: any): NEXUZR006PaymentErrorResponse {
    return NEXUZR006PaymentErrorResponseFromJSONTyped(json, false);
}

export function NEXUZR006PaymentErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR006PaymentErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
    };
}

export function NEXUZR006PaymentErrorResponseToJSON(json: any): NEXUZR006PaymentErrorResponse {
    return NEXUZR006PaymentErrorResponseToJSONTyped(json, false);
}

export function NEXUZR006PaymentErrorResponseToJSONTyped(value?: NEXUZR006PaymentErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
    };
}

