/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR006PaymentContactInfo
 */
export interface NEXUZR006PaymentContactInfo {
    /**
     * Unique identifier for the contact record.
     * @type {number}
     * @memberof NEXUZR006PaymentContactInfo
     */
    contactID: number;
    /**
     * Person/Organization ID associated with this contact.
     * @type {number}
     * @memberof NEXUZR006PaymentContactInfo
     */
    personOrgID: number;
    /**
     * Contact value (phone number or email).
     * @type {string}
     * @memberof NEXUZR006PaymentContactInfo
     */
    contactField: string;
    /**
     * Type of contact (e.g., Workphone, Email).
     * @type {NEXUZR006PaymentContactInfoContactTypeEnum}
     * @memberof NEXUZR006PaymentContactInfo
     */
    contactType: NEXUZR006PaymentContactInfoContactTypeEnum;
}


/**
 * @export
 */
export const NEXUZR006PaymentContactInfoContactTypeEnum = {
    workphone: 'Workphone',
    mobilephone: 'Mobilephone',
    email: 'Email'
} as const;
export type NEXUZR006PaymentContactInfoContactTypeEnum = typeof NEXUZR006PaymentContactInfoContactTypeEnum[keyof typeof NEXUZR006PaymentContactInfoContactTypeEnum];


/**
 * Check if a given object implements the NEXUZR006PaymentContactInfo interface.
 */
export function instanceOfNEXUZR006PaymentContactInfo(value: object): value is NEXUZR006PaymentContactInfo {
    if (!('contactID' in value) || value['contactID'] === undefined) return false;
    if (!('personOrgID' in value) || value['personOrgID'] === undefined) return false;
    if (!('contactField' in value) || value['contactField'] === undefined) return false;
    if (!('contactType' in value) || value['contactType'] === undefined) return false;
    return true;
}

export function NEXUZR006PaymentContactInfoFromJSON(json: any): NEXUZR006PaymentContactInfo {
    return NEXUZR006PaymentContactInfoFromJSONTyped(json, false);
}

export function NEXUZR006PaymentContactInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR006PaymentContactInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'contactID': json['contactID'],
        'personOrgID': json['personOrgID'],
        'contactField': json['contactField'],
        'contactType': json['contactType'],
    };
}

export function NEXUZR006PaymentContactInfoToJSON(json: any): NEXUZR006PaymentContactInfo {
    return NEXUZR006PaymentContactInfoToJSONTyped(json, false);
}

export function NEXUZR006PaymentContactInfoToJSONTyped(value?: NEXUZR006PaymentContactInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contactID': value['contactID'],
        'personOrgID': value['personOrgID'],
        'contactField': value['contactField'],
        'contactType': value['contactType'],
    };
}

