/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR005APIsBundle } from './NEXUZR005APIsBundle';
import {
    NEXUZR005APIsBundleFromJSON,
    NEXUZR005APIsBundleFromJSONTyped,
    NEXUZR005APIsBundleToJSON,
    NEXUZR005APIsBundleToJSONTyped,
} from './NEXUZR005APIsBundle';
import type { NEXUZR005APIsService } from './NEXUZR005APIsService';
import {
    NEXUZR005APIsServiceFromJSON,
    NEXUZR005APIsServiceFromJSONTyped,
    NEXUZR005APIsServiceToJSON,
    NEXUZR005APIsServiceToJSONTyped,
} from './NEXUZR005APIsService';
import type { NEXUZR005APIsEmergencyContact } from './NEXUZR005APIsEmergencyContact';
import {
    NEXUZR005APIsEmergencyContactFromJSON,
    NEXUZR005APIsEmergencyContactFromJSONTyped,
    NEXUZR005APIsEmergencyContactToJSON,
    NEXUZR005APIsEmergencyContactToJSONTyped,
} from './NEXUZR005APIsEmergencyContact';
import type { NEXUZR005APIsContactInformation } from './NEXUZR005APIsContactInformation';
import {
    NEXUZR005APIsContactInformationFromJSON,
    NEXUZR005APIsContactInformationFromJSONTyped,
    NEXUZR005APIsContactInformationToJSON,
    NEXUZR005APIsContactInformationToJSONTyped,
} from './NEXUZR005APIsContactInformation';
import type { NEXUZR005APIsSeat } from './NEXUZR005APIsSeat';
import {
    NEXUZR005APIsSeatFromJSON,
    NEXUZR005APIsSeatFromJSONTyped,
    NEXUZR005APIsSeatToJSON,
    NEXUZR005APIsSeatToJSONTyped,
} from './NEXUZR005APIsSeat';

/**
 * 
 * @export
 * @interface NEXUZR005APIsPassengerDetails
 */
export interface NEXUZR005APIsPassengerDetails {
    /**
     * Unique passenger identifier.
     * @type {number}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    id: number;
    /**
     * Passenger type classification.
     * @type {NEXUZR005APIsPassengerDetailsPassengerTypeEnum}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    passengerType: NEXUZR005APIsPassengerDetailsPassengerTypeEnum;
    /**
     * Adult passenger this passenger is associated with (optional).
     * @type {number}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    associateWithPassengerId?: number;
    /**
     * **Passenger first name.**
     * - Alphanumeric characters only
     * - Length: 1 to 64 characters
     * 
     * @type {string}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    firstName: string;
    /**
     * Passenger middle name.
     * @type {string}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    middleName?: string;
    /**
     * Passenger last name.
     * @type {string}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    lastName: string;
    /**
     * Date of birth.
     * @type {string}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    dateOfBirth: string;
    /**
     * Passenger gender.
     * @type {NEXUZR005APIsPassengerDetailsGenderEnum}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    gender: NEXUZR005APIsPassengerDetailsGenderEnum;
    /**
     * Redress number.
     * @type {string}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    redressNumber?: string;
    /**
     * Known Traveler Number.
     * @type {string}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    knownTravelerNumber?: string;
    /**
     * 3-character ISO country code.
     * @type {string}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    nationality: string;
    /**
     * Indicates primary passenger in booking.
     * @type {boolean}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    isPrimaryPassenger: boolean;
    /**
     * Passenger height in centimeters (optional).
     * @type {number}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    height?: number;
    /**
     * Passenger weight in kilograms (optional).
     * @type {number}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    weight?: number;
    /**
     * 
     * @type {NEXUZR005APIsContactInformation}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    contactInformation: NEXUZR005APIsContactInformation;
    /**
     * 
     * @type {NEXUZR005APIsEmergencyContact}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    emergencyContact?: NEXUZR005APIsEmergencyContact;
    /**
     * Opt-in for marketing emails (optional).
     * @type {boolean}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    marketingMails?: boolean;
    /**
     * Seat selections by passenger (optional).
     * @type {Array<NEXUZR005APIsSeat>}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    seats?: Array<NEXUZR005APIsSeat>;
    /**
     * Ancillary services for passenger (optional).
     * @type {Array<NEXUZR005APIsService>}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    services?: Array<NEXUZR005APIsService>;
    /**
     * Bundles selected by passenger (optional).
     * @type {Array<NEXUZR005APIsBundle>}
     * @memberof NEXUZR005APIsPassengerDetails
     */
    bundles?: Array<NEXUZR005APIsBundle>;
}


/**
 * @export
 */
export const NEXUZR005APIsPassengerDetailsPassengerTypeEnum = {
    adult: 'Adult',
    childA: 'ChildA',
    childB: 'ChildB',
    childC: 'ChildC',
    infant: 'Infant'
} as const;
export type NEXUZR005APIsPassengerDetailsPassengerTypeEnum = typeof NEXUZR005APIsPassengerDetailsPassengerTypeEnum[keyof typeof NEXUZR005APIsPassengerDetailsPassengerTypeEnum];

/**
 * @export
 */
export const NEXUZR005APIsPassengerDetailsGenderEnum = {
    m: 'M',
    f: 'F'
} as const;
export type NEXUZR005APIsPassengerDetailsGenderEnum = typeof NEXUZR005APIsPassengerDetailsGenderEnum[keyof typeof NEXUZR005APIsPassengerDetailsGenderEnum];


/**
 * Check if a given object implements the NEXUZR005APIsPassengerDetails interface.
 */
export function instanceOfNEXUZR005APIsPassengerDetails(value: object): value is NEXUZR005APIsPassengerDetails {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('passengerType' in value) || value['passengerType'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('dateOfBirth' in value) || value['dateOfBirth'] === undefined) return false;
    if (!('gender' in value) || value['gender'] === undefined) return false;
    if (!('nationality' in value) || value['nationality'] === undefined) return false;
    if (!('isPrimaryPassenger' in value) || value['isPrimaryPassenger'] === undefined) return false;
    if (!('contactInformation' in value) || value['contactInformation'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsPassengerDetailsFromJSON(json: any): NEXUZR005APIsPassengerDetails {
    return NEXUZR005APIsPassengerDetailsFromJSONTyped(json, false);
}

export function NEXUZR005APIsPassengerDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsPassengerDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'passengerType': json['passengerType'],
        'associateWithPassengerId': json['associateWithPassengerId'] == null ? undefined : json['associateWithPassengerId'],
        'firstName': json['firstName'],
        'middleName': json['middleName'] == null ? undefined : json['middleName'],
        'lastName': json['lastName'],
        'dateOfBirth': json['dateOfBirth'],
        'gender': json['gender'],
        'redressNumber': json['redressNumber'] == null ? undefined : json['redressNumber'],
        'knownTravelerNumber': json['knownTravelerNumber'] == null ? undefined : json['knownTravelerNumber'],
        'nationality': json['nationality'],
        'isPrimaryPassenger': json['isPrimaryPassenger'],
        'height': json['height'] == null ? undefined : json['height'],
        'weight': json['weight'] == null ? undefined : json['weight'],
        'contactInformation': NEXUZR005APIsContactInformationFromJSON(json['contactInformation']),
        'emergencyContact': json['emergencyContact'] == null ? undefined : NEXUZR005APIsEmergencyContactFromJSON(json['emergencyContact']),
        'marketingMails': json['marketingMails'] == null ? undefined : json['marketingMails'],
        'seats': json['seats'] == null ? undefined : ((json['seats'] as Array<any>).map(NEXUZR005APIsSeatFromJSON)),
        'services': json['services'] == null ? undefined : ((json['services'] as Array<any>).map(NEXUZR005APIsServiceFromJSON)),
        'bundles': json['bundles'] == null ? undefined : ((json['bundles'] as Array<any>).map(NEXUZR005APIsBundleFromJSON)),
    };
}

export function NEXUZR005APIsPassengerDetailsToJSON(json: any): NEXUZR005APIsPassengerDetails {
    return NEXUZR005APIsPassengerDetailsToJSONTyped(json, false);
}

export function NEXUZR005APIsPassengerDetailsToJSONTyped(value?: NEXUZR005APIsPassengerDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'passengerType': value['passengerType'],
        'associateWithPassengerId': value['associateWithPassengerId'],
        'firstName': value['firstName'],
        'middleName': value['middleName'],
        'lastName': value['lastName'],
        'dateOfBirth': value['dateOfBirth'],
        'gender': value['gender'],
        'redressNumber': value['redressNumber'],
        'knownTravelerNumber': value['knownTravelerNumber'],
        'nationality': value['nationality'],
        'isPrimaryPassenger': value['isPrimaryPassenger'],
        'height': value['height'],
        'weight': value['weight'],
        'contactInformation': NEXUZR005APIsContactInformationToJSON(value['contactInformation']),
        'emergencyContact': NEXUZR005APIsEmergencyContactToJSON(value['emergencyContact']),
        'marketingMails': value['marketingMails'],
        'seats': value['seats'] == null ? undefined : ((value['seats'] as Array<any>).map(NEXUZR005APIsSeatToJSON)),
        'services': value['services'] == null ? undefined : ((value['services'] as Array<any>).map(NEXUZR005APIsServiceToJSON)),
        'bundles': value['bundles'] == null ? undefined : ((value['bundles'] as Array<any>).map(NEXUZR005APIsBundleToJSON)),
    };
}

