/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR005APIsResponseData
 */
export interface NEXUZR005APIsResponseData {
    /**
     * Encrypted Arkose token for fraud detection.
     * @type {string}
     * @memberof NEXUZR005APIsResponseData
     */
    token: string;
}

/**
 * Check if a given object implements the NEXUZR005APIsResponseData interface.
 */
export function instanceOfNEXUZR005APIsResponseData(value: object): value is NEXUZR005APIsResponseData {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsResponseDataFromJSON(json: any): NEXUZR005APIsResponseData {
    return NEXUZR005APIsResponseDataFromJSONTyped(json, false);
}

export function NEXUZR005APIsResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function NEXUZR005APIsResponseDataToJSON(json: any): NEXUZR005APIsResponseData {
    return NEXUZR005APIsResponseDataToJSONTyped(json, false);
}

export function NEXUZR005APIsResponseDataToJSONTyped(value?: NEXUZR005APIsResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

