/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR006PaymentRecipientInfo
 */
export interface NEXUZR006PaymentRecipientInfo {
    /**
     * Recipient first name for receipt issuance.
     * @type {string}
     * @memberof NEXUZR006PaymentRecipientInfo
     */
    firstName: string;
    /**
     * Recipient last name for receipt issuance.
     * @type {string}
     * @memberof NEXUZR006PaymentRecipientInfo
     */
    lastName: string;
    /**
     * Recipient middle name for receipt issuance.
     * @type {string}
     * @memberof NEXUZR006PaymentRecipientInfo
     */
    middleName?: string;
    /**
     * Recipient email address for receipt issuance.
     * @type {string}
     * @memberof NEXUZR006PaymentRecipientInfo
     */
    emailAddress: string;
}

/**
 * Check if a given object implements the NEXUZR006PaymentRecipientInfo interface.
 */
export function instanceOfNEXUZR006PaymentRecipientInfo(value: object): value is NEXUZR006PaymentRecipientInfo {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('emailAddress' in value) || value['emailAddress'] === undefined) return false;
    return true;
}

export function NEXUZR006PaymentRecipientInfoFromJSON(json: any): NEXUZR006PaymentRecipientInfo {
    return NEXUZR006PaymentRecipientInfoFromJSONTyped(json, false);
}

export function NEXUZR006PaymentRecipientInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR006PaymentRecipientInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'middleName': json['middleName'] == null ? undefined : json['middleName'],
        'emailAddress': json['emailAddress'],
    };
}

export function NEXUZR006PaymentRecipientInfoToJSON(json: any): NEXUZR006PaymentRecipientInfo {
    return NEXUZR006PaymentRecipientInfoToJSONTyped(json, false);
}

export function NEXUZR006PaymentRecipientInfoToJSONTyped(value?: NEXUZR006PaymentRecipientInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'middleName': value['middleName'],
        'emailAddress': value['emailAddress'],
    };
}

