/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Standard error response body returned when the API fails.
 * @export
 * @interface NEXUZR007OrderManagementErrorResponse
 */
export interface NEXUZR007OrderManagementErrorResponse {
    /**
     * Application-specific error code.
     * @type {string}
     * @memberof NEXUZR007OrderManagementErrorResponse
     */
    code: string;
    /**
     * Human-readable error message.
     * @type {string}
     * @memberof NEXUZR007OrderManagementErrorResponse
     */
    description: string;
}

/**
 * Check if a given object implements the NEXUZR007OrderManagementErrorResponse interface.
 */
export function instanceOfNEXUZR007OrderManagementErrorResponse(value: object): value is NEXUZR007OrderManagementErrorResponse {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function NEXUZR007OrderManagementErrorResponseFromJSON(json: any): NEXUZR007OrderManagementErrorResponse {
    return NEXUZR007OrderManagementErrorResponseFromJSONTyped(json, false);
}

export function NEXUZR007OrderManagementErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR007OrderManagementErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'description': json['description'],
    };
}

export function NEXUZR007OrderManagementErrorResponseToJSON(json: any): NEXUZR007OrderManagementErrorResponse {
    return NEXUZR007OrderManagementErrorResponseToJSONTyped(json, false);
}

export function NEXUZR007OrderManagementErrorResponseToJSONTyped(value?: NEXUZR007OrderManagementErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'description': value['description'],
    };
}

