/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR005APIsFareDetails } from './NEXUZR005APIsFareDetails';
import {
    NEXUZR005APIsFareDetailsFromJSON,
    NEXUZR005APIsFareDetailsFromJSONTyped,
    NEXUZR005APIsFareDetailsToJSON,
    NEXUZR005APIsFareDetailsToJSONTyped,
} from './NEXUZR005APIsFareDetails';
import type { NEXUZR005APIsScheduledDateTime } from './NEXUZR005APIsScheduledDateTime';
import {
    NEXUZR005APIsScheduledDateTimeFromJSON,
    NEXUZR005APIsScheduledDateTimeFromJSONTyped,
    NEXUZR005APIsScheduledDateTimeToJSON,
    NEXUZR005APIsScheduledDateTimeToJSONTyped,
} from './NEXUZR005APIsScheduledDateTime';

/**
 * 
 * @export
 * @interface NEXUZR005APIsFlightSegment
 */
export interface NEXUZR005APIsFlightSegment {
    /**
     * Airline carrier code.
     * @type {string}
     * @memberof NEXUZR005APIsFlightSegment
     */
    carrierCode: string;
    /**
     * 3-letter IATA airport code for departure.
     * @type {string}
     * @memberof NEXUZR005APIsFlightSegment
     */
    origin: string;
    /**
     * 3-letter IATA airport code for arrival.
     * @type {string}
     * @memberof NEXUZR005APIsFlightSegment
     */
    destination: string;
    /**
     * Numeric flight number.
     * @type {number}
     * @memberof NEXUZR005APIsFlightSegment
     */
    flightNumber: number;
    /**
     * Physical Flight ID (PFID).
     * @type {number}
     * @memberof NEXUZR005APIsFlightSegment
     */
    pfid: number;
    /**
     * Logical Flight ID (LFID).
     * @type {number}
     * @memberof NEXUZR005APIsFlightSegment
     */
    lfid: number;
    /**
     * Cabin type/class.
     * @type {NEXUZR005APIsFlightSegmentCabinEnum}
     * @memberof NEXUZR005APIsFlightSegment
     */
    cabin: NEXUZR005APIsFlightSegmentCabinEnum;
    /**
     * 
     * @type {NEXUZR005APIsScheduledDateTime}
     * @memberof NEXUZR005APIsFlightSegment
     */
    scheduledDepartureArrivalDateTime: NEXUZR005APIsScheduledDateTime;
    /**
     * Fare details for the segment.
     * @type {Array<NEXUZR005APIsFareDetails>}
     * @memberof NEXUZR005APIsFlightSegment
     */
    fareDetails: Array<NEXUZR005APIsFareDetails>;
}


/**
 * @export
 */
export const NEXUZR005APIsFlightSegmentCabinEnum = {
    standard: 'STANDARD',
    zipfullflat: 'ZIPFULLFLAT'
} as const;
export type NEXUZR005APIsFlightSegmentCabinEnum = typeof NEXUZR005APIsFlightSegmentCabinEnum[keyof typeof NEXUZR005APIsFlightSegmentCabinEnum];


/**
 * Check if a given object implements the NEXUZR005APIsFlightSegment interface.
 */
export function instanceOfNEXUZR005APIsFlightSegment(value: object): value is NEXUZR005APIsFlightSegment {
    if (!('carrierCode' in value) || value['carrierCode'] === undefined) return false;
    if (!('origin' in value) || value['origin'] === undefined) return false;
    if (!('destination' in value) || value['destination'] === undefined) return false;
    if (!('flightNumber' in value) || value['flightNumber'] === undefined) return false;
    if (!('pfid' in value) || value['pfid'] === undefined) return false;
    if (!('lfid' in value) || value['lfid'] === undefined) return false;
    if (!('cabin' in value) || value['cabin'] === undefined) return false;
    if (!('scheduledDepartureArrivalDateTime' in value) || value['scheduledDepartureArrivalDateTime'] === undefined) return false;
    if (!('fareDetails' in value) || value['fareDetails'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsFlightSegmentFromJSON(json: any): NEXUZR005APIsFlightSegment {
    return NEXUZR005APIsFlightSegmentFromJSONTyped(json, false);
}

export function NEXUZR005APIsFlightSegmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsFlightSegment {
    if (json == null) {
        return json;
    }
    return {
        
        'carrierCode': json['carrierCode'],
        'origin': json['origin'],
        'destination': json['destination'],
        'flightNumber': json['flightNumber'],
        'pfid': json['pfid'],
        'lfid': json['lfid'],
        'cabin': json['cabin'],
        'scheduledDepartureArrivalDateTime': NEXUZR005APIsScheduledDateTimeFromJSON(json['scheduledDepartureArrivalDateTime']),
        'fareDetails': ((json['fareDetails'] as Array<any>).map(NEXUZR005APIsFareDetailsFromJSON)),
    };
}

export function NEXUZR005APIsFlightSegmentToJSON(json: any): NEXUZR005APIsFlightSegment {
    return NEXUZR005APIsFlightSegmentToJSONTyped(json, false);
}

export function NEXUZR005APIsFlightSegmentToJSONTyped(value?: NEXUZR005APIsFlightSegment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'carrierCode': value['carrierCode'],
        'origin': value['origin'],
        'destination': value['destination'],
        'flightNumber': value['flightNumber'],
        'pfid': value['pfid'],
        'lfid': value['lfid'],
        'cabin': value['cabin'],
        'scheduledDepartureArrivalDateTime': NEXUZR005APIsScheduledDateTimeToJSON(value['scheduledDepartureArrivalDateTime']),
        'fareDetails': ((value['fareDetails'] as Array<any>).map(NEXUZR005APIsFareDetailsToJSON)),
    };
}

