/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR006PaymentInitializePaymentResponseData } from './NEXUZR006PaymentInitializePaymentResponseData';
import {
    NEXUZR006PaymentInitializePaymentResponseDataFromJSON,
    NEXUZR006PaymentInitializePaymentResponseDataFromJSONTyped,
    NEXUZR006PaymentInitializePaymentResponseDataToJSON,
    NEXUZR006PaymentInitializePaymentResponseDataToJSONTyped,
} from './NEXUZR006PaymentInitializePaymentResponseData';

/**
 * 
 * @export
 * @interface NEXUZR006PaymentInitializePaymentResponse
 */
export interface NEXUZR006PaymentInitializePaymentResponse {
    /**
     * 
     * @type {NEXUZR006PaymentInitializePaymentResponseData}
     * @memberof NEXUZR006PaymentInitializePaymentResponse
     */
    data: NEXUZR006PaymentInitializePaymentResponseData;
}

/**
 * Check if a given object implements the NEXUZR006PaymentInitializePaymentResponse interface.
 */
export function instanceOfNEXUZR006PaymentInitializePaymentResponse(value: object): value is NEXUZR006PaymentInitializePaymentResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function NEXUZR006PaymentInitializePaymentResponseFromJSON(json: any): NEXUZR006PaymentInitializePaymentResponse {
    return NEXUZR006PaymentInitializePaymentResponseFromJSONTyped(json, false);
}

export function NEXUZR006PaymentInitializePaymentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR006PaymentInitializePaymentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': NEXUZR006PaymentInitializePaymentResponseDataFromJSON(json['data']),
    };
}

export function NEXUZR006PaymentInitializePaymentResponseToJSON(json: any): NEXUZR006PaymentInitializePaymentResponse {
    return NEXUZR006PaymentInitializePaymentResponseToJSONTyped(json, false);
}

export function NEXUZR006PaymentInitializePaymentResponseToJSONTyped(value?: NEXUZR006PaymentInitializePaymentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': NEXUZR006PaymentInitializePaymentResponseDataToJSON(value['data']),
    };
}

