/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for retrieving PNR details.
 * @export
 * @interface NEXUZR007OrderManagementPnrInfoRequest
 */
export interface NEXUZR007OrderManagementPnrInfoRequest {
    /**
     * confirmation number.
     * @type {string}
     * @memberof NEXUZR007OrderManagementPnrInfoRequest
     */
    confirmationNumber: string;
}

/**
 * Check if a given object implements the NEXUZR007OrderManagementPnrInfoRequest interface.
 */
export function instanceOfNEXUZR007OrderManagementPnrInfoRequest(value: object): value is NEXUZR007OrderManagementPnrInfoRequest {
    if (!('confirmationNumber' in value) || value['confirmationNumber'] === undefined) return false;
    return true;
}

export function NEXUZR007OrderManagementPnrInfoRequestFromJSON(json: any): NEXUZR007OrderManagementPnrInfoRequest {
    return NEXUZR007OrderManagementPnrInfoRequestFromJSONTyped(json, false);
}

export function NEXUZR007OrderManagementPnrInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR007OrderManagementPnrInfoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'confirmationNumber': json['confirmationNumber'],
    };
}

export function NEXUZR007OrderManagementPnrInfoRequestToJSON(json: any): NEXUZR007OrderManagementPnrInfoRequest {
    return NEXUZR007OrderManagementPnrInfoRequestToJSONTyped(json, false);
}

export function NEXUZR007OrderManagementPnrInfoRequestToJSONTyped(value?: NEXUZR007OrderManagementPnrInfoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'confirmationNumber': value['confirmationNumber'],
    };
}

