/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Minimum fare summary for a specific date.
 * @export
 * @interface NEXUZR003FlightsAirCalendarFare
 */
export interface NEXUZR003FlightsAirCalendarFare {
    /**
     * The departure date in `yyyy-MM-dd` format.
     * @type {string}
     * @memberof NEXUZR003FlightsAirCalendarFare
     */
    date: string;
    /**
     * Total base fare amount of the flight with the minimum total fare on that date.
     * @type {number}
     * @memberof NEXUZR003FlightsAirCalendarFare
     */
    baseFareAmount: number;
    /**
     * Minimum total fare amount for adult passenger across all flights on that date.
     * @type {number}
     * @memberof NEXUZR003FlightsAirCalendarFare
     */
    totalFareAmount: number;
}

/**
 * Check if a given object implements the NEXUZR003FlightsAirCalendarFare interface.
 */
export function instanceOfNEXUZR003FlightsAirCalendarFare(value: object): value is NEXUZR003FlightsAirCalendarFare {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('baseFareAmount' in value) || value['baseFareAmount'] === undefined) return false;
    if (!('totalFareAmount' in value) || value['totalFareAmount'] === undefined) return false;
    return true;
}

export function NEXUZR003FlightsAirCalendarFareFromJSON(json: any): NEXUZR003FlightsAirCalendarFare {
    return NEXUZR003FlightsAirCalendarFareFromJSONTyped(json, false);
}

export function NEXUZR003FlightsAirCalendarFareFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR003FlightsAirCalendarFare {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'baseFareAmount': json['baseFareAmount'],
        'totalFareAmount': json['totalFareAmount'],
    };
}

export function NEXUZR003FlightsAirCalendarFareToJSON(json: any): NEXUZR003FlightsAirCalendarFare {
    return NEXUZR003FlightsAirCalendarFareToJSONTyped(json, false);
}

export function NEXUZR003FlightsAirCalendarFareToJSONTyped(value?: NEXUZR003FlightsAirCalendarFare | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'baseFareAmount': value['baseFareAmount'],
        'totalFareAmount': value['totalFareAmount'],
    };
}

