/* tslint:disable */
/* eslint-disable */
/**
 * NEXU-Z API
 * API for retrieving bundle information based on flight details and passenger information.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR003FlightsTax } from './NEXUZR003FlightsTax';
import {
    NEXUZR003FlightsTaxFromJSON,
    NEXUZR003FlightsTaxFromJSONTyped,
    NEXUZR003FlightsTaxToJSON,
    NEXUZR003FlightsTaxToJSONTyped,
} from './NEXUZR003FlightsTax';

/**
 * Fare detail for a specific passenger type and cabin.
 * @export
 * @interface NEXUZR003FlightsFare
 */
export interface NEXUZR003FlightsFare {
    /**
     * Fare ID.
     * @type {number}
     * @memberof NEXUZR003FlightsFare
     */
    fareId: number;
    /**
     * Fare class code.
     * @type {string}
     * @memberof NEXUZR003FlightsFare
     */
    fareClass: string | null;
    /**
     * Fare basis code.
     * @type {string}
     * @memberof NEXUZR003FlightsFare
     */
    fareBasisCode: string;
    /**
     * Passenger type.
     * @type {NEXUZR003FlightsFarePassengerTypeEnum}
     * @memberof NEXUZR003FlightsFare
     */
    passengerType: NEXUZR003FlightsFarePassengerTypeEnum;
    /**
     * Cabin code.
     * @type {string}
     * @memberof NEXUZR003FlightsFare
     */
    cabinCode: string;
    /**
     * Number of available seats.
     * @type {number}
     * @memberof NEXUZR003FlightsFare
     */
    availableSeat?: number | null;
    /**
     * Base fare amount (excluding taxes).
     * @type {number}
     * @memberof NEXUZR003FlightsFare
     */
    baseFareAmt?: number | null;
    /**
     * Fare amount (excluding taxes).
     * @type {number}
     * @memberof NEXUZR003FlightsFare
     */
    fareAmt: number;
    /**
     * Base fare amount including taxes before promotion discount.
     * @type {number}
     * @memberof NEXUZR003FlightsFare
     */
    baseFareAmtInclTax: number;
    /**
     * Total fare amount including taxes after promotion discount.
     * @type {number}
     * @memberof NEXUZR003FlightsFare
     */
    fareAmtInclTax: number;
    /**
     * Total fare amount for given passenger type.
     * @type {number}
     * @memberof NEXUZR003FlightsFare
     */
    ptcTotalFare: number;
    /**
     * List of applicable taxes for this fare.
     * @type {Array<NEXUZR003FlightsTax>}
     * @memberof NEXUZR003FlightsFare
     */
    taxes: Array<NEXUZR003FlightsTax>;
}


/**
 * @export
 */
export const NEXUZR003FlightsFarePassengerTypeEnum = {
    adult: 'adult',
    childA: 'childA',
    childB: 'childB',
    childC: 'childC',
    infant: 'infant'
} as const;
export type NEXUZR003FlightsFarePassengerTypeEnum = typeof NEXUZR003FlightsFarePassengerTypeEnum[keyof typeof NEXUZR003FlightsFarePassengerTypeEnum];


/**
 * Check if a given object implements the NEXUZR003FlightsFare interface.
 */
export function instanceOfNEXUZR003FlightsFare(value: object): value is NEXUZR003FlightsFare {
    if (!('fareId' in value) || value['fareId'] === undefined) return false;
    if (!('fareClass' in value) || value['fareClass'] === undefined) return false;
    if (!('fareBasisCode' in value) || value['fareBasisCode'] === undefined) return false;
    if (!('passengerType' in value) || value['passengerType'] === undefined) return false;
    if (!('cabinCode' in value) || value['cabinCode'] === undefined) return false;
    if (!('fareAmt' in value) || value['fareAmt'] === undefined) return false;
    if (!('baseFareAmtInclTax' in value) || value['baseFareAmtInclTax'] === undefined) return false;
    if (!('fareAmtInclTax' in value) || value['fareAmtInclTax'] === undefined) return false;
    if (!('ptcTotalFare' in value) || value['ptcTotalFare'] === undefined) return false;
    if (!('taxes' in value) || value['taxes'] === undefined) return false;
    return true;
}

export function NEXUZR003FlightsFareFromJSON(json: any): NEXUZR003FlightsFare {
    return NEXUZR003FlightsFareFromJSONTyped(json, false);
}

export function NEXUZR003FlightsFareFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR003FlightsFare {
    if (json == null) {
        return json;
    }
    return {
        
        'fareId': json['fareId'],
        'fareClass': json['fareClass'],
        'fareBasisCode': json['fareBasisCode'],
        'passengerType': json['passengerType'],
        'cabinCode': json['cabinCode'],
        'availableSeat': json['availableSeat'] == null ? undefined : json['availableSeat'],
        'baseFareAmt': json['baseFareAmt'] == null ? undefined : json['baseFareAmt'],
        'fareAmt': json['fareAmt'],
        'baseFareAmtInclTax': json['baseFareAmtInclTax'],
        'fareAmtInclTax': json['fareAmtInclTax'],
        'ptcTotalFare': json['ptcTotalFare'],
        'taxes': ((json['taxes'] as Array<any>).map(NEXUZR003FlightsTaxFromJSON)),
    };
}

export function NEXUZR003FlightsFareToJSON(json: any): NEXUZR003FlightsFare {
    return NEXUZR003FlightsFareToJSONTyped(json, false);
}

export function NEXUZR003FlightsFareToJSONTyped(value?: NEXUZR003FlightsFare | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fareId': value['fareId'],
        'fareClass': value['fareClass'],
        'fareBasisCode': value['fareBasisCode'],
        'passengerType': value['passengerType'],
        'cabinCode': value['cabinCode'],
        'availableSeat': value['availableSeat'],
        'baseFareAmt': value['baseFareAmt'],
        'fareAmt': value['fareAmt'],
        'baseFareAmtInclTax': value['baseFareAmtInclTax'],
        'fareAmtInclTax': value['fareAmtInclTax'],
        'ptcTotalFare': value['ptcTotalFare'],
        'taxes': ((value['taxes'] as Array<any>).map(NEXUZR003FlightsTaxToJSON)),
    };
}

