/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR003FlightsSegment } from './NEXUZR003FlightsSegment';
import {
    NEXUZR003FlightsSegmentFromJSON,
    NEXUZR003FlightsSegmentFromJSONTyped,
    NEXUZR003FlightsSegmentToJSON,
    NEXUZR003FlightsSegmentToJSONTyped,
} from './NEXUZR003FlightsSegment';

/**
 * A single flight itinerary (direct or connecting).
 * @export
 * @interface NEXUZR003FlightsFlight
 */
export interface NEXUZR003FlightsFlight {
    /**
     * Layover/transit time for connecting flights in `HH:MM` format.
     * @type {string}
     * @memberof NEXUZR003FlightsFlight
     */
    transitTime?: string | null;
    /**
     * Total travel time including flight time of all segments and transit time in `HH:MM` format.
     * @type {string}
     * @memberof NEXUZR003FlightsFlight
     */
    overallFlightTime: string;
    /**
     * Flight segment(s).
     * @type {Array<NEXUZR003FlightsSegment>}
     * @memberof NEXUZR003FlightsFlight
     */
    segments: Array<NEXUZR003FlightsSegment>;
}

/**
 * Check if a given object implements the NEXUZR003FlightsFlight interface.
 */
export function instanceOfNEXUZR003FlightsFlight(value: object): value is NEXUZR003FlightsFlight {
    if (!('overallFlightTime' in value) || value['overallFlightTime'] === undefined) return false;
    if (!('segments' in value) || value['segments'] === undefined) return false;
    return true;
}

export function NEXUZR003FlightsFlightFromJSON(json: any): NEXUZR003FlightsFlight {
    return NEXUZR003FlightsFlightFromJSONTyped(json, false);
}

export function NEXUZR003FlightsFlightFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR003FlightsFlight {
    if (json == null) {
        return json;
    }
    return {
        
        'transitTime': json['transitTime'] == null ? undefined : json['transitTime'],
        'overallFlightTime': json['overallFlightTime'],
        'segments': ((json['segments'] as Array<any>).map(NEXUZR003FlightsSegmentFromJSON)),
    };
}

export function NEXUZR003FlightsFlightToJSON(json: any): NEXUZR003FlightsFlight {
    return NEXUZR003FlightsFlightToJSONTyped(json, false);
}

export function NEXUZR003FlightsFlightToJSONTyped(value?: NEXUZR003FlightsFlight | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transitTime': value['transitTime'],
        'overallFlightTime': value['overallFlightTime'],
        'segments': ((value['segments'] as Array<any>).map(NEXUZR003FlightsSegmentToJSON)),
    };
}

