/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR005APIsDestinationAddress
 */
export interface NEXUZR005APIsDestinationAddress {
    /**
     * Destination country.
     * @type {string}
     * @memberof NEXUZR005APIsDestinationAddress
     */
    country?: string;
    /**
     * Destination postal code.
     * @type {string}
     * @memberof NEXUZR005APIsDestinationAddress
     */
    postalCode?: string;
    /**
     * Destination state.
     * @type {string}
     * @memberof NEXUZR005APIsDestinationAddress
     */
    state?: string;
    /**
     * Destination city.
     * @type {string}
     * @memberof NEXUZR005APIsDestinationAddress
     */
    city?: string;
    /**
     * Destination address.
     * @type {string}
     * @memberof NEXUZR005APIsDestinationAddress
     */
    address?: string;
}

/**
 * Check if a given object implements the NEXUZR005APIsDestinationAddress interface.
 */
export function instanceOfNEXUZR005APIsDestinationAddress(value: object): value is NEXUZR005APIsDestinationAddress {
    return true;
}

export function NEXUZR005APIsDestinationAddressFromJSON(json: any): NEXUZR005APIsDestinationAddress {
    return NEXUZR005APIsDestinationAddressFromJSONTyped(json, false);
}

export function NEXUZR005APIsDestinationAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsDestinationAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'country': json['country'] == null ? undefined : json['country'],
        'postalCode': json['postalCode'] == null ? undefined : json['postalCode'],
        'state': json['state'] == null ? undefined : json['state'],
        'city': json['city'] == null ? undefined : json['city'],
        'address': json['address'] == null ? undefined : json['address'],
    };
}

export function NEXUZR005APIsDestinationAddressToJSON(json: any): NEXUZR005APIsDestinationAddress {
    return NEXUZR005APIsDestinationAddressToJSONTyped(json, false);
}

export function NEXUZR005APIsDestinationAddressToJSONTyped(value?: NEXUZR005APIsDestinationAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'country': value['country'],
        'postalCode': value['postalCode'],
        'state': value['state'],
        'city': value['city'],
        'address': value['address'],
    };
}

