/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR005APIsEmergencyContact
 */
export interface NEXUZR005APIsEmergencyContact {
    /**
     * Emergency contact country dialling code.
     * @type {string}
     * @memberof NEXUZR005APIsEmergencyContact
     */
    countryCode?: string;
    /**
     * Emergency contact phone number.
     * @type {string}
     * @memberof NEXUZR005APIsEmergencyContact
     */
    phoneNumber?: string;
}

/**
 * Check if a given object implements the NEXUZR005APIsEmergencyContact interface.
 */
export function instanceOfNEXUZR005APIsEmergencyContact(value: object): value is NEXUZR005APIsEmergencyContact {
    return true;
}

export function NEXUZR005APIsEmergencyContactFromJSON(json: any): NEXUZR005APIsEmergencyContact {
    return NEXUZR005APIsEmergencyContactFromJSONTyped(json, false);
}

export function NEXUZR005APIsEmergencyContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsEmergencyContact {
    if (json == null) {
        return json;
    }
    return {
        
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
    };
}

export function NEXUZR005APIsEmergencyContactToJSON(json: any): NEXUZR005APIsEmergencyContact {
    return NEXUZR005APIsEmergencyContactToJSONTyped(json, false);
}

export function NEXUZR005APIsEmergencyContactToJSONTyped(value?: NEXUZR005APIsEmergencyContact | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'countryCode': value['countryCode'],
        'phoneNumber': value['phoneNumber'],
    };
}

