/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Payment order representing the current state of the payment.
 * @export
 * @interface NEXUZR006PaymentPaymentOrder
 */
export interface NEXUZR006PaymentPaymentOrder {
    /**
     * The status of the payment.
     * @type {NEXUZR006PaymentPaymentOrderStatusEnum}
     * @memberof NEXUZR006PaymentPaymentOrder
     */
    status: NEXUZR006PaymentPaymentOrderStatusEnum;
    /**
     * PNR number associated with the payment. This field is present only when the status is 'Success'.
     * @type {string}
     * @memberof NEXUZR006PaymentPaymentOrder
     */
    confirmationNumber?: string;
}


/**
 * @export
 */
export const NEXUZR006PaymentPaymentOrderStatusEnum = {
    success: 'Success',
    failed: 'Failed',
    pending: 'Pending'
} as const;
export type NEXUZR006PaymentPaymentOrderStatusEnum = typeof NEXUZR006PaymentPaymentOrderStatusEnum[keyof typeof NEXUZR006PaymentPaymentOrderStatusEnum];


/**
 * Check if a given object implements the NEXUZR006PaymentPaymentOrder interface.
 */
export function instanceOfNEXUZR006PaymentPaymentOrder(value: object): value is NEXUZR006PaymentPaymentOrder {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function NEXUZR006PaymentPaymentOrderFromJSON(json: any): NEXUZR006PaymentPaymentOrder {
    return NEXUZR006PaymentPaymentOrderFromJSONTyped(json, false);
}

export function NEXUZR006PaymentPaymentOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR006PaymentPaymentOrder {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'confirmationNumber': json['confirmationNumber'] == null ? undefined : json['confirmationNumber'],
    };
}

export function NEXUZR006PaymentPaymentOrderToJSON(json: any): NEXUZR006PaymentPaymentOrder {
    return NEXUZR006PaymentPaymentOrderToJSONTyped(json, false);
}

export function NEXUZR006PaymentPaymentOrderToJSONTyped(value?: NEXUZR006PaymentPaymentOrder | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'confirmationNumber': value['confirmationNumber'],
    };
}

