/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Tax amount for a specific passenger type under a given tax code.
 * @export
 * @interface NEXUZR003FlightsPassengerWiseTax
 */
export interface NEXUZR003FlightsPassengerWiseTax {
    /**
     * Passenger type.
     * @type {NEXUZR003FlightsPassengerWiseTaxPassengerTypeEnum}
     * @memberof NEXUZR003FlightsPassengerWiseTax
     */
    passengerType: NEXUZR003FlightsPassengerWiseTaxPassengerTypeEnum;
    /**
     * Number of passengers of this type.
     * @type {number}
     * @memberof NEXUZR003FlightsPassengerWiseTax
     */
    passengerCount: number;
    /**
     * Tax amount for this passenger type under this tax code.
     * @type {number}
     * @memberof NEXUZR003FlightsPassengerWiseTax
     */
    amount: number;
}


/**
 * @export
 */
export const NEXUZR003FlightsPassengerWiseTaxPassengerTypeEnum = {
    adult: 'adult',
    childA: 'childA',
    childB: 'childB',
    childC: 'childC',
    infant: 'infant'
} as const;
export type NEXUZR003FlightsPassengerWiseTaxPassengerTypeEnum = typeof NEXUZR003FlightsPassengerWiseTaxPassengerTypeEnum[keyof typeof NEXUZR003FlightsPassengerWiseTaxPassengerTypeEnum];


/**
 * Check if a given object implements the NEXUZR003FlightsPassengerWiseTax interface.
 */
export function instanceOfNEXUZR003FlightsPassengerWiseTax(value: object): value is NEXUZR003FlightsPassengerWiseTax {
    if (!('passengerType' in value) || value['passengerType'] === undefined) return false;
    if (!('passengerCount' in value) || value['passengerCount'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function NEXUZR003FlightsPassengerWiseTaxFromJSON(json: any): NEXUZR003FlightsPassengerWiseTax {
    return NEXUZR003FlightsPassengerWiseTaxFromJSONTyped(json, false);
}

export function NEXUZR003FlightsPassengerWiseTaxFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR003FlightsPassengerWiseTax {
    if (json == null) {
        return json;
    }
    return {
        
        'passengerType': json['passengerType'],
        'passengerCount': json['passengerCount'],
        'amount': json['amount'],
    };
}

export function NEXUZR003FlightsPassengerWiseTaxToJSON(json: any): NEXUZR003FlightsPassengerWiseTax {
    return NEXUZR003FlightsPassengerWiseTaxToJSONTyped(json, false);
}

export function NEXUZR003FlightsPassengerWiseTaxToJSONTyped(value?: NEXUZR003FlightsPassengerWiseTax | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'passengerType': value['passengerType'],
        'passengerCount': value['passengerCount'],
        'amount': value['amount'],
    };
}

