/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR002SearchFareDateEntry
 */
export interface NEXUZR002SearchFareDateEntry {
    /**
     * Travel date to be shown in the calendar.
     * @type {string}
     * @memberof NEXUZR002SearchFareDateEntry
     */
    date: string;
    /**
     * Applicable when a promoCode is provided.
     * @type {number}
     * @memberof NEXUZR002SearchFareDateEntry
     */
    baseFareForPromotion?: number;
    /**
     * Lowest fare amount for the cabin on the given date.
     * @type {number}
     * @memberof NEXUZR002SearchFareDateEntry
     */
    lowestPrice: number;
}

/**
 * Check if a given object implements the NEXUZR002SearchFareDateEntry interface.
 */
export function instanceOfNEXUZR002SearchFareDateEntry(value: object): value is NEXUZR002SearchFareDateEntry {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('lowestPrice' in value) || value['lowestPrice'] === undefined) return false;
    return true;
}

export function NEXUZR002SearchFareDateEntryFromJSON(json: any): NEXUZR002SearchFareDateEntry {
    return NEXUZR002SearchFareDateEntryFromJSONTyped(json, false);
}

export function NEXUZR002SearchFareDateEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR002SearchFareDateEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'],
        'baseFareForPromotion': json['baseFareForPromotion'] == null ? undefined : json['baseFareForPromotion'],
        'lowestPrice': json['lowestPrice'],
    };
}

export function NEXUZR002SearchFareDateEntryToJSON(json: any): NEXUZR002SearchFareDateEntry {
    return NEXUZR002SearchFareDateEntryToJSONTyped(json, false);
}

export function NEXUZR002SearchFareDateEntryToJSONTyped(value?: NEXUZR002SearchFareDateEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'baseFareForPromotion': value['baseFareForPromotion'],
        'lowestPrice': value['lowestPrice'],
    };
}

