/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR004OffersFlightSeatMapResponseData } from './NEXUZR004OffersFlightSeatMapResponseData';
import {
    NEXUZR004OffersFlightSeatMapResponseDataFromJSON,
    NEXUZR004OffersFlightSeatMapResponseDataFromJSONTyped,
    NEXUZR004OffersFlightSeatMapResponseDataToJSON,
    NEXUZR004OffersFlightSeatMapResponseDataToJSONTyped,
} from './NEXUZR004OffersFlightSeatMapResponseData';

/**
 * Response wrapper for seatmap includes seat Availbility of the cabin requested by the passenger.
 * @export
 * @interface NEXUZR004OffersFlightSeatMapResponse
 */
export interface NEXUZR004OffersFlightSeatMapResponse {
    /**
     * 
     * @type {NEXUZR004OffersFlightSeatMapResponseData}
     * @memberof NEXUZR004OffersFlightSeatMapResponse
     */
    data?: NEXUZR004OffersFlightSeatMapResponseData;
}

/**
 * Check if a given object implements the NEXUZR004OffersFlightSeatMapResponse interface.
 */
export function instanceOfNEXUZR004OffersFlightSeatMapResponse(value: object): value is NEXUZR004OffersFlightSeatMapResponse {
    return true;
}

export function NEXUZR004OffersFlightSeatMapResponseFromJSON(json: any): NEXUZR004OffersFlightSeatMapResponse {
    return NEXUZR004OffersFlightSeatMapResponseFromJSONTyped(json, false);
}

export function NEXUZR004OffersFlightSeatMapResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersFlightSeatMapResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : NEXUZR004OffersFlightSeatMapResponseDataFromJSON(json['data']),
    };
}

export function NEXUZR004OffersFlightSeatMapResponseToJSON(json: any): NEXUZR004OffersFlightSeatMapResponse {
    return NEXUZR004OffersFlightSeatMapResponseToJSONTyped(json, false);
}

export function NEXUZR004OffersFlightSeatMapResponseToJSONTyped(value?: NEXUZR004OffersFlightSeatMapResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': NEXUZR004OffersFlightSeatMapResponseDataToJSON(value['data']),
    };
}

