/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR001CoreTokenData
 */
export interface NEXUZR001CoreTokenData {
    /**
     * The WBS-generated security token. The token is an encrypted value and is valid for 30 minutes.
     * @type {string}
     * @memberof NEXUZR001CoreTokenData
     */
    accessToken: string;
}

/**
 * Check if a given object implements the NEXUZR001CoreTokenData interface.
 */
export function instanceOfNEXUZR001CoreTokenData(value: object): value is NEXUZR001CoreTokenData {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    return true;
}

export function NEXUZR001CoreTokenDataFromJSON(json: any): NEXUZR001CoreTokenData {
    return NEXUZR001CoreTokenDataFromJSONTyped(json, false);
}

export function NEXUZR001CoreTokenDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR001CoreTokenData {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
    };
}

export function NEXUZR001CoreTokenDataToJSON(json: any): NEXUZR001CoreTokenData {
    return NEXUZR001CoreTokenDataToJSONTyped(json, false);
}

export function NEXUZR001CoreTokenDataToJSONTyped(value?: NEXUZR001CoreTokenData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
    };
}

