/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR006PaymentPaymentOrder } from './NEXUZR006PaymentPaymentOrder';
import {
    NEXUZR006PaymentPaymentOrderFromJSON,
    NEXUZR006PaymentPaymentOrderFromJSONTyped,
    NEXUZR006PaymentPaymentOrderToJSON,
    NEXUZR006PaymentPaymentOrderToJSONTyped,
} from './NEXUZR006PaymentPaymentOrder';
import type { NEXUZR006PaymentWarningItem } from './NEXUZR006PaymentWarningItem';
import {
    NEXUZR006PaymentWarningItemFromJSON,
    NEXUZR006PaymentWarningItemFromJSONTyped,
    NEXUZR006PaymentWarningItemToJSON,
    NEXUZR006PaymentWarningItemToJSONTyped,
} from './NEXUZR006PaymentWarningItem';

/**
 * Response body for retrieving payment status.
 * @export
 * @interface NEXUZR006PaymentPaymentStatusResponse
 */
export interface NEXUZR006PaymentPaymentStatusResponse {
    /**
     * 
     * @type {NEXUZR006PaymentWarningItem}
     * @memberof NEXUZR006PaymentPaymentStatusResponse
     */
    warning?: NEXUZR006PaymentWarningItem;
    /**
     * 
     * @type {NEXUZR006PaymentPaymentOrder}
     * @memberof NEXUZR006PaymentPaymentStatusResponse
     */
    data: NEXUZR006PaymentPaymentOrder;
}

/**
 * Check if a given object implements the NEXUZR006PaymentPaymentStatusResponse interface.
 */
export function instanceOfNEXUZR006PaymentPaymentStatusResponse(value: object): value is NEXUZR006PaymentPaymentStatusResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function NEXUZR006PaymentPaymentStatusResponseFromJSON(json: any): NEXUZR006PaymentPaymentStatusResponse {
    return NEXUZR006PaymentPaymentStatusResponseFromJSONTyped(json, false);
}

export function NEXUZR006PaymentPaymentStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR006PaymentPaymentStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'warning': json['warning'] == null ? undefined : NEXUZR006PaymentWarningItemFromJSON(json['warning']),
        'data': NEXUZR006PaymentPaymentOrderFromJSON(json['data']),
    };
}

export function NEXUZR006PaymentPaymentStatusResponseToJSON(json: any): NEXUZR006PaymentPaymentStatusResponse {
    return NEXUZR006PaymentPaymentStatusResponseToJSONTyped(json, false);
}

export function NEXUZR006PaymentPaymentStatusResponseToJSONTyped(value?: NEXUZR006PaymentPaymentStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'warning': NEXUZR006PaymentWarningItemToJSON(value['warning']),
        'data': NEXUZR006PaymentPaymentOrderToJSON(value['data']),
    };
}

