/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR005APIsSeat
 */
export interface NEXUZR005APIsSeat {
    /**
     * Logical Flight ID for the seat.
     * @type {number}
     * @memberof NEXUZR005APIsSeat
     */
    lfid: number;
    /**
     * Physical Flight ID for the seat.
     * @type {number}
     * @memberof NEXUZR005APIsSeat
     */
    pfid: number;
    /**
     * Seat row number.
     * @type {number}
     * @memberof NEXUZR005APIsSeat
     */
    row: number;
    /**
     * Seat column (alphabetic).
     * @type {string}
     * @memberof NEXUZR005APIsSeat
     */
    column: string;
    /**
     * 4-character SSR code for seat.
     * @type {string}
     * @memberof NEXUZR005APIsSeat
     */
    serviceCode: string;
    /**
     * Seat price (numeric with max 2 decimal places).
     * @type {number}
     * @memberof NEXUZR005APIsSeat
     */
    amount: number;
    /**
     * 4-character bundle code associated with seat (optional).
     * @type {string}
     * @memberof NEXUZR005APIsSeat
     */
    bundleCode?: string;
}

/**
 * Check if a given object implements the NEXUZR005APIsSeat interface.
 */
export function instanceOfNEXUZR005APIsSeat(value: object): value is NEXUZR005APIsSeat {
    if (!('lfid' in value) || value['lfid'] === undefined) return false;
    if (!('pfid' in value) || value['pfid'] === undefined) return false;
    if (!('row' in value) || value['row'] === undefined) return false;
    if (!('column' in value) || value['column'] === undefined) return false;
    if (!('serviceCode' in value) || value['serviceCode'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsSeatFromJSON(json: any): NEXUZR005APIsSeat {
    return NEXUZR005APIsSeatFromJSONTyped(json, false);
}

export function NEXUZR005APIsSeatFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsSeat {
    if (json == null) {
        return json;
    }
    return {
        
        'lfid': json['lfid'],
        'pfid': json['pfid'],
        'row': json['row'],
        'column': json['column'],
        'serviceCode': json['serviceCode'],
        'amount': json['amount'],
        'bundleCode': json['bundleCode'] == null ? undefined : json['bundleCode'],
    };
}

export function NEXUZR005APIsSeatToJSON(json: any): NEXUZR005APIsSeat {
    return NEXUZR005APIsSeatToJSONTyped(json, false);
}

export function NEXUZR005APIsSeatToJSONTyped(value?: NEXUZR005APIsSeat | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lfid': value['lfid'],
        'pfid': value['pfid'],
        'row': value['row'],
        'column': value['column'],
        'serviceCode': value['serviceCode'],
        'amount': value['amount'],
        'bundleCode': value['bundleCode'],
    };
}

