/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR003FlightsAirCalendarFare } from './NEXUZR003FlightsAirCalendarFare';
import {
    NEXUZR003FlightsAirCalendarFareFromJSON,
    NEXUZR003FlightsAirCalendarFareFromJSONTyped,
    NEXUZR003FlightsAirCalendarFareToJSON,
    NEXUZR003FlightsAirCalendarFareToJSONTyped,
} from './NEXUZR003FlightsAirCalendarFare';
import type { NEXUZR003FlightsFlightsByDate } from './NEXUZR003FlightsFlightsByDate';
import {
    NEXUZR003FlightsFlightsByDateFromJSON,
    NEXUZR003FlightsFlightsByDateFromJSONTyped,
    NEXUZR003FlightsFlightsByDateToJSON,
    NEXUZR003FlightsFlightsByDateToJSONTyped,
} from './NEXUZR003FlightsFlightsByDate';

/**
 * Flight data for a single bound (outbound or inbound).
 * @export
 * @interface NEXUZR003FlightsBoundData
 */
export interface NEXUZR003FlightsBoundData {
    /**
     * Calendar-level fare summary per date.
     * @type {Array<NEXUZR003FlightsAirCalendarFare>}
     * @memberof NEXUZR003FlightsBoundData
     */
    airCalendarFare?: Array<NEXUZR003FlightsAirCalendarFare>;
    /**
     * List of flights grouped by departure date.
     * @type {Array<NEXUZR003FlightsFlightsByDate>}
     * @memberof NEXUZR003FlightsBoundData
     */
    flightsByDate?: Array<NEXUZR003FlightsFlightsByDate>;
}

/**
 * Check if a given object implements the NEXUZR003FlightsBoundData interface.
 */
export function instanceOfNEXUZR003FlightsBoundData(value: object): value is NEXUZR003FlightsBoundData {
    return true;
}

export function NEXUZR003FlightsBoundDataFromJSON(json: any): NEXUZR003FlightsBoundData {
    return NEXUZR003FlightsBoundDataFromJSONTyped(json, false);
}

export function NEXUZR003FlightsBoundDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR003FlightsBoundData {
    if (json == null) {
        return json;
    }
    return {
        
        'airCalendarFare': json['airCalendarFare'] == null ? undefined : ((json['airCalendarFare'] as Array<any>).map(NEXUZR003FlightsAirCalendarFareFromJSON)),
        'flightsByDate': json['flightsByDate'] == null ? undefined : ((json['flightsByDate'] as Array<any>).map(NEXUZR003FlightsFlightsByDateFromJSON)),
    };
}

export function NEXUZR003FlightsBoundDataToJSON(json: any): NEXUZR003FlightsBoundData {
    return NEXUZR003FlightsBoundDataToJSONTyped(json, false);
}

export function NEXUZR003FlightsBoundDataToJSONTyped(value?: NEXUZR003FlightsBoundData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'airCalendarFare': value['airCalendarFare'] == null ? undefined : ((value['airCalendarFare'] as Array<any>).map(NEXUZR003FlightsAirCalendarFareToJSON)),
        'flightsByDate': value['flightsByDate'] == null ? undefined : ((value['flightsByDate'] as Array<any>).map(NEXUZR003FlightsFlightsByDateToJSON)),
    };
}

