/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR003FlightsBoundSummary } from './NEXUZR003FlightsBoundSummary';
import {
    NEXUZR003FlightsBoundSummaryFromJSON,
    NEXUZR003FlightsBoundSummaryFromJSONTyped,
    NEXUZR003FlightsBoundSummaryToJSON,
    NEXUZR003FlightsBoundSummaryToJSONTyped,
} from './NEXUZR003FlightsBoundSummary';
import type { NEXUZR003FlightsFareDetail } from './NEXUZR003FlightsFareDetail';
import {
    NEXUZR003FlightsFareDetailFromJSON,
    NEXUZR003FlightsFareDetailFromJSONTyped,
    NEXUZR003FlightsFareDetailToJSON,
    NEXUZR003FlightsFareDetailToJSONTyped,
} from './NEXUZR003FlightsFareDetail';

/**
 * Fare detail grouped by cabin type.
 * @export
 * @interface NEXUZR003FlightsFareInfo
 */
export interface NEXUZR003FlightsFareInfo {
    /**
     * Cabin type.
     * @type {string}
     * @memberof NEXUZR003FlightsFareInfo
     */
    cabin: string;
    /**
     * 
     * @type {NEXUZR003FlightsBoundSummary}
     * @memberof NEXUZR003FlightsFareInfo
     */
    boundSummary: NEXUZR003FlightsBoundSummary;
    /**
     * Per-passenger-type fare breakdown for this cabin.
     * @type {Array<NEXUZR003FlightsFareDetail>}
     * @memberof NEXUZR003FlightsFareInfo
     */
    fareDetails: Array<NEXUZR003FlightsFareDetail>;
}

/**
 * Check if a given object implements the NEXUZR003FlightsFareInfo interface.
 */
export function instanceOfNEXUZR003FlightsFareInfo(value: object): value is NEXUZR003FlightsFareInfo {
    if (!('cabin' in value) || value['cabin'] === undefined) return false;
    if (!('boundSummary' in value) || value['boundSummary'] === undefined) return false;
    if (!('fareDetails' in value) || value['fareDetails'] === undefined) return false;
    return true;
}

export function NEXUZR003FlightsFareInfoFromJSON(json: any): NEXUZR003FlightsFareInfo {
    return NEXUZR003FlightsFareInfoFromJSONTyped(json, false);
}

export function NEXUZR003FlightsFareInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR003FlightsFareInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'cabin': json['cabin'],
        'boundSummary': NEXUZR003FlightsBoundSummaryFromJSON(json['boundSummary']),
        'fareDetails': ((json['fareDetails'] as Array<any>).map(NEXUZR003FlightsFareDetailFromJSON)),
    };
}

export function NEXUZR003FlightsFareInfoToJSON(json: any): NEXUZR003FlightsFareInfo {
    return NEXUZR003FlightsFareInfoToJSONTyped(json, false);
}

export function NEXUZR003FlightsFareInfoToJSONTyped(value?: NEXUZR003FlightsFareInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cabin': value['cabin'],
        'boundSummary': NEXUZR003FlightsBoundSummaryToJSON(value['boundSummary']),
        'fareDetails': ((value['fareDetails'] as Array<any>).map(NEXUZR003FlightsFareDetailToJSON)),
    };
}

