/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR005APIsFlightBound } from './NEXUZR005APIsFlightBound';
import {
    NEXUZR005APIsFlightBoundFromJSON,
    NEXUZR005APIsFlightBoundFromJSONTyped,
    NEXUZR005APIsFlightBoundToJSON,
    NEXUZR005APIsFlightBoundToJSONTyped,
} from './NEXUZR005APIsFlightBound';

/**
 * 
 * @export
 * @interface NEXUZR005APIsFlights
 */
export interface NEXUZR005APIsFlights {
    /**
     * Outbound flight info.
     * @type {Array<NEXUZR005APIsFlightBound>}
     * @memberof NEXUZR005APIsFlights
     */
    outbound: Array<NEXUZR005APIsFlightBound>;
    /**
     * Inbound flight info.
     * @type {Array<NEXUZR005APIsFlightBound>}
     * @memberof NEXUZR005APIsFlights
     */
    inbound?: Array<NEXUZR005APIsFlightBound>;
}

/**
 * Check if a given object implements the NEXUZR005APIsFlights interface.
 */
export function instanceOfNEXUZR005APIsFlights(value: object): value is NEXUZR005APIsFlights {
    if (!('outbound' in value) || value['outbound'] === undefined) return false;
    return true;
}

export function NEXUZR005APIsFlightsFromJSON(json: any): NEXUZR005APIsFlights {
    return NEXUZR005APIsFlightsFromJSONTyped(json, false);
}

export function NEXUZR005APIsFlightsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR005APIsFlights {
    if (json == null) {
        return json;
    }
    return {
        
        'outbound': ((json['outbound'] as Array<any>).map(NEXUZR005APIsFlightBoundFromJSON)),
        'inbound': json['inbound'] == null ? undefined : ((json['inbound'] as Array<any>).map(NEXUZR005APIsFlightBoundFromJSON)),
    };
}

export function NEXUZR005APIsFlightsToJSON(json: any): NEXUZR005APIsFlights {
    return NEXUZR005APIsFlightsToJSONTyped(json, false);
}

export function NEXUZR005APIsFlightsToJSONTyped(value?: NEXUZR005APIsFlights | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'outbound': ((value['outbound'] as Array<any>).map(NEXUZR005APIsFlightBoundToJSON)),
        'inbound': value['inbound'] == null ? undefined : ((value['inbound'] as Array<any>).map(NEXUZR005APIsFlightBoundToJSON)),
    };
}

