/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR003FlightsTax } from './NEXUZR003FlightsTax';
import {
    NEXUZR003FlightsTaxFromJSON,
    NEXUZR003FlightsTaxFromJSONTyped,
    NEXUZR003FlightsTaxToJSON,
    NEXUZR003FlightsTaxToJSONTyped,
} from './NEXUZR003FlightsTax';

/**
 * Detailed fare information for a single passenger type within a cabin.
 * @export
 * @interface NEXUZR003FlightsFareDetail
 */
export interface NEXUZR003FlightsFareDetail {
    /**
     * Fare ID.
     * @type {number}
     * @memberof NEXUZR003FlightsFareDetail
     */
    fareId: number;
    /**
     * Fare class code.
     * @type {string}
     * @memberof NEXUZR003FlightsFareDetail
     */
    fareClass?: string | null;
    /**
     * Fare basis code.
     * @type {string}
     * @memberof NEXUZR003FlightsFareDetail
     */
    fareBasisCode: string;
    /**
     * Passenger type.
     * @type {NEXUZR003FlightsFareDetailPassengerTypeEnum}
     * @memberof NEXUZR003FlightsFareDetail
     */
    passengerType: NEXUZR003FlightsFareDetailPassengerTypeEnum;
    /**
     * Number of available seats.
     * @type {number}
     * @memberof NEXUZR003FlightsFareDetail
     */
    availableSeat?: number | null;
    /**
     * Base fare amount excluding taxes.
     * @type {number}
     * @memberof NEXUZR003FlightsFareDetail
     */
    baseFareAmt?: number | null;
    /**
     * Fare amount excluding taxes.
     * @type {number}
     * @memberof NEXUZR003FlightsFareDetail
     */
    fareAmt: number;
    /**
     * Base fare amount including taxes before promotion discount.
     * @type {number}
     * @memberof NEXUZR003FlightsFareDetail
     */
    baseFareAmtInclTax: number;
    /**
     * Total fare amount including taxes after promotion discount.
     * @type {number}
     * @memberof NEXUZR003FlightsFareDetail
     */
    fareAmtInclTax: number;
    /**
     * Fare amount including taxes after promotion discount.
     * @type {number}
     * @memberof NEXUZR003FlightsFareDetail
     */
    amtInclTax: number;
    /**
     * List of applicable taxes for this fare.
     * @type {Array<NEXUZR003FlightsTax>}
     * @memberof NEXUZR003FlightsFareDetail
     */
    taxes: Array<NEXUZR003FlightsTax>;
}


/**
 * @export
 */
export const NEXUZR003FlightsFareDetailPassengerTypeEnum = {
    adult: 'adult',
    childA: 'childA',
    childB: 'childB',
    childC: 'childC',
    infant: 'infant'
} as const;
export type NEXUZR003FlightsFareDetailPassengerTypeEnum = typeof NEXUZR003FlightsFareDetailPassengerTypeEnum[keyof typeof NEXUZR003FlightsFareDetailPassengerTypeEnum];


/**
 * Check if a given object implements the NEXUZR003FlightsFareDetail interface.
 */
export function instanceOfNEXUZR003FlightsFareDetail(value: object): value is NEXUZR003FlightsFareDetail {
    if (!('fareId' in value) || value['fareId'] === undefined) return false;
    if (!('fareBasisCode' in value) || value['fareBasisCode'] === undefined) return false;
    if (!('passengerType' in value) || value['passengerType'] === undefined) return false;
    if (!('fareAmt' in value) || value['fareAmt'] === undefined) return false;
    if (!('baseFareAmtInclTax' in value) || value['baseFareAmtInclTax'] === undefined) return false;
    if (!('fareAmtInclTax' in value) || value['fareAmtInclTax'] === undefined) return false;
    if (!('amtInclTax' in value) || value['amtInclTax'] === undefined) return false;
    if (!('taxes' in value) || value['taxes'] === undefined) return false;
    return true;
}

export function NEXUZR003FlightsFareDetailFromJSON(json: any): NEXUZR003FlightsFareDetail {
    return NEXUZR003FlightsFareDetailFromJSONTyped(json, false);
}

export function NEXUZR003FlightsFareDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR003FlightsFareDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'fareId': json['fareId'],
        'fareClass': json['fareClass'] == null ? undefined : json['fareClass'],
        'fareBasisCode': json['fareBasisCode'],
        'passengerType': json['passengerType'],
        'availableSeat': json['availableSeat'] == null ? undefined : json['availableSeat'],
        'baseFareAmt': json['baseFareAmt'] == null ? undefined : json['baseFareAmt'],
        'fareAmt': json['fareAmt'],
        'baseFareAmtInclTax': json['baseFareAmtInclTax'],
        'fareAmtInclTax': json['fareAmtInclTax'],
        'amtInclTax': json['amtInclTax'],
        'taxes': ((json['taxes'] as Array<any>).map(NEXUZR003FlightsTaxFromJSON)),
    };
}

export function NEXUZR003FlightsFareDetailToJSON(json: any): NEXUZR003FlightsFareDetail {
    return NEXUZR003FlightsFareDetailToJSONTyped(json, false);
}

export function NEXUZR003FlightsFareDetailToJSONTyped(value?: NEXUZR003FlightsFareDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fareId': value['fareId'],
        'fareClass': value['fareClass'],
        'fareBasisCode': value['fareBasisCode'],
        'passengerType': value['passengerType'],
        'availableSeat': value['availableSeat'],
        'baseFareAmt': value['baseFareAmt'],
        'fareAmt': value['fareAmt'],
        'baseFareAmtInclTax': value['baseFareAmtInclTax'],
        'fareAmtInclTax': value['fareAmtInclTax'],
        'amtInclTax': value['amtInclTax'],
        'taxes': ((value['taxes'] as Array<any>).map(NEXUZR003FlightsTaxToJSON)),
    };
}

