/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR003FlightsPassengerWiseTax } from './NEXUZR003FlightsPassengerWiseTax';
import {
    NEXUZR003FlightsPassengerWiseTaxFromJSON,
    NEXUZR003FlightsPassengerWiseTaxFromJSONTyped,
    NEXUZR003FlightsPassengerWiseTaxToJSON,
    NEXUZR003FlightsPassengerWiseTaxToJSONTyped,
} from './NEXUZR003FlightsPassengerWiseTax';

/**
 * Tax detail broken down by tax code.
 * @export
 * @interface NEXUZR003FlightsTaxBreakDown
 */
export interface NEXUZR003FlightsTaxBreakDown {
    /**
     * Tax code identifier.
     * @type {string}
     * @memberof NEXUZR003FlightsTaxBreakDown
     */
    taxCode: string;
    /**
     * Human-readable tax description.
     * @type {string}
     * @memberof NEXUZR003FlightsTaxBreakDown
     */
    description: string;
    /**
     * Total tax amount for this tax code across all passengers.
     * @type {number}
     * @memberof NEXUZR003FlightsTaxBreakDown
     */
    taxAmount: number;
    /**
     * Tax amount for this tax code broken down per passenger type.
     * @type {Array<NEXUZR003FlightsPassengerWiseTax>}
     * @memberof NEXUZR003FlightsTaxBreakDown
     */
    passengerWiseTaxes: Array<NEXUZR003FlightsPassengerWiseTax>;
}

/**
 * Check if a given object implements the NEXUZR003FlightsTaxBreakDown interface.
 */
export function instanceOfNEXUZR003FlightsTaxBreakDown(value: object): value is NEXUZR003FlightsTaxBreakDown {
    if (!('taxCode' in value) || value['taxCode'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('taxAmount' in value) || value['taxAmount'] === undefined) return false;
    if (!('passengerWiseTaxes' in value) || value['passengerWiseTaxes'] === undefined) return false;
    return true;
}

export function NEXUZR003FlightsTaxBreakDownFromJSON(json: any): NEXUZR003FlightsTaxBreakDown {
    return NEXUZR003FlightsTaxBreakDownFromJSONTyped(json, false);
}

export function NEXUZR003FlightsTaxBreakDownFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR003FlightsTaxBreakDown {
    if (json == null) {
        return json;
    }
    return {
        
        'taxCode': json['taxCode'],
        'description': json['description'],
        'taxAmount': json['taxAmount'],
        'passengerWiseTaxes': ((json['passengerWiseTaxes'] as Array<any>).map(NEXUZR003FlightsPassengerWiseTaxFromJSON)),
    };
}

export function NEXUZR003FlightsTaxBreakDownToJSON(json: any): NEXUZR003FlightsTaxBreakDown {
    return NEXUZR003FlightsTaxBreakDownToJSONTyped(json, false);
}

export function NEXUZR003FlightsTaxBreakDownToJSONTyped(value?: NEXUZR003FlightsTaxBreakDown | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taxCode': value['taxCode'],
        'description': value['description'],
        'taxAmount': value['taxAmount'],
        'passengerWiseTaxes': ((value['passengerWiseTaxes'] as Array<any>).map(NEXUZR003FlightsPassengerWiseTaxToJSON)),
    };
}

