/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NEXUZR006PaymentInitializePaymentResponseData
 */
export interface NEXUZR006PaymentInitializePaymentResponseData {
    /**
     * This field contains the orderId received from the POP.
     * @type {string}
     * @memberof NEXUZR006PaymentInitializePaymentResponseData
     */
    statusCheckKey: string;
    /**
     * This field contains the ReservationPaymentID.
     * 
     * @type {number}
     * @memberof NEXUZR006PaymentInitializePaymentResponseData
     */
    paymentReferenceId: number;
    /**
     * This field contains the UI redirection URL.
     * @type {string}
     * @memberof NEXUZR006PaymentInitializePaymentResponseData
     */
    redirectionUrl: string;
}

/**
 * Check if a given object implements the NEXUZR006PaymentInitializePaymentResponseData interface.
 */
export function instanceOfNEXUZR006PaymentInitializePaymentResponseData(value: object): value is NEXUZR006PaymentInitializePaymentResponseData {
    if (!('statusCheckKey' in value) || value['statusCheckKey'] === undefined) return false;
    if (!('paymentReferenceId' in value) || value['paymentReferenceId'] === undefined) return false;
    if (!('redirectionUrl' in value) || value['redirectionUrl'] === undefined) return false;
    return true;
}

export function NEXUZR006PaymentInitializePaymentResponseDataFromJSON(json: any): NEXUZR006PaymentInitializePaymentResponseData {
    return NEXUZR006PaymentInitializePaymentResponseDataFromJSONTyped(json, false);
}

export function NEXUZR006PaymentInitializePaymentResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR006PaymentInitializePaymentResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCheckKey': json['statusCheckKey'],
        'paymentReferenceId': json['paymentReferenceId'],
        'redirectionUrl': json['redirectionUrl'],
    };
}

export function NEXUZR006PaymentInitializePaymentResponseDataToJSON(json: any): NEXUZR006PaymentInitializePaymentResponseData {
    return NEXUZR006PaymentInitializePaymentResponseDataToJSONTyped(json, false);
}

export function NEXUZR006PaymentInitializePaymentResponseDataToJSONTyped(value?: NEXUZR006PaymentInitializePaymentResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'statusCheckKey': value['statusCheckKey'],
        'paymentReferenceId': value['paymentReferenceId'],
        'redirectionUrl': value['redirectionUrl'],
    };
}

