/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Individual tax detail applied to a fare.
 * @export
 * @interface NEXUZR003FlightsTax
 */
export interface NEXUZR003FlightsTax {
    /**
     * Tax ID.
     * @type {number}
     * @memberof NEXUZR003FlightsTax
     */
    id: number;
    /**
     * Tax amount in the requested currency.
     * @type {number}
     * @memberof NEXUZR003FlightsTax
     */
    amount: number;
    /**
     * Tax code.
     * @type {string}
     * @memberof NEXUZR003FlightsTax
     */
    taxCode: string;
    /**
     * Tax description.
     * @type {string}
     * @memberof NEXUZR003FlightsTax
     */
    taxDesc: string;
}

/**
 * Check if a given object implements the NEXUZR003FlightsTax interface.
 */
export function instanceOfNEXUZR003FlightsTax(value: object): value is NEXUZR003FlightsTax {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('taxCode' in value) || value['taxCode'] === undefined) return false;
    if (!('taxDesc' in value) || value['taxDesc'] === undefined) return false;
    return true;
}

export function NEXUZR003FlightsTaxFromJSON(json: any): NEXUZR003FlightsTax {
    return NEXUZR003FlightsTaxFromJSONTyped(json, false);
}

export function NEXUZR003FlightsTaxFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR003FlightsTax {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'amount': json['amount'],
        'taxCode': json['taxCode'],
        'taxDesc': json['taxDesc'],
    };
}

export function NEXUZR003FlightsTaxToJSON(json: any): NEXUZR003FlightsTax {
    return NEXUZR003FlightsTaxToJSONTyped(json, false);
}

export function NEXUZR003FlightsTaxToJSONTyped(value?: NEXUZR003FlightsTax | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'amount': value['amount'],
        'taxCode': value['taxCode'],
        'taxDesc': value['taxDesc'],
    };
}

