/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Fare amount for a specific passenger type.
 * @export
 * @interface NEXUZR003FlightsPassengerWiseFare
 */
export interface NEXUZR003FlightsPassengerWiseFare {
    /**
     * Passenger type.
     * @type {NEXUZR003FlightsPassengerWiseFarePassengerTypeEnum}
     * @memberof NEXUZR003FlightsPassengerWiseFare
     */
    passengerType: NEXUZR003FlightsPassengerWiseFarePassengerTypeEnum;
    /**
     * Number of passengers of this type requested.
     * @type {number}
     * @memberof NEXUZR003FlightsPassengerWiseFare
     */
    count: number;
    /**
     * Total fare for this passenger type.
     * @type {number}
     * @memberof NEXUZR003FlightsPassengerWiseFare
     */
    amount: number;
}


/**
 * @export
 */
export const NEXUZR003FlightsPassengerWiseFarePassengerTypeEnum = {
    adult: 'adult',
    childA: 'childA',
    childB: 'childB',
    childC: 'childC',
    infant: 'infant'
} as const;
export type NEXUZR003FlightsPassengerWiseFarePassengerTypeEnum = typeof NEXUZR003FlightsPassengerWiseFarePassengerTypeEnum[keyof typeof NEXUZR003FlightsPassengerWiseFarePassengerTypeEnum];


/**
 * Check if a given object implements the NEXUZR003FlightsPassengerWiseFare interface.
 */
export function instanceOfNEXUZR003FlightsPassengerWiseFare(value: object): value is NEXUZR003FlightsPassengerWiseFare {
    if (!('passengerType' in value) || value['passengerType'] === undefined) return false;
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function NEXUZR003FlightsPassengerWiseFareFromJSON(json: any): NEXUZR003FlightsPassengerWiseFare {
    return NEXUZR003FlightsPassengerWiseFareFromJSONTyped(json, false);
}

export function NEXUZR003FlightsPassengerWiseFareFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR003FlightsPassengerWiseFare {
    if (json == null) {
        return json;
    }
    return {
        
        'passengerType': json['passengerType'],
        'count': json['count'],
        'amount': json['amount'],
    };
}

export function NEXUZR003FlightsPassengerWiseFareToJSON(json: any): NEXUZR003FlightsPassengerWiseFare {
    return NEXUZR003FlightsPassengerWiseFareToJSONTyped(json, false);
}

export function NEXUZR003FlightsPassengerWiseFareToJSONTyped(value?: NEXUZR003FlightsPassengerWiseFare | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'passengerType': value['passengerType'],
        'count': value['count'],
        'amount': value['amount'],
    };
}

