/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR002SearchRoutes } from './NEXUZR002SearchRoutes';
import {
    NEXUZR002SearchRoutesFromJSON,
    NEXUZR002SearchRoutesFromJSONTyped,
    NEXUZR002SearchRoutesToJSON,
    NEXUZR002SearchRoutesToJSONTyped,
} from './NEXUZR002SearchRoutes';

/**
 * 
 * @export
 * @interface NEXUZR002SearchArrayOfRoutes
 */
export interface NEXUZR002SearchArrayOfRoutes {
    /**
     * 
     * @type {Array<Array<NEXUZR002SearchRoutes>>}
     * @memberof NEXUZR002SearchArrayOfRoutes
     */
    routeInfo: Array<Array<NEXUZR002SearchRoutes>>;
}

/**
 * Check if a given object implements the NEXUZR002SearchArrayOfRoutes interface.
 */
export function instanceOfNEXUZR002SearchArrayOfRoutes(value: object): value is NEXUZR002SearchArrayOfRoutes {
    if (!('routeInfo' in value) || value['routeInfo'] === undefined) return false;
    return true;
}

export function NEXUZR002SearchArrayOfRoutesFromJSON(json: any): NEXUZR002SearchArrayOfRoutes {
    return NEXUZR002SearchArrayOfRoutesFromJSONTyped(json, false);
}

export function NEXUZR002SearchArrayOfRoutesFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR002SearchArrayOfRoutes {
    if (json == null) {
        return json;
    }
    return {
        
        'routeInfo': json['routeInfo'],
    };
}

export function NEXUZR002SearchArrayOfRoutesToJSON(json: any): NEXUZR002SearchArrayOfRoutes {
    return NEXUZR002SearchArrayOfRoutesToJSONTyped(json, false);
}

export function NEXUZR002SearchArrayOfRoutesToJSONTyped(value?: NEXUZR002SearchArrayOfRoutes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'routeInfo': value['routeInfo'],
    };
}

