/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR004OffersPassengers } from './NEXUZR004OffersPassengers';
import {
    NEXUZR004OffersPassengersFromJSON,
    NEXUZR004OffersPassengersFromJSONTyped,
    NEXUZR004OffersPassengersToJSON,
    NEXUZR004OffersPassengersToJSONTyped,
} from './NEXUZR004OffersPassengers';

/**
 * 
 * @export
 * @interface NEXUZR004OffersAncillaryRequest
 */
export interface NEXUZR004OffersAncillaryRequest {
    /**
     * Flight departure date in `yyyy-MM-dd` format.
     * @type {string}
     * @memberof NEXUZR004OffersAncillaryRequest
     */
    departureDate: string;
    /**
     * Logical flight ID.
     * @type {number}
     * @memberof NEXUZR004OffersAncillaryRequest
     */
    lfid: number;
    /**
     * Origin airport IATA code.
     * @type {string}
     * @memberof NEXUZR004OffersAncillaryRequest
     */
    origin: string;
    /**
     * Destination airport IATA code.
     * @type {string}
     * @memberof NEXUZR004OffersAncillaryRequest
     */
    destination: string;
    /**
     * Category of the services to retrieve.
     * @type {NEXUZR004OffersAncillaryRequestServiceCategoryEnum}
     * @memberof NEXUZR004OffersAncillaryRequest
     */
    serviceCategory: NEXUZR004OffersAncillaryRequestServiceCategoryEnum;
    /**
     * 
     * @type {NEXUZR004OffersPassengers}
     * @memberof NEXUZR004OffersAncillaryRequest
     */
    passengers: NEXUZR004OffersPassengers;
}


/**
 * @export
 */
export const NEXUZR004OffersAncillaryRequestServiceCategoryEnum = {
    amenities: 'AMENITIES',
    meals: 'MEALS',
    baggage: 'BAGGAGE',
    akibazip: 'AKIBAZIP',
    inflightitem: 'INFLIGHTITEM',
    transportation: 'TRANSPORTATION',
    lounge: 'LOUNGE'
} as const;
export type NEXUZR004OffersAncillaryRequestServiceCategoryEnum = typeof NEXUZR004OffersAncillaryRequestServiceCategoryEnum[keyof typeof NEXUZR004OffersAncillaryRequestServiceCategoryEnum];


/**
 * Check if a given object implements the NEXUZR004OffersAncillaryRequest interface.
 */
export function instanceOfNEXUZR004OffersAncillaryRequest(value: object): value is NEXUZR004OffersAncillaryRequest {
    if (!('departureDate' in value) || value['departureDate'] === undefined) return false;
    if (!('lfid' in value) || value['lfid'] === undefined) return false;
    if (!('origin' in value) || value['origin'] === undefined) return false;
    if (!('destination' in value) || value['destination'] === undefined) return false;
    if (!('serviceCategory' in value) || value['serviceCategory'] === undefined) return false;
    if (!('passengers' in value) || value['passengers'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersAncillaryRequestFromJSON(json: any): NEXUZR004OffersAncillaryRequest {
    return NEXUZR004OffersAncillaryRequestFromJSONTyped(json, false);
}

export function NEXUZR004OffersAncillaryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersAncillaryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'departureDate': json['departureDate'],
        'lfid': json['lfid'],
        'origin': json['origin'],
        'destination': json['destination'],
        'serviceCategory': json['serviceCategory'],
        'passengers': NEXUZR004OffersPassengersFromJSON(json['passengers']),
    };
}

export function NEXUZR004OffersAncillaryRequestToJSON(json: any): NEXUZR004OffersAncillaryRequest {
    return NEXUZR004OffersAncillaryRequestToJSONTyped(json, false);
}

export function NEXUZR004OffersAncillaryRequestToJSONTyped(value?: NEXUZR004OffersAncillaryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'departureDate': value['departureDate'],
        'lfid': value['lfid'],
        'origin': value['origin'],
        'destination': value['destination'],
        'serviceCategory': value['serviceCategory'],
        'passengers': NEXUZR004OffersPassengersToJSON(value['passengers']),
    };
}

