/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR004OffersServiceGroup } from './NEXUZR004OffersServiceGroup';
import {
    NEXUZR004OffersServiceGroupFromJSON,
    NEXUZR004OffersServiceGroupFromJSONTyped,
    NEXUZR004OffersServiceGroupToJSON,
    NEXUZR004OffersServiceGroupToJSONTyped,
} from './NEXUZR004OffersServiceGroup';

/**
 * 
 * @export
 * @interface NEXUZR004OffersAncillaryResponse
 */
export interface NEXUZR004OffersAncillaryResponse {
    /**
     * 
     * @type {NEXUZR004OffersServiceGroup}
     * @memberof NEXUZR004OffersAncillaryResponse
     */
    data: NEXUZR004OffersServiceGroup;
}

/**
 * Check if a given object implements the NEXUZR004OffersAncillaryResponse interface.
 */
export function instanceOfNEXUZR004OffersAncillaryResponse(value: object): value is NEXUZR004OffersAncillaryResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersAncillaryResponseFromJSON(json: any): NEXUZR004OffersAncillaryResponse {
    return NEXUZR004OffersAncillaryResponseFromJSONTyped(json, false);
}

export function NEXUZR004OffersAncillaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersAncillaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': NEXUZR004OffersServiceGroupFromJSON(json['data']),
    };
}

export function NEXUZR004OffersAncillaryResponseToJSON(json: any): NEXUZR004OffersAncillaryResponse {
    return NEXUZR004OffersAncillaryResponseToJSONTyped(json, false);
}

export function NEXUZR004OffersAncillaryResponseToJSONTyped(value?: NEXUZR004OffersAncillaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': NEXUZR004OffersServiceGroupToJSON(value['data']),
    };
}

