/* tslint:disable */
/* eslint-disable */
/**
 * NEXUZ API
 * API for retrieving bundle information based on flight details and passenger information. It also retrieves seatMap based on the cabin requested by the passenger for its respective flights and provides details of available ancillaries for a particular flight.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NEXUZR004OffersServiceCategory } from './NEXUZR004OffersServiceCategory';
import {
    NEXUZR004OffersServiceCategoryFromJSON,
    NEXUZR004OffersServiceCategoryFromJSONTyped,
    NEXUZR004OffersServiceCategoryToJSON,
    NEXUZR004OffersServiceCategoryToJSONTyped,
} from './NEXUZR004OffersServiceCategory';

/**
 * 
 * @export
 * @interface NEXUZR004OffersServicesPerPassengerType
 */
export interface NEXUZR004OffersServicesPerPassengerType {
    /**
     * Passenger type based on age.
     * @type {NEXUZR004OffersServicesPerPassengerTypePassengerTypeEnum}
     * @memberof NEXUZR004OffersServicesPerPassengerType
     */
    passengerType: NEXUZR004OffersServicesPerPassengerTypePassengerTypeEnum;
    /**
     * 
     * @type {Array<NEXUZR004OffersServiceCategory>}
     * @memberof NEXUZR004OffersServicesPerPassengerType
     */
    categories: Array<NEXUZR004OffersServiceCategory>;
}


/**
 * @export
 */
export const NEXUZR004OffersServicesPerPassengerTypePassengerTypeEnum = {
    adult: 'adult',
    childA: 'childA',
    childB: 'childB',
    childC: 'childC',
    infant: 'infant'
} as const;
export type NEXUZR004OffersServicesPerPassengerTypePassengerTypeEnum = typeof NEXUZR004OffersServicesPerPassengerTypePassengerTypeEnum[keyof typeof NEXUZR004OffersServicesPerPassengerTypePassengerTypeEnum];


/**
 * Check if a given object implements the NEXUZR004OffersServicesPerPassengerType interface.
 */
export function instanceOfNEXUZR004OffersServicesPerPassengerType(value: object): value is NEXUZR004OffersServicesPerPassengerType {
    if (!('passengerType' in value) || value['passengerType'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    return true;
}

export function NEXUZR004OffersServicesPerPassengerTypeFromJSON(json: any): NEXUZR004OffersServicesPerPassengerType {
    return NEXUZR004OffersServicesPerPassengerTypeFromJSONTyped(json, false);
}

export function NEXUZR004OffersServicesPerPassengerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NEXUZR004OffersServicesPerPassengerType {
    if (json == null) {
        return json;
    }
    return {
        
        'passengerType': json['passengerType'],
        'categories': ((json['categories'] as Array<any>).map(NEXUZR004OffersServiceCategoryFromJSON)),
    };
}

export function NEXUZR004OffersServicesPerPassengerTypeToJSON(json: any): NEXUZR004OffersServicesPerPassengerType {
    return NEXUZR004OffersServicesPerPassengerTypeToJSONTyped(json, false);
}

export function NEXUZR004OffersServicesPerPassengerTypeToJSONTyped(value?: NEXUZR004OffersServicesPerPassengerType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'passengerType': value['passengerType'],
        'categories': ((value['categories'] as Array<any>).map(NEXUZR004OffersServiceCategoryToJSON)),
    };
}

